### PR TITLE
pass temperature, pressure to modelchain sol pos call

### PR DESCRIPTION
**Pull request by Ahanmr**
This PR handles, the case where pressure or temp_air is not in weather, using the pvlib.tools._build_kwargs method, as keyword arguments. #893

 - [x] Closes #893 #523 
 - [x] I am familiar with the [contributing guidelines](https://pvlib-python.readthedocs.io/en/latest/contributing.html)
 - [ ] Tests added
 - [ ] Updates entries to [`docs/sphinx/source/api.rst`](https://github.com/pvlib/pvlib-python/blob/master/docs/sphinx/source/api.rst) for API changes.
 - [ ] Adds description and name entries in the appropriate "what's new" file in [`docs/sphinx/source/whatsnew`](https://github.com/pvlib/pvlib-python/tree/master/docs/sphinx/source/whatsnew) for all changes. Includes link to the GitHub Issue with `` :issue:`num` `` or this Pull Request with `` :pull:`num` ``. Includes contributor name and/or GitHub username (link with `` :ghuser:`user` ``).
 - [ ] New code is fully documented. Includes [numpydoc](https://numpydoc.readthedocs.io/en/latest/format.html) compliant docstrings, examples, and comments where necessary.
 - [x] Pull request is nearly complete and ready for detailed review.
 - [x] Maintainer: Appropriate GitHub Labels and Milestone are assigned to the Pull Request and linked Issue.

### CODE REVIEW

**Comment by Ahanmr** [comment]
@cwhanse  How do I resolve the codecov error here?

**Comment by Ahanmr** [comment]
Since, the code successfully passes all checks except these two codecov tests.

**Comment by cwhanse** [comment]
> @cwhanse  How do I resolve the codecov error here?

Don't worry about it.  codecov isn't hitting the 95% target due to `raise` statements, and a few untested lines that are outside this PR.

**Comment by cwhanse** [comment]
@Ahanmr just pinging you about this PR - can you add a line to the whatsnew v0.7.2 file, and add yourself to the Contributors section?  Or if circumstances prevent you, I can do it for you.

**Comment by Ahanmr** [comment]
Yes @cwhanse ! I'll do this right away! Thank you!

**Pull request merged**
