### PR TITLE
Add "ape" to variables_style_rules.csv

### PR DESCRIPTION
**Pull request by RDaxini**
- [X] Relates to #2135 and #2140 
 - [X] I am familiar with the [contributing guidelines](https://pvlib-python.readthedocs.io/en/latest/contributing.html)
 - [X] New code is fully documented. Includes [numpydoc](https://numpydoc.readthedocs.io/en/latest/format.html) compliant docstrings, examples, and comments where necessary.
 - [X] Pull request is nearly complete and ready for detailed review.
 - [x] Maintainer: Appropriate GitHub Labels (including `remote-data`) and Milestone are assigned to the Pull Request and linked Issue.

Adds "ape" to the user guide variables and symbols page to complement the new function created in PR #2140 , which itself was created to close Issue #2135

### CODE REVIEW

**Review by cwhanse — APPROVED** [review]

**Review by AdamRJensen — DISMISSED** [review]
I must admit that `ape` stands out as the only acronym from the variable list that I wouldn't intuitively know what was prior to these last PRs.

**Comment by RDaxini** [comment]
> _Edit: given that `ape` is only used once in the entire documentation (in the output of the `average_photon_energy` function then I don't think it warrants being added here (yet). I think we should use `average_photon_energy` to the extent that we can, as `ape` does not see universal usage in the community or widespread usage in pvlib like say GHI, DNI, etc._

It depends what you mean by universal usage. The initialism "ape" for "average photon energy" might not be known by everyone, but this is to be expected since not everyone works with every metric. I think the spectrum in particular is also a less common area of study. As for instances where the average photon energy is used, I am certain that this initialism is used universally in the PV performance modelling community. Happy to be corrected if you have found exceptions to this.

That's my understanding of the general subject, but as to whether an entry into the pvlib user guide is necessary I will leave that up to the more experienced pvlib maintainers --- @AdamRJensen @cwhanse (or another vote) if there is consensus to hold off on this addition then I'm happy to close this PR. At the moment it's 1 approval 1 non-approval.

**Comment by cwhanse** [comment]
@pvlib/pvlib-maintainer any objection to merging?

**Review by adriesse — APPROVED** [review]
I see no harm done here.

**Pull request merged**
