### PR TITLE
Remove warnings in docs

### PR DESCRIPTION
**Pull request by echedey-ls**
- ~[ ] Closes #xxxx~
 - [x] I am familiar with the [contributing guidelines](https://pvlib-python.readthedocs.io/en/latest/contributing.html)
 - ~[ ] Tests added~
 - ~[ ] Updates entries in [`docs/sphinx/source/reference`](https://github.com/pvlib/pvlib-python/blob/main/docs/sphinx/source/reference) for API changes.~
 - ~[ ] Adds description and name entries in the appropriate "what's new" file in [`docs/sphinx/source/whatsnew`](https://github.com/pvlib/pvlib-python/tree/main/docs/sphinx/source/whatsnew) for all changes. Includes link to the GitHub Issue with `` :issue:`num` `` or this Pull Request with `` :pull:`num` ``. Includes contributor name and/or GitHub username (link with `` :ghuser:`user` ``).~
 - ~[ ] New code is fully documented. Includes [numpydoc](https://numpydoc.readthedocs.io/en/latest/format.html) compliant docstrings, examples, and comments where necessary.~
 - [x] Pull request is nearly complete and ready for detailed review.
 - [x] Maintainer: Appropriate GitHub Labels (including `remote-data`) and Milestone are assigned to the Pull Request and linked Issue.

I forgot to check the built docs log ☠️ 
Second commit has the log output of that equation problem

- Fixes
  -
  - Broken hyperlinks
  - Warning of duplicated equation label
  - Version switcher position text, with #2112 it's position got changed. Credit of @RDaxini for spotting it

### CODE REVIEW

**Comment by echedey-ls** [comment]
@IoannisSifnaios @RDaxini this documentation log is almost clean. Double-checking exercise left to the reader 🙃

**Review by RDaxini — APPROVED** [review]
LGTM, I can see that the links are working now and you've removed the additional label.

Possible additional revision while we're at it though... in the [Plot Irradiance Non-uniformity Loss](https://pvlib-python--2128.org.readthedocs.build/en/2128/gallery/bifacial/plot_irradiance_nonuniformity_loss.html?highlight=plot%20irradiance%20nonuniformity#) example, can we separate the first code block (the one importing packages) more distinctly from the references section? I just think it would look neater. I know anyone would know that's not references, but it kinda looks like it is part of that section. Perhaps shift it into the problem description section? It could still be kept as a separate code block from the code block already in that section though. Just an idea.

**Comment by echedey-ls** [comment]
> can we separate the first code block (the one importing packages)

You've got a point right there @RDaxini , thx!

**Review by kandersolar — APPROVED** [review]
LGTM, thanks @echedey-ls!

**Pull request merged**
