### PR TITLE
[DOC] Added synk.io badge

### LINKED ISSUE #1543: add snyk open source advisor badge
**Is your feature request related to a problem? Please describe.**
Do people wonder if pvlib and open source are safe? Snyk is one of several online solutions that offer security analysis. According to them pvlib is looking pretty good

[pvlib](https://snyk.io/advisor/python/pvlib)

**Describe the solution you'd like**
Add Snyk OS advisor in the badge matrix on the readme.

[pvlib](https://snyk.io/advisor/python/pvlib)

**Describe alternatives you've considered**
* https://deps.dev/pypi/pvlib is an OpenSSF scorecard. pvlib scores 6/10
* IDK?

**Additional context**
This is how you add the markdown and it should take you to the snyk OS advisor page:

[pvlib](https://snyk.io/advisor/python/pvlib)

### PR DESCRIPTION
**Pull request by ooprathamm**
- [x] Closes #1543 
 - [ ] I am familiar with the [contributing guidelines](https://pvlib-python.readthedocs.io/en/latest/contributing.html)
 - [ ] Tests added
 - [ ] Updates entries in [`docs/sphinx/source/reference`](https://github.com/pvlib/pvlib-python/blob/main/docs/sphinx/source/reference) for API changes.
 - [ ] Adds description and name entries in the appropriate "what's new" file in [`docs/sphinx/source/whatsnew`](https://github.com/pvlib/pvlib-python/tree/main/docs/sphinx/source/whatsnew) for all changes. Includes link to the GitHub Issue with `` :issue:`num` `` or this Pull Request with `` :pull:`num` ``. Includes contributor name and/or GitHub username (link with `` :ghuser:`user` ``).
 - [ ] New code is fully documented. Includes [numpydoc](https://numpydoc.readthedocs.io/en/latest/format.html) compliant docstrings, examples, and comments where necessary.
 - [ ] Pull request is nearly complete and ready for detailed review.
 - [ ] Maintainer: Appropriate GitHub Labels (including `remote-data`) and Milestone are assigned to the Pull Request and linked Issue.

### CODE REVIEW

**Comment by mikofski** [comment]
Thanks @ooprathamm ! Do you think Snyk should be separated with a row heading like "Security"? The badge itself doesn't say anything so it's hard to know what it's measuring?
image

**Comment by mikofski** [comment]
also looks like LGTM badges may be going away soon according to #1550. @AdamRJensen do you know what the status is on GH code scanning? Any opinions on where Snyk.io security badge should go?

**Comment by AdamRJensen** [comment]
I believe the LGTM badges should just be removed - it would be nice if you could do that in this PR.

If we decide to add GitHub Code Scanning badges, I vote that we do that later in the same PR that adds Code Scanning.

**Comment by mikofski** [comment]
@AdamRJensen do you think "Code Quality" is an appropriate row heading for Snyk? @ooprathamm I still think changing the row heading will make it more understandable. If LGTM is going away, then maybe we can repurpose this row to "Snyk Advisor"

**Comment by ooprathamm** [comment]
@mikofski If we are adding more checks like Open Source Insights as sited by you, then repurposing it to Sync.io won't be a good idea.

**Comment by AdamRJensen** [comment]
> Code Quality"

"Security" or "Snyk advisor" seems more appropriate to me.

**Comment by mikofski** [comment]
@AdamRJensen did you see Kevin's comment in #1543 ? I am leery of advancing this PR if it's not considered valuable. I think there's some concern over the rigor/credibility of Snyk's advisory? Do you or others have any input? Maybe continue the discussin in the issue?

**Comment by mikofski** [comment]
tabling this PR for now, see discussion on related issue. Thanks @ooprathamm  for your effort. Could you open a new PR to remove the LGTM row if still interested. Thanks!

**Pull request closed without merging**
