### PR TITLE
centrally defined abbreviations for units with special formatting

### LINKED ISSUE #2205: Standarizing pvlib typesetting of units - standarization for common variables?
**Is your feature request related to a problem? Please describe.**
As of now, units in the whole documentation are written with the own developer style, and there is no place that suggests which units should be used in any case.

Current typesetting includes:
1. LaTeX like markup, e.g., `W/m^2` (in https://pvlib-python.readthedocs.io/en/latest/reference/generated/pvlib.irradiance.dirint.html)
2. Mathjax rendering using the Sphinx math role, e.g., ```:math:`W/m^2` ``` (in https://pvlib-python.readthedocs.io/en/latest/reference/generated/pvlib.irradiance.get_ground_diffuse.html)
3. Unicode plaintext using superscript numbers, optionally superscript dash to avoid the slash; e.g., `W/m²` or `Wm⁻²`, `Wm⁻²nm⁻¹` (in https://pvlib-python.readthedocs.io/en/latest/reference/generated/pvlib.spectrum.spectrl2.html)

(I can't find some comment in a review of my PRs or so talking about alternatives and views with @kandersolar and @AdamRJensen )

On one side new/current contributors don't have a clear guideline on what to do when writing units. Both in API docs and examples. On the other side, switching between docs and seeing different ways of writing it may confuse inexperienced users.
And it looks a bit crappy that each dev sticks to it's own style.

Now the topic moves to [Variables and Symbols](https://pvlib-python.readthedocs.io/en/latest/user_guide/variables_style_rules.html#variables-and-symbols). I think that units that make a convention have a spot there, and can be used to template units out of there too. E.g.:

- eta_inv | inverter efficiency <> in % or in [0,1]? (and the same goes for many of them)

Normalizing what units shall be used for each variable guarantees pvlib is a toolbox of tools that fit together.

**Describe the solution you'd like**
I personally think an homogeneous typesetting is beneficial for the project. And if I had to choose, I don't like cluttering the view with extra characters like `^2` when `²` exists, so I'm +1 for homogenizing and changing to option 3. I somewhat agree with @RDaxini on using superscript minus sign `⁻`.

**Describe alternatives you've considered**
1. Proposing and pushing and agenda to adopt a complete PVlib Enhancement Proposals (PVEP) system the same way Python has PEPs, Numpy NEPs and Matplotlib MEPs, then convincing everyone that option 3 is the right path, because it is.
1. Not doing anything 🙄 

**Additional context**
When a decision on this is agreed, this would make for a good set of Easy and How-To-Contribute series of PRs for newcomers, conferences and workshops.

### PR DESCRIPTION
**Pull request by RDaxini**
- [X] Closes #2205 
 - [X] I am familiar with the [contributing guidelines](https://pvlib-python.readthedocs.io/en/latest/contributing.html)
 - [ ] Tests added
 - [ ] Updates entries in [`docs/sphinx/source/reference`](https://github.com/pvlib/pvlib-python/blob/main/docs/sphinx/source/reference) for API changes.
 - [ ] Adds description and name entries in the appropriate "what's new" file in [`docs/sphinx/source/whatsnew`](https://github.com/pvlib/pvlib-python/tree/main/docs/sphinx/source/whatsnew) for all changes. Includes link to the GitHub Issue with `` :issue:`num` `` or this Pull Request with `` :pull:`num` ``. Includes contributor name and/or GitHub username (link with `` :ghuser:`user` ``).
 - [x] New code is fully documented. Includes [numpydoc](https://numpydoc.readthedocs.io/en/latest/format.html) compliant docstrings, examples, and comments where necessary.
 - [x] Pull request is nearly complete and ready for detailed review.
 - [x] Maintainer: Appropriate GitHub Labels (including `remote-data`) and Milestone are assigned to the Pull Request and linked Issue.
 
 **Additional context**
 Suggested replacements:
|wm2| -> Wm⁻²
|wm2nm1| -> Wm⁻²nm⁻¹
|degc| -> °C
|deg| -> °
_Note: click shift+\ to type |_

Includes some common units but the current list just gives an idea of what is possible. Feel free to recommend inclusions/exclusions/modifications. [See here](https://pvlib-python--2209.org.readthedocs.build/en/2209/reference/generated/pvlib.irradiance.get_total_irradiance.html) for example usage (`solar_azimuth`, `dhi`, `dni_extra`)

I also tried:
|^-1| -> ⁻¹
|^-2| -> ⁻² 
to create some individual superscripts for more flexible applications (e.g. in [atmosphere.pres2alt](https://pvlib-python.readthedocs.io/en/stable/reference/generated/pvlib.atmosphere.pres2alt.html#) we have ms⁻²) but this did not render correctly in the docs. Is this a problem / does anyone have a suggestion to resolve this?

ps ignore the branch name, nothing to do with latex

### CODE REVIEW

**Comment by RDaxini** [comment]
@echedey-ls do you have any ideas about this?
None of these attempts worked (apart from using :math:, but no-one wants that) 😂

I was not confident about the latex commands since the docs are html, not pdf, but I thought creating the new roles would work, or at the very least just typing out the superscript manually with `<sup> </sup>` would work,,, but no

**Comment by echedey-ls** [comment]
I haven't had a look at your commits, but the best thing that comes to my mind is the following:
- Add a prolog `rst_prolog` in `conf.py` with a substitution pattern
  - https://www.sphinx-doc.org/en/master/usage/restructuredtext/basics.html#substitutions
  - https://docutils.sourceforge.io/docs/ref/rst/restructuredtext.html#substitution-definitions
  - https://docutils.sourceforge.io/docs/ref/rst/directives.html#replacement-text
- Substitutions could be:
  - `.. |W/m^2| replace:: [Wm⁻²]`
  - and the same for all common units pvlib uses; be aware there are a lot of combinations you could make use of, in this case I put brackets so in a docstring parameter we avoid using pipes and brackets all together.
  - this is both readable through help and RTD
  - in a paragraph, you will do:
    ```
    poa_global: plane-of-array global irradiance. |W/m^2|.
    ```
    which should render as:
    `poa_global: plane-of-array global irradiance. [W/m^2].`

**Comment by echedey-ls** [comment]
I think this PR is now a nice example of how this would look like: https://pvlib-python--2209.org.readthedocs.build/en/2209/reference/generated/pvlib.irradiance.get_total_irradiance.html

Params `dhi` and `dni_extra`.

**Comment by kandersolar** [comment]
> How did conf.py pass the Flake8 Linter test in the past?

The flake8 job is configured to only check lines that are near other lines that have changed in the PR, and we don't change `conf.py` very often :)

> Should I resolve these linting issues or leave them?

My two cents: reviewing PRs is already hard enough without extra "clutter" of unrelated formatting changes.  Best to do them in a separate PR where improved formatting is the objective.

**Comment by RDaxini** [comment]
Closed, see [comment](https://github.com/pvlib/pvlib-python/issues/2205#issuecomment-2384159039)

**Pull request closed without merging**
