### PR TITLE
Use pandas wrapper functions for the test suite

### LINKED ISSUE #1018: pandas.testing.assert_series_equal precision defaults changed in pandas 1.1.0
Pandas 1.1.0 changed the default precision tolerances in the `assert_series_equal` and similar functions: https://github.com/pandas-dev/pandas/pull/30562.  This is causing test failures on the Azure checks that use the most recent pandas version, e.g.:  https://dev.azure.com/solararbiter/pvlib%20python/_build/results?buildId=3877&view=logs&j=ee50eb0a-7467-5494-0f35-e3b863355bb0&t=2efe8f58-8c60-5d45-8189-b00aa6aac1e4&l=209

I think maybe the best way to fix this is to wrap the pandas functions with our own with some version-checking logic.  Or we could rework all the failing tests to use more precise values, or bump the minimum pandas version to 1.1.0, neither of which seems like a good option to me.

### PR DESCRIPTION
**Pull request by kanderso-nrel**
- [x] Closes #1018
 - [x] I am familiar with the [contributing guidelines](https://pvlib-python.readthedocs.io/en/latest/contributing.html)
 - ~Tests added~
 - ~Updates entries to [`docs/sphinx/source/api.rst`](https://github.com/pvlib/pvlib-python/blob/master/docs/sphinx/source/api.rst) for API changes.~
 - ~Adds description and name entries in the appropriate "what's new" file in [`docs/sphinx/source/whatsnew`](https://github.com/pvlib/pvlib-python/tree/master/docs/sphinx/source/whatsnew) for all changes. Includes link to the GitHub Issue with `` :issue:`num` `` or this Pull Request with `` :pull:`num` ``. Includes contributor name and/or GitHub username (link with `` :ghuser:`user` ``).~
 - ~New code is fully documented. Includes [numpydoc](https://numpydoc.readthedocs.io/en/latest/format.html) compliant docstrings, examples, and comments where necessary.~
 - [x] Pull request is nearly complete and ready for detailed review.
 - [x] Maintainer: Appropriate GitHub Labels and Milestone are assigned to the Pull Request and linked Issue.

Seeing what Azure thinks of the changes.

Possible to-do items:
- [ ] Add tests for the new assert functions somehow?
- [x] Whatsnew?

### CODE REVIEW

**Comment by kanderso-nrel** [comment]
Tests pass.  Codecov is low because it's only getting results from one branch of the `if parse_version(pd.__version__) >= parse_version('1.1.0')` switch, so it sees the other as uncovered.

**Comment by kanderso-nrel** [comment]
A mocked version test is interesting but I'm not sure how it would work.  Mock the other version and test that it raises a TypeError for the unexpected keyword argument?

**Comment by wholmgren** [comment]
I'd patch and set the appropriate return_value for both conditions regardless of the true pandas version. The test would assert that the correct kwargs are included/excluded from the function.

**Comment by kanderso-nrel** [comment]
Thanks, that got me on the right track.  I've added a test, but wouldn't be surprised if it could be made simpler.

**Comment by wholmgren** [comment]
thanks @kanderso-nrel!

**Pull request merged**
