### PR TITLE
fix built in ephemeris

### LINKED ISSUE #40: solarposition.ephemeris
returns solar azimuth angle in wrong definition with zero = south. But irradiance.aoi needs as input panel azimuth angles from north.

This function is discouraged anyway, so may it be better to remove it from the library?

### PR DESCRIPTION
**Pull request by wholmgren**
I fixed the ephemeris function (I think). The key changes are

* replace the local and utc hour calculation code as described in #40.
* multiply longitude by -1 as described in a comment but not actually done in the code.

Here's some sample output.

Tucson summer elevation
tucson summer

Berlin no DST (March 28, 2015)
berlin no dst

Berlin DST (March 30, 2015)
berlin dst

Berlin summer elevation and azimuth.
berlin summer az
berlin summer elev

Closes #40. cc @uvchik

### CODE REVIEW

**Comment by wholmgren** [comment]
Here's a closer look at the refraction correction. The difference between pyephem and ephemeris is negligible above the horizon.

apparent diff

**Comment by wholmgren** [comment]
Rebased to retest on the many pandas versions. I think this can be merged now or with minor review.

**Comment by uvchik** [comment]
Good work. Thank you.

**Comment by mariusko** [comment]
We are currently working on a problem related to the ephemeris calculations of the sun elevation. The problem is that the time at which ephemeris calculates the sunrise ( above 0°) is sometimes later than the first radiation data derived from our climate model.

We think the problem is related to different methods of calculating the exact time of the sunrise. 
So I would like to ask you if you happen to know about further documentation/explanation of how ephemeris calculates its outputs.

Thanks in advance

**Comment by wholmgren** [comment]
@mariusko I suggest comparing both ephemeris and your climate model to actuals using e.g. google for a couple of locations on a couple of days. My guess is that your climate model does not use the correct equation of time. It was only in the last year or so that the WRF weather model started using the correct equation of time, but this is even less important for climate modeling than it is for weather modeling.

**Comment by bmu** [comment]
@mariusko : The fact that there is irradiance before the sun is above the horizon, may be a hint, that you have a good climate model ;-) You often measure positive irradiance before the sun is above the horizon, due to scattering in the atmosphere and atmospheric refraction.  
Maybe this is one reason.

**Pull request merged**
