### PR TITLE
Add project urls to setup.py for pypi page

### LINKED ISSUE #1108: urls for pypi page
copy https://github.com/NREL/rdtools/pull/248

### PR DESCRIPTION
**Pull request by AzizCode92**
- [x] Closes #1108
 - [x] I am familiar with the [contributing guidelines](https://pvlib-python.readthedocs.io/en/latest/contributing.html)
 - [ ] Tests added
 - [ ] Updates entries to [`docs/sphinx/source/api.rst`](https://github.com/pvlib/pvlib-python/blob/master/docs/sphinx/source/api.rst) for API changes.
 - [x] Adds description and name entries in the appropriate "what's new" file in [`docs/sphinx/source/whatsnew`](https://github.com/pvlib/pvlib-python/tree/master/docs/sphinx/source/whatsnew) for all changes. Includes link to the GitHub Issue with `` :issue:`num` `` or this Pull Request with `` :pull:`num` ``. Includes contributor name and/or GitHub username (link with `` :ghuser:`user` ``).
 - [ ] New code is fully documented. Includes [numpydoc](https://numpydoc.readthedocs.io/en/latest/format.html) compliant docstrings, examples, and comments where necessary.
 - [x] Pull request is nearly complete and ready for detailed review.
 - [x] Maintainer: Appropriate GitHub Labels and Milestone are assigned to the Pull Request and linked Issue.

### CODE REVIEW

**Comment by kanderso-nrel** [comment]
Hi @AzizCode92, thanks for the PR!  If you're comfortable with it, you can add yourself to the `Contributors` section in `docs/sphinx/source/whatsnew/v0.8.1.rst`.

**Comment by AzizCode92** [comment]
@kanderso-nrel done, the one thing that is failing now is the code coverage. Is there something else I need to modify to make the pipeline green again?

**Comment by kanderso-nrel** [comment]
@AzizCode92 I think we can ignore the coverage failure for this PR. 

@pvlib/pvlib-maintainer - should we make sure this works on test.pypi.org?

**Comment by wholmgren** [comment]
thanks @AzizCode92!

@kanderso-nrel we could, but it's easiest to tag a release candidate, let the automated machinery do its thing, and see if it works on the main pypi.

**Pull request merged**
