### PR TITLE
fix broken seealso docstring entries

### LINKED ISSUE #941: DOC: some API reference pages have broken "see also" links
The see-also links on many of the API reference pages don't work because the names aren't in a format sphinx understands.  The majority are because the "module.function" path is only partially specified (e.g. `iam.martin_ruiz`).  I think it only works if you use the bare function name if it's in the same module, or you can specify the full path (including the leading `pvlib.`).  However there are a few misspellings like `equation_of_time_Spencer71()` and out of date locations like `pvlib.tmy.readtmy3()`. 

```
                                        function                       see-also name
0                        pvlib.location.Location                   pvsystem.PVSystem
1   pvlib.solarposition.equation_of_time_pvcdrom        equation_of_time_Spencer71()
2                 pvlib.solarposition.hour_angle        equation_of_time_Spencer71()
3                            pvlib.clearsky.bird  pvlib.atmosphere.relativeairmass()
4                             pvlib.iam.physical                   iam.martin_ruiz()
5                             pvlib.iam.physical                        iam.ashrae()
6                             pvlib.iam.physical                        iam.interp()
7                             pvlib.iam.physical                          iam.sapm()
8                               pvlib.iam.ashrae                      iam.physical()
9                               pvlib.iam.ashrae                   iam.martin_ruiz()
10                              pvlib.iam.ashrae                        iam.interp()
11                         pvlib.iam.martin_ruiz           iam.martin_ruiz_diffuse()
12                         pvlib.iam.martin_ruiz                      iam.physical()
13                         pvlib.iam.martin_ruiz                        iam.ashrae()
14                         pvlib.iam.martin_ruiz                        iam.interp()
15                         pvlib.iam.martin_ruiz                          iam.sapm()
16                 pvlib.iam.martin_ruiz_diffuse                   iam.martin_ruiz()
17                 pvlib.iam.martin_ruiz_diffuse                      iam.physical()
18                 pvlib.iam.martin_ruiz_diffuse                        iam.ashrae()
19                 pvlib.iam.martin_ruiz_diffuse                        iam.interp()
20                 pvlib.iam.martin_ruiz_diffuse                          iam.sapm()
21                                pvlib.iam.sapm                      iam.physical()
22                                pvlib.iam.sapm                        iam.ashrae()
23                                pvlib.iam.sapm                   iam.martin_ruiz()
24                                pvlib.iam.sapm                        iam.interp()
25                              pvlib.iam.interp                      iam.physical()
26                              pvlib.iam.interp                        iam.ashrae()
27                              pvlib.iam.interp                   iam.martin_ruiz()
28                              pvlib.iam.interp                          iam.sapm()
29                           pvlib.pvsystem.sapm             temperature.sapm_cell()
30                           pvlib.pvsystem.sapm           temperature.sapm_module()
31                  pvlib.pvsystem.sapm_aoi_loss                      iam.physical()
32                  pvlib.pvsystem.sapm_aoi_loss                        iam.ashrae()
33                  pvlib.pvsystem.sapm_aoi_loss                   iam.martin_ruiz()
34                  pvlib.pvsystem.sapm_aoi_loss                        iam.interp()
35                      pvlib.pvsystem.systemdef                pvlib.tmy.readtmy3()
36                      pvlib.pvsystem.systemdef                pvlib.tmy.readtmy2()
37                       pvlib.location.Location                   pvsystem.PVSystem
```

That list was generated with this quick and dirty script that scans through a local docs build and finds the broken see-also links:

<details>
  <summary>Click to expand</summary>

```python
# run from the pvlib-python/docs/sphinx/build/html directory
import bs4
import pandas as pd

#%% get a list of all the functions documented in the API Reference page

listing_file = 'api.html'

with open(listing_file, 'r') as f:
    html = f.read()

soup = bs4.BeautifulSoup(html)

listing = soup.find(id='api-reference')
link_elements = listing.find_all('a', class_='reference internal')
link_urls = [a.attrs['href'].split("#")[0] for a in link_elements]

#%% For each function page, check its "see also" entries for a link

missing_links = []

for link_url in link_urls:
    print(link_url)
    with open(link_url, 'r') as f:
        html = f.read()

    soup = bs4.BeautifulSoup(html)
    seealso_divs = soup.find_all('div', class_='seealso')
    for div in seealso_divs:
        entries = div.find_all('code', class_='xref')
        for entry in entries:
            # if sphinx didn't recognize the name, it doesn't wrap the "code"
            # element in an <a href=...> tag, so the code's parent won't have
            # that attribute
            if 'href' not in entry.parent.attrs:
                info = {
                    'page': link_url,
                    'function': link_url.split("/")[1].rsplit(".",1)[0],
                    'see-also name': entry.text
                }
                missing_links.append(info)

#%%

df = pd.DataFrame(missing_links)
print(df[['function', 'see-also name']])
```
</details>

### PR DESCRIPTION
**Pull request by kanderso-nrel**
- [x] Closes #941
 - [x] I am familiar with the [contributing guidelines](https://pvlib-python.readthedocs.io/en/latest/contributing.html)
 - [x] Pull request is nearly complete and ready for detailed review.
 - [x] Maintainer: Appropriate GitHub Labels and Milestone are assigned to the Pull Request and linked Issue.

Just a simple sphinx docs PR.

### CODE REVIEW

**Comment by wholmgren** [comment]
If it works, I prefer bare function names when the function is in the same module, but what do you think?

**Comment by kanderso-nrel** [comment]
I don't feel strongly one way or the other.  It is a little clunky to have a bunch of `pvlib.submodule.` everywhere, but in some cases it might help with clarity, for instance in https://pvlib-python--946.org.readthedocs.build/en/946/generated/pvlib.iam.physical.html, `martin_ruiz(), ashrae(), interp(), sapm()` would lose the context that `sapm()` is the IAM part of the SAPM.  

If you prefer bare function names, that's fine and I'll update this PR tonight.

**Comment by cwhanse** [comment]
> sapm() would lose the context that sapm() is the IAM part of the SAPM.

Because of the SAPM group of functions, I'd prefer full paths. It's clunky but explicit.

**Comment by CameronTStark** [comment]
Thanks @kanderso-nrel!

**Pull request merged**
