### PR TITLE
Remove orientation_strategy from Modelchain

### LINKED ISSUE #1028: remove ModelChain.orientation_strategy
I don't like that `ModelChain(system, location, orientation_strategy='flat`|`south_at_latitude_tilt`) modifies the `system` object. It's not something we do anywhere else in pvlib. `orientation_strategy` only supports flat and south_at_latitude_tilt, neither of which are commonly used in the real world in 2020. 

I think we should remove it, maybe even without deprecation, in 0.8.

I'm ok with keeping the `modelchain.get_orientation` function for now.

### PR DESCRIPTION
**Pull request by kanderso-nrel**
- [x] Closes #1028
 - [x] I am familiar with the [contributing guidelines](https://pvlib-python.readthedocs.io/en/latest/contributing.html)
 - [x] Tests added
 - [x] Updates entries to [`docs/sphinx/source/api.rst`](https://github.com/pvlib/pvlib-python/blob/master/docs/sphinx/source/api.rst) for API changes.
 - [x] Adds description and name entries in the appropriate "what's new" file in [`docs/sphinx/source/whatsnew`](https://github.com/pvlib/pvlib-python/tree/master/docs/sphinx/source/whatsnew) for all changes. Includes link to the GitHub Issue with `` :issue:`num` `` or this Pull Request with `` :pull:`num` ``. Includes contributor name and/or GitHub username (link with `` :ghuser:`user` ``).
 - [x] New code is fully documented. Includes [numpydoc](https://numpydoc.readthedocs.io/en/latest/format.html) compliant docstrings, examples, and comments where necessary.
 - [x] Pull request is nearly complete and ready for detailed review.
 - [x] Maintainer: Appropriate GitHub Labels and Milestone are assigned to the Pull Request and linked Issue.

Follow up to https://github.com/pvlib/pvlib-python/pull/1176#discussion_r584349918.  I went the lazy route and removed it without deprecation, but I am willing to not be lazy if a deprecation period seems like a good idea here.

### CODE REVIEW

**Review by wholmgren — APPROVED** [review]
Thanks @kanderso-nrel. 

After some more thought, I'm leaning towards deprecating the parameter. The primary reason is that the default used to be `south_at_latitude_tilt` and users had to specify `orientation_stragety=None` to prevent `ModelChain` from modifying their systems (https://github.com/pvlib/pvlib-python/issues/290). As a long result of that bad API decision years ago, I still have modern code that sets the parameter to None. I'm guessing that at least a few other users might be in the same position.

FWIW, I briefly searched github and google for pvlib and south_at_latitude_tilt. I found one article in energies that used the parameter. I did not find any maintained code that uses it.

**Comment by wholmgren** [comment]
Forgot to add... On the other hand, the changes to the object layer make the deprecation non-trivial, so unless you know a good way to do it then it's fine with me if we skip it. We're not a 1.0+ project for this reason.

**Review by cwhanse — APPROVED** [review]
LGTM. I'm ok removing without deprecation, in this case.

**Comment by wholmgren** [comment]
Let's go ahead then. Thanks @kanderso-nrel

**Pull request merged**
