### PR TITLE
[DOC] Removes LGTM Badges from README.md

### PR DESCRIPTION
**Pull request by ooprathamm**
- [ ] Closes #xxxx
 - [ ] I am familiar with the [contributing guidelines](https://pvlib-python.readthedocs.io/en/latest/contributing.html)
 - [ ] Tests added
 - [ ] Updates entries in [`docs/sphinx/source/reference`](https://github.com/pvlib/pvlib-python/blob/main/docs/sphinx/source/reference) for API changes.
 - [x] Adds description and name entries in the appropriate "what's new" file in [`docs/sphinx/source/whatsnew`](https://github.com/pvlib/pvlib-python/tree/main/docs/sphinx/source/whatsnew) for all changes. Includes link to the GitHub Issue with `` :issue:`num` `` or this Pull Request with `` :pull:`num` ``. Includes contributor name and/or GitHub username (link with `` :ghuser:`user` ``).
 - [ ] New code is fully documented. Includes [numpydoc](https://numpydoc.readthedocs.io/en/latest/format.html) compliant docstrings, examples, and comments where necessary.
 - [ ] Pull request is nearly complete and ready for detailed review.
 - [x] Maintainer: Appropriate GitHub Labels (including `remote-data`) and Milestone are assigned to the Pull Request and linked Issue.

### CODE REVIEW

**Comment by ooprathamm** [comment]
@mikofski this PR removes code quality row (containing LGTM badges) as requested by you

**Comment by AdamRJensen** [comment]
Just wanted to note that this is related to GitHub retiring LGTM (see #1550 for further details).

**Review by AdamRJensen — APPROVED** [review]
LGTM, thanks @ooprathamm

**Comment by mikofski** [comment]
@ooprathamm a few more tasks to close this out:
- [ ] remove the line `exclude .lgtm.yml` in the file "MANIFEST.in"
- [ ] remove the file [`.lgtm.yml`](https://github.com/pvlib/pvlib-python/blob/main/.lgtm.yml).
- [ ] add a note under documentation and add your name to contributors in [what's new for 0.9.5](https://github.com/pvlib/pvlib-python/blob/main/docs/sphinx/source/whatsnew/v0.9.5.rst)

**Comment by ooprathamm** [comment]
@mikofski made the changes asked by you.

**Pull request merged**
