### PR TITLE
Fix iam.martin_ruiz equation in docs #1561

### LINKED ISSUE #1561: Equation in docstring of `pvlib.iam.martin_ruiz` does not match code
The docstring of `pvlib.iam.martin_ruiz` includes an equation defining the IAM:

https://github.com/pvlib/pvlib-python/blob/bdbaf4c238ce2b373d04af48193b14659662cef1/pvlib/iam.py#L230-L231

This equation does not match what is implemented in the code (specifically, `cos(aoi / a_r)` versus `cos(aoi) / a_r`):

https://github.com/pvlib/pvlib-python/blob/bdbaf4c238ce2b373d04af48193b14659662cef1/pvlib/iam.py#L269

The formatting in the original reference leaves room for doubt in which of these is correct.  IEC 61853-2 is unambiguous and specifies the version implemented in the code.

Correcting the docstring to match the code would be a good first PR for a new contributor!

---

The MATLAB version suffers from this same inconsistency: https://github.com/sandialabs/MATLAB_PV_LIB/blob/master/pvl_iam_martinruiz.m#L30

### PR DESCRIPTION
**Pull request by echedey-ls**
- [x] Closes #1561
 - [x] I am familiar with the [contributing guidelines](https://pvlib-python.readthedocs.io/en/latest/contributing.html)
 - [x] Adds description and name entries in the appropriate "what's new" file in [`docs/sphinx/source/whatsnew`](https://github.com/pvlib/pvlib-python/tree/master/docs/sphinx/source/whatsnew) for all changes. Includes link to the GitHub Issue with `` :issue:`num` `` or this Pull Request with `` :pull:`num` ``. Includes contributor name and/or GitHub username (link with `` :ghuser:`user` ``).
 - [x] Pull request is nearly complete and ready for detailed review.
 - [x] Maintainer: Appropriate GitHub Labels (including `remote-data`) and Milestone are assigned to the Pull Request and linked Issue.

Does not apply:
 - [ ] Tests added
 - [ ] Updates entries in [`docs/sphinx/source/reference`](https://github.com/pvlib/pvlib-python/blob/master/docs/sphinx/source/reference) for API changes.
 - [ ] New code is fully documented. Includes [numpydoc](https://numpydoc.readthedocs.io/en/latest/format.html) compliant docstrings, examples, and comments where necessary.

Description of issue in #1561 
First time contributor here! Looking forward to make bigger PRs in short, so all tips and criticism is welcomed.

### CODE REVIEW

**Comment by echedey-ls** [comment]
I've got a doubt in the optional use of ``~`` in `` :py:func:`~pvlib.iam.martin_ruiz` ``, I've seen some rST entries don't use it (I didn't) but all still works. Can you tell me if it's use is recommended or not?

**Review by kanderso-nrel — APPROVED** [review]
Looks great, thanks @echedey-ls!

> I've got a doubt in the optional use of ~ in :py:func:`~pvlib.iam.martin_ruiz`, I've seen some rST entries don't use it (I didn't) but all still works. Can you tell me if it's use is recommended or not?

The `~` controls whether the HTML link text will look like `pvlib.iam.martin_ruiz` or just `martin_ruiz`.  See https://www.sphinx-doc.org/en/master/usage/restructuredtext/domains.html#cross-referencing-syntax

Sometimes it makes sense to use `~` and sometimes it's better not to use it.  For this PR I would leave it the way it is now, but it's really just down to personal taste.

**Review by cwhanse — APPROVED** [review]

**Comment by echedey-ls** [comment]
Thanks for the reference @kanderso-nrel!

**Review by adriesse — APPROVED** [review]

**Comment by kanderso-nrel** [comment]
> Looking forward to make bigger PRs in short

Please let us know if we can help :) and thanks again for this PR!

**Pull request merged**
