### PR TITLE
TST: make iotools tests robust to API downtime

### LINKED ISSUE #917: iotools tests fail when unable to connect to remote API
**Describe the bug**
Failures of network dependent iotools tests due to failures of the API server receiving the request affect consistency and confidence in our CI test results. 

**To Reproduce**
* This is difficult to reproduce since API failures are sporadic.
* An example of our CI failure can be found [here](https://dev.azure.com/solararbiter/pvlib%20python/_build/results?buildId=2807&view=logs&j=06aebe0f-636a-5f93-19d5-0c37b58d55c8&t=0878738c-c430-5911-4cfd-99d3ab677436).

**Expected behavior**
There are two important functionalities that are desirable: 
1. Ideally, a failure due to API server failure would be repeated with the hope that communication can be established. 

1. In the event that communication cannot be established during the test, it should be conditionally skipped with a warning that the test wasn't properly run. 

**Additional context**

This was originally identified by @wholmgren in https://github.com/pvlib/pvlib-python/pull/897#issuecomment-590352000_

**Proposed solution**
Implement `@pytest.mark.flaky()`for all remote API dependent tests to reattempt if API is temporarily unreachable. This is already done for tests in `test_psm3.py` decorated with `@pytest.mark.remote_data`. 

~~I'm going to look for a pytest functionality to enable a conditional skip of the test in the event the API server is completely unavailable during the test duration. If you have a suggestion on how to accomplish this please let me know.~~
`@pytest.mark.skipif()` should work well for this application but the trick will be the implementation for each network dependent API.

### PR DESCRIPTION
**Pull request by CameronTStark**
- [x] Closes #917 
 - [x] I am familiar with the [contributing guidelines](https://pvlib-python.readthedocs.io/en/latest/contributing.html)
 - [x] Adds description and name entries in the appropriate "what's new" file in [`docs/sphinx/source/whatsnew`](https://github.com/pvlib/pvlib-python/tree/master/docs/sphinx/source/whatsnew) for all changes. Includes link to the GitHub Issue with `` :issue:`num` `` or this Pull Request with `` :pull:`num` ``. Includes contributor name and/or GitHub username (link with `` :ghuser:`user` ``).
 - [x] Pull request is nearly complete and ready for detailed review.
 - [x] Maintainer: Appropriate GitHub Labels and Milestone are assigned to the Pull Request and linked Issue.

This PR has implemented `@pytest.mark.flaky()` on all tests with `@pytest.mark.remote_data()`. This enables tests dependent on a network API to be retried after an initial failure. 

I am considering implementing `@pytest.mark.skipif()` decorators that are API specific and would test the availability of the API before running the tests. My concern is the complexity this might add to the testing suite while not necessarily completely fixing the issue. This approach still would not cover if the API becomes unavailable mid-test. Using `pytest.mock` is a potential alternative but would change the scope of the tests.

### CODE REVIEW

**Comment by CameronTStark** [comment]
This should be ready for merge now.

> Ok with me to merge. The repetitive specs of `reruns` and `reruns_delay` is not ideal, but cleaning that up could be more effort than its worth. 

Are you suggesting that the numbers be reduced? I could see making `reruns=3` and `reruns_delay=1` which would potentially cut 9 seconds from each test with a down server API. The effort you suggest would be ensuring that this could still endure multiple runs of the pvlib test suite. Not exciting but doable.

> I don't know if things like `partial` work with pytest markers.

You're referring to `functools.partial` right? Do you have a brief/small example of how would you try this?

**Comment by wholmgren** [comment]
The repetition I'm worried about is the configuration of the marker. In the current PR you need a find/replace all across multiple files if you want to change the arguments. Here are few examples of what I'm proposing:

option 1:

```python
# confest.py
reruns=5
reruns_delay=2

# test_*.py
from conftest import reruns, reruns_delay

@pytest.mark.flaky(reruns=reruns, reruns_delay=reruns_delay)
def test_something():
```

option 2:

```python
# conftest.py
# does this work with markers??? maybe functools.wraps???
flaky = partial(pytest.mark.flaky, reruns=reruns, reruns_delay=reruns_delay)

# test_*.py
from conftest import flaky

@flaky
def test_something():
```

option 3:

something smarter that takes advantage of built-in pytest capabilities (e.g. marker definitions, command line args).

But like I said, I'm fine with moving forward with the current approach if you're not up for digging on this (I know I'm not).

**Comment by mikofski** [comment]
>`# confest.py
reruns=5
reruns_delay=2`
>``
>`# test_*.py
from conftest import reruns, reruns_delay`

not: would you be okay with using all caps for constants?

**Comment by wholmgren** [comment]
Sure.

**Comment by CameronTStark** [comment]
I went with option 1. It's worth another code review before merging. Thanks!

**Comment by CameronTStark** [comment]
@wholmgren Do you mind if I merge my own PR?

**Comment by wholmgren** [comment]
@CameronTStark I don't mind once it's been approved.

**Pull request merged**
