### PR TITLE
Updated pd.date_range-API in plot_sunpath_diagrams.py

### PR DESCRIPTION
**Pull request by PhilBrk8**
freq='H' is depricated.
the parameter 'closed' was changed to 'inclusive'

 - [ ] Closes #xxxx
 - [ ] I am familiar with the [contributing guidelines](https://pvlib-python.readthedocs.io/en/latest/contributing.html)
 - [ ] Tests added
 - [ ] Updates entries in [`docs/sphinx/source/reference`](https://github.com/pvlib/pvlib-python/blob/main/docs/sphinx/source/reference) for API changes.
 - [ ] Adds description and name entries in the appropriate "what's new" file in [`docs/sphinx/source/whatsnew`](https://github.com/pvlib/pvlib-python/tree/main/docs/sphinx/source/whatsnew) for all changes. Includes link to the GitHub Issue with `` :issue:`num` `` or this Pull Request with `` :pull:`num` ``. Includes contributor name and/or GitHub username (link with `` :ghuser:`user` ``).
 - [ ] New code is fully documented. Includes [numpydoc](https://numpydoc.readthedocs.io/en/latest/format.html) compliant docstrings, examples, and comments where necessary.
 - [ ] Pull request is nearly complete and ready for detailed review.
 - [ ] Maintainer: Appropriate GitHub Labels (including `remote-data`) and Milestone are assigned to the Pull Request and linked Issue.

### CODE REVIEW

**Comment by kandersolar** [comment]
Right now our docs build uses python 3.7 (see https://github.com/pvlib/pvlib-python/blob/main/readthedocs.yml), which I'm guessing means it's also using an older pandas that doesn't support `inclusive`.  I'm in favor of upgrading our docs build configuration to a more modern environment.  @PhilBrk8 would you be up for trying that out in this PR?

**Comment by PhilBrk8** [comment]
> Right now our docs build uses python 3.7 (see https://github.com/pvlib/pvlib-python/blob/main/readthedocs.yml), which I'm guessing means it's also using an older pandas that doesn't support `inclusive`. I'm in favor of upgrading our docs build configuration to a more modern environment. @PhilBrk8 would you be up for trying that out in this PR?

Hi there,
sorry - life got in the way a bit...

I'm currently doing the Solar Energy Engineering Program of the TU Delft on edx.org and i'm in the last of 4 courses.
I set my self the goal to transfer the content and calculations into code in order to review and solidify my learnings.

To go even further and incorporate useful parts into the library while bringing it up to a more modern environment might be a great opportunity to advance my python skills to the next level and polish up my github profile in the meantime as well.

@kandersolar Would you also be in favor of this?

**Comment by kandersolar** [comment]
> @kandersolar Would you also be in favor of this?

Hard to say without hearing some specifics, but in general we enthusiastically welcome contributions!  Please open an issue describing any improvements you'd like to discuss :)

**Comment by kandersolar** [comment]
Closing this PR as it is now redundant after #2029.  Thanks @PhilBrk8, and hopefully we see more PRs from you in the future :)

**Pull request closed without merging**
