### PR TITLE
Tutorials

### LINKED ISSUE #30: Port Tutorials
Port of tutorials from sandia labs develop branch.

### PR DESCRIPTION
**Pull request by wholmgren**
~~Not yet ready to merge~~ 

Closes #30. This PR is just about making the notebooks work from beginning to end. I'm not going to spend much time making them read better.

I wrote a new [``tmy_to_power``](http://nbviewer.ipython.org/github/wholmgren/pvlib-python/blob/tutorials/docs/tutorials/tmy_to_power.ipynb) notebook that replaces ``Test_Scripts``. 

Here's a nbviewer [link to my fork](http://nbviewer.ipython.org/github/wholmgren/pvlib-python/tree/tutorials/docs/tutorials/).

To do:
- [x] ET_Irradiance (move into irradiance)
- [x] TS_2_Irradiance_functions reworked and renamed tmy_and_diffuse_irrad_models
- [x] atmosphere
- [x] irradiance
- [x] pvsystem
- [x] solarposition
- [x] tmy
- [x] tracking
- [x] add 0.2.1 whatsnew

Note that I've already rebased this on #77.

~~@NelisW sorry if this steps on your toes. Would be great to divide and conquer if you have the time to work on one or more of these before ~Monday.~~

### CODE REVIEW

**Comment by wholmgren** [comment]
@bmu @Calama-Consulting ready for your review. I will merge this if I don't hear from you by Monday.

**Comment by wholmgren** [comment]
@NelisW we'd still be thrilled to have your help improving the now-working tutorials or writing new ones.

**Comment by NelisW** [comment]
You know the feeling when you haven't visited friends for some time: your
embarrassment keeps you from calling :-(

I have been busy preparing for a PV system purchase for my home - about to
sign the contract. Quite an investment (1 kW PV water heating, 3kW PV for
the rest, 50V@200 Ah, 3kW IMEON inverter ) - lots of reading to do. Still
not fully decided on battery selection (gell or crystal)

Then also lure of Arduino / Raspberry Pi seduced me, with its detracting
promise of home automation.  Spent too much time there.

I will try an put in some time over the weekend.

not to worry about toe-stepping here, these toes have been out of
circulation too long ...

**Comment by bmu** [comment]
Should I merge it or are there problems with #78 and #79?

**Comment by bmu** [comment]
And I am not sure about #77. Seems that there are some conflicts with this pull request

**Comment by wholmgren** [comment]
@bmu I'm not sure what conflicts with #77 you're referring to. GitHub says that it can merge it automatically, so I think that means that everything is resolved.

What do you think we should do regarding this vs. #78? I would prefer to give @NelisW the credit for fixing the tutorials, but it will take some time get #78 into mergeable shape and this is ready to go now.

**Comment by bmu** [comment]
When I look at the diff in #77 for `whatsnew.rst` and `0.2.1.txt` seems like it is the same as the diff for this PR here (with some minor differences). Not sure, if this is resolved by your rebase.

**Comment by bmu** [comment]
I would prefer to merge this one in favour of #78. it's a pity with the doubled work.

**Comment by wholmgren** [comment]
Ok. I rebased on the new upstream master and fixed a typo in the 0.2.1 whats new.

**Pull request merged**
