### PR TITLE
use sphinx autosummary to make one doc page per function

### PR DESCRIPTION
**Pull request by wholmgren**
I'd like to change to API documentation format to have:
1. a separate summary page for each module
2. a separate detailed page for each function

see the new documentation here:

http://wholmgren-pvlib-python-new.readthedocs.org/en/doc-reorg2/modules.html

I think it's a lot easier to navigate this. Separate pages for each function also makes it reasonable to add example documentation for each function (like the matlab library already has) and was discussed in #62.

### CODE REVIEW

**Comment by alorenzo175** [comment]
Looks good except for the scrollbars on the tables. You might try some custom CSS so that the descriptions wrap like in https://github.com/qtile/qtile/commit/3eadbbf20adf975ed2ac502f59a6a7d854b7de91.

**Comment by alorenzo175** [comment]
Also, is there a way to have the +- boxes in the menu on the left for the autosummary items (like in Time and time zones)?

**Comment by wholmgren** [comment]
I applied that scroll bar patch. Nice find. The some of the tables look a little messy, but I prefer this to scrolling. 

I noticed earlier that the +/- symbols were not being created, but I couldn't figure out how to fix it.

autosummary is creating new pages for imported functions and classes. Not sure if this due to a sphinx bug or if I'm doing something wrong.

**Comment by wholmgren** [comment]
I forgot to add that I am fairly sure that the duplicated pages are due to a sphinx bug, and I'm waiting to merge this until they fix it.

**Comment by wholmgren** [comment]
closed in favor of #258.

**Pull request closed without merging**
