### PR TITLE
Updated plot_singlediode.py

### PR DESCRIPTION
**Pull request by RoyCoding8**
Changed the unit from C to degree C (°C)

 - [ ] Closes #xxxx
 - [ ] I am familiar with the [contributing guidelines](https://pvlib-python.readthedocs.io/en/latest/contributing.html)
 - [ ] Tests added
 - [ ] Updates entries in [`docs/sphinx/source/reference`](https://github.com/pvlib/pvlib-python/blob/master/docs/sphinx/source/reference) for API changes.
 - [ ] Adds description and name entries in the appropriate "what's new" file in [`docs/sphinx/source/whatsnew`](https://github.com/pvlib/pvlib-python/tree/master/docs/sphinx/source/whatsnew) for all changes. Includes link to the GitHub Issue with `` :issue:`num` `` or this Pull Request with `` :pull:`num` ``. Includes contributor name and/or GitHub username (link with `` :ghuser:`user` ``).
 - [ ] New code is fully documented. Includes [numpydoc](https://numpydoc.readthedocs.io/en/latest/format.html) compliant docstrings, examples, and comments where necessary.
 - [ ] Pull request is nearly complete and ready for detailed review.
 - [ ] Maintainer: Appropriate GitHub Labels and Milestone are assigned to the Pull Request and linked Issue.

### CODE REVIEW

**Comment by mikofski** [comment]
Hi, thanks for the contribution. I have a concern and a preference if you’ll indulge me.

I’m concerned about using non-ascii Unicode characters. My preference is for the LaTeX `\degree` symbol in matplotlib which avoids any encoding issues with using Unicode characters.

This:

```
plt.plot([1, 2, 3], [4, 9, 16])
plt.title(r'temp = $10 \degree C$')
```
works for me:
PNG image

**Comment by RoyCoding8** [comment]
Yeah, I think that'll be great :)

**Comment by RoyCoding8** [comment]
@mikofski Why does it show 8 failed checks? Do I have to make some more changes?

**Review by kanderso-nrel — COMMENTED** [review]
Thanks @RoyCoding8!  The check failures are all unrelated and can be ignored here.  Can you edit `docs/sphinx/source/whatsnew/v0.9.1.rst` to make a note under `Documentation` and add yourself to the contributors list?

**Comment by mikofski** [comment]
@kanderso-nrel  I can't see the rendered docs - they are failing. Any ideas why? @RoyCoding8  can you render the docs locally and copy/paste an image of the gallery example showing that the degree symbol is present? thanks!

**Comment by RoyCoding8** [comment]
@mikofski 
image
In my case it shows the presence of the degree symbol.

**Review by kanderso-nrel — APPROVED** [review]
Thanks @RoyCoding8!

**Pull request merged**
