### PR TITLE
Update outdated pvpmc.sandia.gov links in user guide

### LINKED ISSUE #1788: Outdated pvpmc.sandia.gov links in user guide.
**Describe the bug**
The pvpmc.sandia.gov website was updated, breaking these links in the pvlib docs: the PV_LIB Matlab help webpage [here](https://pvlib-python.readthedocs.io/en/stable/user_guide/comparison_pvlib_matlab.html), and PVPMC single diode page [here](https://pvlib-python.readthedocs.io/en/stable/gallery/iv-modeling/plot_singlediode.html#sphx-glr-gallery-iv-modeling-plot-singlediode-py).

### PR DESCRIPTION
**Pull request by reepoi**
- [x] Closes #1788 
 - [x] I am familiar with the [contributing guidelines](https://pvlib-python.readthedocs.io/en/latest/contributing.html)
 - ~[ ] Tests added~
 - ~[ ] Updates entries in [`docs/sphinx/source/reference`](https://github.com/pvlib/pvlib-python/blob/main/docs/sphinx/source/reference) for API changes.~
 - [ ] Adds description and name entries in the appropriate "what's new" file in [`docs/sphinx/source/whatsnew`](https://github.com/pvlib/pvlib-python/tree/main/docs/sphinx/source/whatsnew) for all changes. Includes link to the GitHub Issue with `` :issue:`num` `` or this Pull Request with `` :pull:`num` ``. Includes contributor name and/or GitHub username (link with `` :ghuser:`user` ``).
 - ~[ ] New code is fully documented. Includes [numpydoc](https://numpydoc.readthedocs.io/en/latest/format.html) compliant docstrings, examples, and comments where necessary.~
 - [x] Pull request is nearly complete and ready for detailed review.
 - [x] Maintainer: Appropriate GitHub Labels (including `remote-data`) and Milestone are assigned to the Pull Request and linked Issue.

Fixes the two links mentioned in the issue. I am unsure what link to use for the PV_LIB Matlab help webpage.

### CODE REVIEW

**Comment by cwhanse** [comment]
I would point the PVLib for Matlab link to https://github.com/sandialabs/MATLAB_PV_LIB

**Review by kandersolar — APPROVED** [review]
Thanks @reepoi!

As an aside, I recall there being some way to automatically detect broken links during the sphinx build.  Maybe something to consider for the future.

**Comment by echedey-ls** [comment]
> automatically detect broken links during the sphinx build

Mind if I open a PR for that? It's just a line of code.

**Comment by kandersolar** [comment]
@echedey-ls sure! My first thought is that it might significantly slow down the docs build, depending on what URLs it checks (e.g. every docstring DOI might take a long time...).  Depending on that, we could add it to the CI, or just run it manually every so often.   Probably broken links should be reported as warnings, not failures.

**Comment by echedey-ls** [comment]
@kandersolar I've been looking a bit more into it.

For internal references there is the config value [`nitpicky = True`](https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-nitpicky), that would be useful but does not solve the problem. I think it is good enough to add: I'll open a PR at least for that.

On the other hand, for external links [`linkchecker`](https://www.sphinx-doc.org/en/master/usage/builders/index.html#sphinx.builders.linkcheck.CheckExternalLinksBuilder) builder has to be run.
I'm looking for a way to integrate it. From [this comment](https://github.com/matplotlib/matplotlib/issues/5380#issuecomment-1573958731) it seems a bad idea to trigger that on every PR. In fact, all that conversation gives a good insight on how many things can go wrong with it.

I don't know how could I even take all the `linkchecker` output and create a test triggering that and determine if it passes or fails. There are many other occurrences out there to do link-checking, but I'm unable to find something that may work for PVLIB without problems.

Anyway, IMO the most promising approach is the one that is currently done at Matplotlib. See [this instructions](https://github.com/matplotlib/matplotlib/issues/5380#issuecomment-1573958731) on the release procedure. And sorry for not bringing a better solution.

If an action could be made out of that, an action running weekly or so would be nice, like [this one](https://github.com/lxc/linuxcontainers.org/blob/f56254a966a2b53e3bcb3f9cd408af0a706e4f77/.github/workflows/linkcheck.yml).

**Pull request merged**
