### PR TITLE
update API entrypoint

### PR DESCRIPTION
**Pull request by ancirTOR**
new API entrypoint PVGIS 5.2

 - [ ] Closes #xxxx
 - [ ] I am familiar with the [contributing guidelines](https://pvlib-python.readthedocs.io/en/latest/contributing.html)
 - [ ] Tests added
 - [ ] Updates entries in [`docs/sphinx/source/reference`](https://github.com/pvlib/pvlib-python/blob/master/docs/sphinx/source/reference) for API changes.
 - [ ] Adds description and name entries in the appropriate "what's new" file in [`docs/sphinx/source/whatsnew`](https://github.com/pvlib/pvlib-python/tree/master/docs/sphinx/source/whatsnew) for all changes. Includes link to the GitHub Issue with `` :issue:`num` `` or this Pull Request with `` :pull:`num` ``. Includes contributor name and/or GitHub username (link with `` :ghuser:`user` ``).
 - [ ] New code is fully documented. Includes [numpydoc](https://numpydoc.readthedocs.io/en/latest/format.html) compliant docstrings, examples, and comments where necessary.
 - [ ] Pull request is nearly complete and ready for detailed review.
 - [ ] Maintainer: Appropriate GitHub Labels and Milestone are assigned to the Pull Request and linked Issue.

### CODE REVIEW

**Comment by mikofski** [comment]
👀 @kanderso-nrel

**Comment by AdamRJensen** [comment]
I have a feeling that it is a bad idea to hardcode the version number. What is your opinion @kanderso-nrel?

As stated in the [PVGIS doscs](https://joint-research-centre.ec.europa.eu/pvgis-photovoltaic-geographical-information-system/pvgis-releases/pvgis-52_en) the endpoint https://re.jrc.ec.europa.eu/api/ will default to 5.1 for now:
> The old entrypoint https://re.jrc.ec.europa.eu/api/tool_name?param1=value1&param2=value2&... will continue to serve PVGIS 5.1 for the time being. 

To me, this means that sometime in the future they will change this to default to the PVGIS 5.2 database, i.e., generally to the most recent version with somedelay.

Having the version hardcoded makes it difficult for users to understand which database is actually being used. Some versions of pvlib will then default to  5.1, some will use 5.2, and in the future maybe also 5.3 and so forth. As it is set up right now, users can utilize a specific version of the database by manually specifying the URL:

    data, input, meta = pvlib.iotools.get_pvgis_hourly(
        latitude=28.965734,
        longitude=117.147418,
        raddatabase='PVGIS-ERA5',
        url='https://re.jrc.ec.europa.eu/api/v5_2/')

**Comment by kanderso-nrel** [comment]
I guess "will continue serve PVGIS 5.1 for a limited period" and "will continue to serve PVGIS 5.1 for the time being" are both ambiguous -- they could mean that they will switch the old url to the new data, as you say and as I previously thought, or they could mean that they are changing the url scheme to explicitly include the data version, and someday the old versionless url will be retired.  Maybe we could just ask them for clarity :)

**Comment by AdamRJensen** [comment]
Hi @NikosAlexandris (employee at the Joint Research Center who works on PVGIS)
Perhaps you have an answer to the above question or could inform us who we can contact? 
Thanks!

**Comment by NikosAlexandris** [comment]
Apologies for the delay!

In the [API Non-Interactive Service](https://joint-research-centre.ec.europa.eu/pvgis-photovoltaic-geographical-information-system/getting-started-pvgis/api-non-interactive-service_en) documentation page, it is stated

>All the PVGIS tools can be accessed non-interactively using our web APIs. The entrypoints are:
>
>PVGIS 5.1: https://re.jrc.ec.europa.eu/api/v5_1/tool_name?param1=value1&param2=value2&...
>
>PVGIS 5.2: https://re.jrc.ec.europa.eu/api/v5_2/tool_name?param1=value1&param2=value2&...
>
>NB The old entrypoint https://re.jrc.ec.europa.eu/api/tool_name?param1=value1&param2=value2&...   will continue serve PVGIS 5.1 for a limited period.

Indeed, this isn't clear enough about the future setup. We are updating our database and once PVGIS v5.2 is ready, it will be the default version served via the _stadard_ entrypoint [https://re.jrc.ec.europa.eu/api/](https://re.jrc.ec.europa.eu/api/). What is served currently via [https://re.jrc.ec.europa.eu/api/v5_2/](https://re.jrc.ec.europa.eu/api/v5_2/) is _beta_ and comes with issues mentioned in the [release notes](https://joint-research-centre.ec.europa.eu/pvgis-photovoltaic-geographical-information-system/pvgis-releases/pvgis-52_en). In any case, we are not going to deprecate the default URL scheme.

**Comment by kanderso-nrel** [comment]
Thank you @NikosAlexandris for clarifying!  Sounds like we don't need to make any changes on our side and can close this PR then.  

Thanks also @ancirTOR for the PR, even if we didn't end up merging it :)

**Pull request closed without merging**
