### PR TITLE
port Purdue bifacial irradiance model

### PR DESCRIPTION
**Pull request by nappaillav**
- [ ] Closes #xxxx
 - [x] I am familiar with the [contributing guidelines](https://pvlib-python.readthedocs.io/en/latest/contributing.html)
 - [ ] Tests added
 - [ ] Updates entries to [`docs/sphinx/source/api.rst`](https://github.com/pvlib/pvlib-python/blob/master/docs/sphinx/source/api.rst) for API changes.
 - [ ] Adds description and name entries in the appropriate "what's new" file in [`docs/sphinx/source/whatsnew`](https://github.com/pvlib/pvlib-python/tree/master/docs/sphinx/source/whatsnew) for all changes. Includes link to the GitHub Issue with `` :issue:`num` `` or this Pull Request with `` :pull:`num` ``. Includes contributor name and/or GitHub username (link with `` :ghuser:`user` ``).
 - [x] New code is fully documented. Includes [numpydoc](https://numpydoc.readthedocs.io/en/latest/format.html) compliant docstrings, examples, and comments where necessary.
 - [x] Pull request is nearly complete and ready for detailed review.
 - [x] Maintainer: Appropriate GitHub Labels and Milestone are assigned to the Pull Request and linked Issue.

This is related to issue #863

### CODE REVIEW

**Comment by wholmgren** [comment]
@nappaillav are you planning on adding the bifacial code to this PR or did you want to split it into two PRs? My preference is a single PR since the trig functions are not explicitly tested and I don't see another near-term use for them.

**Comment by nappaillav** [comment]
@wholmgren  Initially I thought of having separate pull requests, but I guess its better to combine both as you suggest.

**Comment by nappaillav** [comment]
There are few more steps in the process of completed the port of Purdue bifacial irradiance model, which are as follows 
1) Description for the modules/ functions 
2) Testing of the individual functions 
3) Coding Style has to be corrected 

Currently I'm updating the code for your perusal. So that you can suggest me

**Comment by nappaillav** [comment]
@cwhanse I have updated the description. If you can let me know if the implementation is fine by you, we can proceed further. 
I also need help from you to completing the unit test.
I myself will do the write the test_codes, if you can provide me the test data (Input and output) it would be great.

**Comment by cwhanse** [comment]
> @cwhanse I have updated the description. If you can let me know if the implementation is fine by you, we can proceed further.

The new bifacial functions should be added to `pvlib.bifacial.py`.

I'd suggest
`pvlib.bifacial.irradiance_purdue`
`pvlib.bifacial.ground_reflected_purdue`

Although I'm not fond of the `ground_reflected` name, it will move us ahead.

> I also need help from you to completing the unit test.

Sure.  Before we do that, we need to clean up the commit - it's not reviewable in current form.

There's a lot of leftover Matlab formalities that need to be dropped or formatted to pass Stickler.

There's a bunch of recent commits to pvlib master in other PRs that show up here as new code changes @wholmgren should this be addressed with a git rebase?

**Comment by wholmgren** [comment]
Yes

**Comment by nappaillav** [comment]
I will rebase and make sure the commit is clean

**Comment by cwhanse** [comment]
Closing due to merge of #717

**Pull request closed without merging**
