### PR TITLE
0.1 documentation improvements

### LINKED ISSUE #8: Add What's New section to docs
A good pattern seems to be to make a separate file for each release.

Possibly helpful links

https://github.com/pydata/pandas/tree/master/doc/source

https://github.com/ipython/ipython/tree/master/docs/source

https://github.com/statsmodels/statsmodels/tree/master/docs/source

### PR DESCRIPTION
**Pull request by wholmgren**
Summarizing and copying material from #16, this PR includes improvements to

Major:

- [x] Add more to the homepage
- [x] Add basic install instructions
- [x] Link to Rob and Will's PVSC papers.
- [x] Add What's new section. Closes #8.
- [x] Add comparison to PVLIB_MATLAB section. 
- [x] Describe the relation to PVPMC, PVLIB-Matlab, address some of the points raised in #2.
- [x] Make a text link for the tutorials instead of my usual url dump.
- [x] Different page for each module? **I think not, at least for 0.1**

Minor:

- [x] Ineichen doesn’t provide info on single df output
- [x] function is now aoi, but docs reference getaoi throughout, except in actual function doc
- [x] lots of references to pvl_function not function
- [x] The numpydoc convention is to avoid using "See also" unless it's really important. **still not great, and many broken links, but I think good enough for 0.1**
- [x] The doc title capitalization needs to be updated.
- [x] Copyright needs to be updated.
- [x] pvlib.pvsystem.snlinverter has a long table that rtfd doesn't always format nicely **small improvement, good enough**
- [x] References to maketimestruct, makelocationstruct in pvlib.clearsky.haurwitz, maybe more.
- [x] pvlib.irradiance.beam_component has no documentation.
- [x] All modules need a better introduction to what's in them. **still not great, but I think good enough for 0.1**
- [x] pvlib.pvsystem.I_from_V has no documentation. **only added warning that this may go private**
- [x] pvlib.pvsystem.Voc_optfcn has no documentation. **only added warning that this may go private**
- [x] pvlib.pvsystem.calcparams_desoto says that module_parameters can be a Series, which, although true, is probably confusing. In any case, the doc's dict keys do not match the code's dict keys.
- [x] Misspelling in pvlib.pvsystem.retrieve_sam example.
- [x] Format equation in pvlib.pvsystem.singlediode
- [x] Add ``sphinx.ext.extlinks`` for issue tracking in what's new. Copied from pandas.

Does not address
- pvlib.pvsystem.systemdef as described in #17
- pvlib.tmy.readtmy2 refers to a metadata struct instead of a dict. Addressed in #7.

Docs can be viewed [here](http://wholmgren-pvlib-python-new.readthedocs.org/en/docfixes/index.html)

Let me know if you think that the doc improvements are good enough for the 0.1 release or if you want to see further changes on this PR.

### CODE REVIEW

**Comment by bmu** [comment]
From my side, this is good for the 0.1 release.

**Comment by wholmgren** [comment]
I think we should give @Calama-Consulting a chance for feedback on this one.

**Comment by wholmgren** [comment]
@dacoex the github links are now working in the test build. I will go through and add more links in either this pull request or others depending on merge order.

**Comment by dacoex** [comment]
@wholmgren all fine.

**Comment by Calama-Consulting** [comment]
This looks good, @wholmgren can you address the merge conflicts and I'll merge it

**Comment by wholmgren** [comment]
Ok, ready to merge.

**Pull request merged**
