### PR TITLE
Verify weather includes 'dhi' in ModelChain.prepare_inputs()

### LINKED ISSUE #1092: ModelChain.prepare_inputs can succeed with missing dhi
From the docstring for `ModelChain.prepare_inputs()` I believe the method should fail if `weather` does not have a `dhi` column.

The validation checks for `'ghi'` twice, but not `'dhi`'

https://github.com/pvlib/pvlib-python/blob/11c356f9a89fc88b4d3ff368ce1aae170a97ebd7/pvlib/modelchain.py#L1136

### PR DESCRIPTION
**Pull request by wfvining**
- [x] Closes #1092
 - [x] I am familiar with the [contributing guidelines](https://pvlib-python.readthedocs.io/en/latest/contributing.html)
 - [x] Tests added
 - [x] Adds description and name entries in the appropriate "what's new" file in [`docs/sphinx/source/whatsnew`](https://github.com/pvlib/pvlib-python/tree/master/docs/sphinx/source/whatsnew) for all changes. Includes link to the GitHub Issue with `` :issue:`num` `` or this Pull Request with `` :pull:`num` ``. Includes contributor name and/or GitHub username (link with `` :ghuser:`user` ``).
 - [x] Pull request is nearly complete and ready for detailed review.
 - [x] Maintainer: Appropriate GitHub Labels and Milestone are assigned to the Pull Request and linked Issue.

### CODE REVIEW

**Comment by wfvining** [comment]
I think this is ready for review, but I'm not sure what that test failure is about. It is from `test_get_psm3_5min`, which should be completely unaffected by this PR (doesn't look like the test interacts with `ModelChain` at all.

**Comment by cwhanse** [comment]
Test failure is due to #1091

**Review by wholmgren — APPROVED** [review]
Thanks @wfvining. I suggest we go ahead and merge.

**Comment by wfvining** [comment]
Thanks @cwhanse. I suspected it might be something like that.

**Pull request merged**
