### PR TITLE
Compatibility with pandas 2.0.0

### PR DESCRIPTION
**Pull request by kandersolar**
~- [ ] Closes #xxxx~
 - [x] I am familiar with the [contributing guidelines](https://pvlib-python.readthedocs.io/en/latest/contributing.html)
~- [ ] Tests added~
~- [ ] Updates entries in [`docs/sphinx/source/reference`](https://github.com/pvlib/pvlib-python/blob/main/docs/sphinx/source/reference) for API changes.~
~- [ ] Adds description and name entries in the appropriate "what's new" file in [`docs/sphinx/source/whatsnew`](https://github.com/pvlib/pvlib-python/tree/main/docs/sphinx/source/whatsnew) for all changes. Includes link to the GitHub Issue with `` :issue:`num` `` or this Pull Request with `` :pull:`num` ``. Includes contributor name and/or GitHub username (link with `` :ghuser:`user` ``).~
~- [ ] New code is fully documented. Includes [numpydoc](https://numpydoc.readthedocs.io/en/latest/format.html) compliant docstrings, examples, and comments where necessary.~
 - [x] Pull request is nearly complete and ready for detailed review.
 - [x] Maintainer: Appropriate GitHub Labels (including `remote-data`) and Milestone are assigned to the Pull Request and linked Issue.

The first release candidate for pandas 2.0.0 was released yesterday: https://github.com/pandas-dev/pandas/releases/tag/v2.0.0rc0.  It's available on PyPI with `pip install --pre pandas==2.0.0rc0`.  

The list of changes is pretty extensive, but it seems like we escape nearly unscathed: it doesn't seem to break anything in pvlib itself and only causes one small issue in our tests.  This PR fixes that test issue.

Since pvlib itself seems to be compatible, I suggest we wait to merge this PR until pandas 2.0.0 is officially released (anticipated in "a couple weeks") in case there are any other breaking changes made between now and then.

### CODE REVIEW

**Comment by adriesse** [comment]
> The first release candidate for pandas 2.0.0 was released yesterday

> This PR fixes that test issue.

I'm impressed!

**Comment by kanderso-nrel** [comment]
This branch has no failures on the just-released [2.0.0rc1](https://github.com/pandas-dev/pandas/releases/tag/v2.0.0rc1) as well.  Their ETA for the actual release of pandas 2.0.0 is still "about two weeks".

**Comment by kanderso-nrel** [comment]
This is ready for review now that pandas [2.0.0](https://github.com/pandas-dev/pandas/releases/tag/v2.0.0) has been released.  

Note that wheels are available on PyPI, but the new version isn't yet available on conda, so the CI isn't currently using it for the `remote-data` tests. In lieu of that I ran `pytest pvlib/tests/iotools/ --remote-data` locally with pandas 2.0.0 installed and all looks good.

**Review by AdamRJensen — APPROVED** [review]
LGTM

**Pull request merged**
