### PR TITLE
[Feature Preview] Shadow casting on and by flat surfaces

### LINKED ISSUE #2069: Direct and diffuse shading factors - spatial approach (for Photosynthetically Active Radiation)
**Is your feature request related to a problem? Please describe.**
This is the broadest proposal I'm ever going to do here, I think.

The model (or workflow, I don't know how to call it) is described in [1]. It compares the output of a Matlab script against PVsyst and SketchUp and calculates shading factors for direct and diffuse components, in the context of PAR incidence onto ground. Nevertheless part of the workflow seems equally applicable to shadows of other objects onto arrays.

A first step is a geometrical description of the PV arrays and projection of their shadows onto arbitrary planes, described in [3] of [1].

For the direct shading factor:

I already have arbitrary shadow castings onto a random plane: I'm currently at equation 20 of [1], finished section 4.3 of [3]. You can check out some dirty progress at [this gist](https://gist.github.com/echedey-ls/c6da724455ff16bc3f0e7a86cda0db82). Next steps include probably using the `shapely` package, doing intersections and unions of shadows.

For the diffuse shading factor:

A semi-spherical discrete integral is done. I haven't made any progress on it nor I have read enough to be sure about the approach.

**Describe the solution you'd like**
A functional set of functions in a new submodule, something along `spatial.py` ([shamelessly stealing this idea from @adriesse 😉 ](https://github.com/pvlib/pvlib-python/issues/1734#issuecomment-1816602613)) to handle the array rectangle and rotation creation, projection of the corners, and translation from 3D coordinates to 2D plane system (required for easy area calculations). I usually find functional code more hackable and well-documented.

Then I would like to add at least the fixed tilt agrivoltaic system modelling in an example. I can add the other examples in different PRs.

I'm still unsure regarding how to approach the diffuse integral.

**Describe alternatives you've considered**
- Create a parallel OOP modelling for 3D operations
  The base object would be:
  - `Surface` -> rectangle to describe arrays, the field or flat obstacles. Internally a shapely polygon. Initialized from azimuth, tilt, length, width and a point (a corner or the centroid). Would have methods to make the boundary checks of the shadows onto the surface (intersection), shadow area calculation (or output as a Polygon)
  The pro of this approach is no user mess of mis-reused variables, and ease of use I think. With solar azimuth and zenith and shadowing objects, I think a method can handle the projection:
  `shadow_polygon (or shadow_area) = shaded_surface.shadow_by(solar_azimuth, solar_zenith, array1, obstacle1, array2, obstacle2, ...)`
  I have doubts regarding trackers, since they change their corners coordinates.
  - This would possibly allow expanding the obstacles with more complex geometries, or defining them just as Polygons

- Add the above to the current `Array` class (or by inheritance)

**Additional context**
This is part of my GSoC PAR analysis proposals.

- [1] S. Zainali et al., ‘Direct and diffuse shading factors modelling for the most representative agrivoltaic system layouts’, Applied Energy, vol. 339, p. 120981, Jun. 2023, doi: [10.1016/j.apenergy.2023.120981](https://doi.org/10.1016/j.apenergy.2023.120981).
- [3] Y. Cascone, V. Corrado, and V. Serra, ‘Calculation procedure of the shading factor under complex boundary conditions’, Solar Energy, vol. 85, no. 10, pp. 2524–2539, Oct. 2011, doi: [10.1016/j.solener.2011.07.011](https://doi.org/10.1016/j.solener.2011.07.011).

I request input in:
- where to put new code
- whether or not to add more examples in a single PR
- approach: functional or OOP

### PR DESCRIPTION
**Pull request by echedey-ls**
- [x] Closes #2069
 - [x] I am familiar with the [contributing guidelines](https://pvlib-python.readthedocs.io/en/latest/contributing.html)
 - [ ] Tests added
 - [ ] Updates entries in [`docs/sphinx/source/reference`](https://github.com/pvlib/pvlib-python/blob/main/docs/sphinx/source/reference) for API changes.
 - [ ] Adds description and name entries in the appropriate "what's new" file in [`docs/sphinx/source/whatsnew`](https://github.com/pvlib/pvlib-python/tree/main/docs/sphinx/source/whatsnew) for all changes. Includes link to the GitHub Issue with `` :issue:`num` `` or this Pull Request with `` :pull:`num` ``. Includes contributor name and/or GitHub username (link with `` :ghuser:`user` ``).
 - [x] New code is fully documented. Includes [numpydoc](https://numpydoc.readthedocs.io/en/latest/format.html) compliant docstrings, examples, and comments where necessary.
 - [ ] Pull request is nearly complete and ready for detailed review.
 - [ ] Maintainer: Appropriate GitHub Labels (including `remote-data`) and Milestone are assigned to the Pull Request and linked Issue.

# Briefing
### Objectives
- Provide an API to calculate shades
- Intuitive
- Trying to follow the references

Possibly there's only one I have achieved.
⚠️ Trigger warning for reviewers: crap unfinished code

### General modifications this PR introduces
- `pvlib.spatial` module with two classes:
  - `FlatSurface`, can shade and can be shaded
  - `RectangularSurface`, inherits from above but allows for easy building of the common instance
- Two examples
  - Calculation of shades geometries + easy plot of row to row for a unique instant
    - Sandbox for myself, and for other people to play, test it
  - First example (fixed tilt) of the paper [1] in #2069 , Figure 9, top plot
    - Animation of the simulation
- New config option of sphinx-gallery to allow animations
- New dependency, shapely (probably should be pinned to >= 2)

### What is pending
- Completing the test suite
- Polishing docs
- Implement the generic `FlatSurface.plot()` method
- Implement `FlatSurface.combine_2D_shades()` to avoid overlapping shades (make it the default in `.get_2D_shades_from()`

#### Long-term roadmap
- Add 3D objects (the same projection of points, but using a ConvexHull to calculate the shade boundaries for certain objects or maybe composing of flat surfaces)
- Add opacity and the inclusion-exclusion algorithm to calculate the resulting shade transparency
- Add conical objects, i.e. trees

### Where & why I did not follow the references in some cases:
- Angle convention used has been the one described by the familiar reference [`Slope-Aware Backtracking for Single-Axis Trackers - NREL`](https://www.nrel.gov/docs/fy20osti/76626.pdf)
- Added rotation of surfaces, the known `axis_tilt`
- Added a surface point to the calculation of the interceptions. The original reference describes projecting the shadows onto the plane that goes through the origin, but I thought that is super-antiintuitive for any kind of user since it would make the coordinate system fixed to each item being shaded. In other words, a shading scene per shaded object. The extra step is a translation (points difference) of the projected object.

### Other information about the solution
- Does not use rotation matrices (originally it did): it uses the scipy spatial Rotation object, faster (quaternions), implements broadcasting, handy ways of instantiating the object
- Relies on shapely Polygons for a lot of things

### Controversial features (like if there weren't already enough)
- Does not allow the input to be a timeseries, only an instant (scalar solar zenith and azimuth)

# Status and discussion
You see, this is unfinished. I wouldn't allow myself to do this to you, but in one of the GSoC meetings I was hinted (fairly) that maybe this does not fit this repo. That maybe it does creating another repo under the pvlib organization. Maybe not even that.

And since there wasn't much conversation at #2069, opening this PR is partly to kickstart the discussion regarding that.

Regarding the model, the simulated plot:
image

Does not match the results for the Winter Solstice:
image

# Docs
- Spatial module
  - `FlatSurface`: https://pvlib-python--2106.org.readthedocs.build/en/2106/reference/generated/pvlib.spatial.FlatSurface.html
  - `RectangularSurface`: https://pvlib-python--2106.org.readthedocs.build/en/2106/reference/generated/pvlib.spatial.RectangularSurface.html
- Examples
  - Minimal example for instantaneous data: https://pvlib-python--2106.org.readthedocs.build/en/2106/gallery/shading/plot_spatial_row_to_row_shading.html#sphx-glr-gallery-shading-plot-spatial-row-to-row-shading-py
  - PAR shading example, animation: https://pvlib-python--2106.org.readthedocs.build/en/2106/gallery/agrivoltaics/plot_par_direct_shading0_fixed_tilt.html#sphx-glr-gallery-agrivoltaics-plot-par-direct-shading0-fixed-tilt-py

### CODE REVIEW

**Comment by echedey-ls** [comment]
Ready for preview @kandersolar , @AdamRJensen , @cwhanse , the rest of @pvlib/maintainers (I can't ping the team)

Feel free to weight in whatever comes to your mind, but firstly focus on whether pvlib is a good place for this please. TIA.

**Comment by echedey-ls** [comment]
@mikofski , @adriesse , @markcampanelli would you like to weight in whether pvlib is a good place to include this? So I can determine if I should continue working on the code or not.

### Docs
- Spatial module
        - FlatSurface: https://pvlib-python--2106.org.readthedocs.build/en/2106/reference/generated/pvlib.spatial.FlatSurface.html
        - RectangularSurface: https://pvlib-python--2106.org.readthedocs.build/en/2106/reference/generated/pvlib.spatial.RectangularSurface.html
- Examples
        - Minimal example for instantaneous data: https://pvlib-python--2106.org.readthedocs.build/en/2106/gallery/shading/plot_spatial_row_to_row_shading.html#sphx-glr-gallery-shading-plot-spatial-row-to-row-shading-py
        - PAR shading example, animation: https://pvlib-python--2106.org.readthedocs.build/en/2106/gallery/agrivoltaics/plot_par_direct_shading0_fixed_tilt.html#sphx-glr-gallery-agrivoltaics-plot-par-direct-shading0-fixed-tilt-py

**Comment by cwhanse** [comment]
I am not in favor of building 3D lighting/shade calculators into pvlib-python. My reasons:

- I think the code base will necessarily be large and I worry about long-term maintenance
- it is likely to introduce dependencies that aren't used elsewhere in pvlib (e.g. shapely)
- I can't help but think that lighting/shade calculations are already being done in other libraries and pvlib would only need some shim code. Perhaps that's wishful thinking.

For these reasons, I think a new project (pvlib3d?) makes more sense than `pvlib.spatial`.

**Comment by echedey-ls** [comment]
Seems like there is consensus on not including something like this here, so I'm closing this PR.

**Pull request closed without merging**
