### PR TITLE
Update module and inverter files (#761)

### LINKED ISSUE #761: Update module and inverter files
CEC module and inverter files are >1year old, and should be updated for the next pvlib release.

### PR DESCRIPTION
**Pull request by Peque**
pvlib python pull request guidelines
====================================

 - [x] Closes  #761
 - [x] I am familiar with the [contributing guidelines](http://pvlib-python.readthedocs.io/en/latest/contributing.html).
 - [x] Fully tested. Added and/or modified tests to ensure correct behavior for all reasonable inputs. Tests (usually) must pass on the TravisCI and Appveyor testing services.
 - [x] Updates entries to `docs/sphinx/source/api.rst` for API changes.
 - [x] Adds description and name entries in the appropriate `docs/sphinx/source/whatsnew` file for all changes.
 - [x] Code quality and style is sufficient. Passes LGTM and SticklerCI checks.
 - [x] New code is fully documented. Includes sphinx/numpydoc compliant docstrings and comments in the code where necessary.
 - [x] Pull request is nearly complete and ready for detailed review.

### CODE REVIEW

**Comment by Peque** [comment]
I am assuming already-existing tests are sufficient and I am not expected to add new tests for this change. Please tell me otherwise. :blush:

I did not modify `docs/sphinx/source/whatsnew` as I guess I am not supposed to know when this will be integrated and released (`0.6.4`, `0.7.0`, `x.x.x`... ?)

**Comment by cwhanse** [comment]
> I am assuming already-existing tests are sufficient and I am not expected to add new tests for this change. Please tell me otherwise. 😊
Correct

> I did not modify docs/sphinx/source/whatsnew as I guess I am not supposed to know when this will be integrated and released (0.6.4, 0.7.0, x.x.x... ?)
v0.7.0

**Comment by Peque** [comment]
@cwhanse Tests seem to be passing now. :blush:

Mind suggesting (or directly amending) the note to "what's new" section?

**Comment by Peque** [comment]
@cwhanse Friendly ping. :innocent:

**Comment by cwhanse** [comment]
> @cwhanse Tests seem to be passing now. 😊
> Mind suggesting (or directly amending) the note to "what's new" section?

My apologies, this fell of my list to do.

**Comment by cwhanse** [comment]
@wholmgren ok to merge?

**Pull request merged**
