### PR TITLE
Add shield organization table with download shields

### LINKED ISSUE #813: Please add a download counter to the GitHub readme
**Is your feature request related to a problem? Please describe.**
Not a problem, but an opportunity

**Describe the solution you'd like**
Add download shield to Readme.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by CameronTStark**
- [x] Closes  #813
 - [x] I am familiar with the [contributing guidelines](http://pvlib-python.readthedocs.io/en/latest/contributing.html).
 - [x] Fully tested. Added and/or modified tests to ensure correct behavior for all reasonable inputs. Tests (usually) must pass on the TravisCI and Appveyor testing services.
* N/A
 - [x] Updates entries to `docs/sphinx/source/api.rst` for API changes.
* N/A
 - [X] Adds description and name entries in the appropriate `docs/sphinx/source/whatsnew` file for all changes.
* N/A
 - [x] Code quality and style is sufficient. Passes LGTM and SticklerCI checks.
 - [x] New code is fully documented. Includes sphinx/numpydoc compliant docstrings and comments in the code where necessary.
* N/A
 - [x] Pull request is nearly complete and ready for detailed review.

Brief description of the problem and proposed solution (if not already fully described in the issue linked to above):

This PR addresses  #813 to add download counter shields for the README. It also implements a table organizing the shields by a descriptive title. 

I've included a placeholder shield for Azure Pipelines from Pandas as an example of a new shield to add. @wholmgren if adding this Azure Pipelines shield is desired it needs to be activated according to [this guide](https://docs.microsoft.com/en-us/azure/devops/pipelines/create-first-pipeline?view=azure-devops&tabs=tfs-2018-2#add-a-status-badge-to-your-repository).

Please let me know what you all think about the table format, titles and general organization.

### CODE REVIEW

**Comment by wholmgren** [comment]
@CameronTStark can you rebase on pvlib/master?

**Comment by wholmgren** [comment]
I really like the table! (other reviewers: see the branch's readme [here](https://github.com/CameronTStark/pvlib-python/tree/shield_org))

I couldn't follow the linked Azure Pipelines instructions. Its interface didn't seem to line up with the documentation. But I think the following badge works:

[Build Status](https://dev.azure.com/solararbiter/pvlib%20python/_build/latest?definitionId=4&branchName=master)

```
[![Build Status](https://dev.azure.com/solararbiter/pvlib%20python/_apis/build/status/pvlib.pvlib-python?branchName=master)](https://dev.azure.com/solararbiter/pvlib%20python/_build/latest?definitionId=4&branchName=master)
```

**Comment by CameronTStark** [comment]
> @CameronTStark can you rebase on pvlib/master?

Done. Thanks for the warning.

I've included the Azure Pipelines urls for pvlib. Thanks for that.

I'm glad you like the format. :smile

**Comment by cwhanse** [comment]
The table looks great!  

Is there a conda badge to go with the pypi badge?

How should I interpret the downloads?  Since some date?  Wondering if it is possible and useful to add dates to the Latest Release, and a "Downloads since" date.

**Comment by CameronTStark** [comment]
> Is there a conda badge to go with the pypi badge?

Good idea. [Here's a link to more of the Anaconda badges.](https://anaconda.org/conda-forge/pvlib-python/badges) We could put this one next to PyPI: [Anaconda-Server Badge](https://anaconda.org/conda-forge/pvlib-python)

 
> How should I interpret the downloads? Since some date? Wondering if it is possible and useful to add dates to the Latest Release, and a "Downloads since" date.

The PyPI one is per month and the conda-forge  is total. The PyPI appears disproportionate to the conda-forge so I'm wondering where that could come from. I've looked at the numbers on [PyPIstats.org](https://pypistats.org/packages/pvlib) and there's a big jump in Linux Python 3.6 users downloading pvlib-python in late June. Any ideas what that could be from? Was there a CI change then? I think legacy Python(2) support was dropped then, maybe it nudged people into staying current?

PyPI logs metrics to Google BigQuery and the badge/shield providers crunch that data depending on the time scale chosen either daily, weekly or monthly. BigQuery is free so we could go into there and crunch the numbers in any way we want but we'd probably have to build a means of calculating from a previous release unless we found a badge provider that would do that for us.  I could imagine doing that crunch manually before a conference presentation as a means of showing usage growth.

Here's a few more links:
https://pypi.org/help/ # search page for statistics
https://pypistats.org/faqs

**Comment by cwhanse** [comment]
> The PyPI one is per month and the conda-forge  is total. The PyPI appears disproportionate to the conda-forge so I'm wondering where that could come from. I've looked at the numbers on PyPIstats.org and there's a big jump in Linux Python 3.6 users downloading pvlib-python in late June. Any ideas what that could be from? Was there a CI change then? 

Something changed. The NumFocus affiliated status was in April 2019. I looked at the commit history and didn't recognize a change that could explain the surge in downloads that started in June 2019.

**Comment by wholmgren** [comment]
Interesting that there is a gradual build up over a month instead of a step change over a single day. I'm almost certain the change does not reflect a dramatic increase in the number of users. I'd like to think that someone like Google or Facebook started using pvlib at some bigger scale for something interesting, but I'm guessing the answer is much less exciting.

**Comment by cwhanse** [comment]
> Is there a conda badge to go with the pypi badge?
> 
> Good idea. Here's a link to more of the Anaconda badges. We could put this one next to PyPI: 

Suggest we add the conda badge and the Last Updated badge with date (not months and days).  Not a sticking point for me, OK to merge.

**Comment by CameronTStark** [comment]
Will do. I'll create another row for Last Updated and try to include PyPI as well.

**Comment by CameronTStark** [comment]
This should be ready to merge from my side.

**Pull request merged**
