### PR TITLE
implement voltage, current, power scaling function and method

### PR DESCRIPTION
**Pull request by wholmgren**
This PR implements a simple scaling function and hooks it up to PVSystem and ModelChain. I'm open to changing things.

I'd like to merge early next week.

### CODE REVIEW

**Comment by wholmgren** [comment]
I'll merge tomorrow unless someone comments, which you should, because I'm confident that there's a non-0 number of users that will find this useful if done right and annoying if done wrong. 

original issue: #159.

**Comment by jforbess** [comment]
It looks good to me. I was trying to decide if there was any value in calculating voltage and current multipliers separately, but I think there is not, because any adjustments on either that are needed (electrical shading) can happen before the dc parameters are fed to the inverter. 

I appreciate the clarification you provided over the definiton of series_modules and parallel_modules, but one recommended change is to say that parallel_modules are the number of strings in parallel, not the number of *modules or* strings in parallel. I think that wording just confuses. The parameter name is confusing in general, but I've made my peace with it. :)

**Comment by wholmgren** [comment]
Thanks for the feedback. One quick proposal and then a longer discussion...

Quick: What if I change the individual parameter descriptions to something like "see system topology discussion above"?

Long: I agree that the parameter names and descriptions are confusing. Now is a good time to change them since they didn't actually do anything before. Well, they didn't do anything useful in pvlib code, but maybe users did something with them in their own code. In any case, they're not my creation and I have no attachment to them. I would support something like ``series_modules --> modules_per_string`` and ``parallel_modules --> strings``. We can also merge this and then address the name issue separately.

**Comment by jforbess** [comment]
Quick: Sure, that's fine.

Long: If no one else complains, I would definitely prefer
modules_per_string and strings, for clarity. I don't mind series_modules,
but parallel_modules is so confusing and annoyingly wrong in concept.

**Pull request merged**
