### PR TITLE
TST:MNT: add 30 minutes to test data

### PR DESCRIPTION
**Pull request by mikofski**
pvlib python pull request guidelines
====================================

Thank you for your contribution to pvlib python! You may delete all of these instructions except for the list below.

You may submit a pull request with your code at any stage of completion.

The following items must be addressed before the code can be merged. Please don't hesitate to ask for help if you're unsure of how to accomplish any of the items below:

 - [ ] Closes issue #731 
 - [ ] I am familiar with the [contributing guidelines](http://pvlib-python.readthedocs.io/en/latest/contributing.html).
 - [ ] Fully tested. Added and/or modified tests to ensure correct behavior for all reasonable inputs. Tests (usually) must pass on the TravisCI and Appveyor testing services.
 - [ ] Updates entries to `docs/sphinx/source/api.rst` for API changes.
 - [ ] Adds description and name entries in the appropriate `docs/sphinx/source/whatsnew` file for all changes.
 - [ ] Code quality and style is sufficient. Passes LGTM and SticklerCI checks.
 - [ ] New code is fully documented. Includes sphinx/numpydoc compliant docstrings and comments in the code where necessary.
 - [ ] Pull request is nearly complete and ready for detailed review.

Brief description of the problem and proposed solution (if not already fully described in the issue linked to above):

### CODE REVIEW

**Comment by cwhanse** [comment]
At this point we don't know if this change to the NSRDB is intended and will be permanent.  Perhaps let's comment out comparison of the `Minute` field from the test, and hold this change to the data file. I've asked NREL about the NSRDB change.

**Comment by cwhanse** [comment]
@mikofski can you revert the change to `test_psm3.csv` for now?  Thanks for this patch.

**Comment by mikofski** [comment]
FYI: [codecov thinks this change reduces coverage by -1 lines](https://codecov.io/gh/pvlib/pvlib-python/commit/c1ebff81da538cd8779c373d6ad9f85867f64d7a), because there is one new line, the comment, or maybe because I commented out one line?

    # unclear if NSRDB changes are permanent

**Comment by cwhanse** [comment]
Thanks @mikofski

**Pull request merged**
