### PR TITLE
ADR PV efficiency model from pvpltools-python

### LINKED ISSUE #1544: Migrate efficiency models from pvpltools-python
**Describe the solution you'd like**
A number of different models exist to estimate efficiency (or power) as a function of irradiance and temperature.  I coded and published many of them in my own repository [pvpltools-python](https://github.com/adriesse/pvpltools-python) as it was quicker to do than a pvlib PR, but I think they would fit nicely into pvlib-python.  

https://github.com/adriesse/pvpltools-python/blob/master/pvpltools/module_efficiency.py

**Additional context**
Oh yes, I almost forgot: I developed such a model myself also and it's in there.

### PR DESCRIPTION
**Pull request by adriesse**
- [x] Partially fulfills #1544
 - [x] I am familiar with the [contributing guidelines](https://pvlib-python.readthedocs.io/en/latest/contributing.html)
 - [x] Tests added
 - [ ] Updates entries in [`docs/sphinx/source/reference`](https://github.com/pvlib/pvlib-python/blob/master/docs/sphinx/source/reference) for API changes.
 - [ ] Adds description and name entries in the appropriate "what's new" file in [`docs/sphinx/source/whatsnew`](https://github.com/pvlib/pvlib-python/tree/master/docs/sphinx/source/whatsnew) for all changes. Includes link to the GitHub Issue with `` :issue:`num` `` or this Pull Request with `` :pull:`num` ``. Includes contributor name and/or GitHub username (link with `` :ghuser:`user` ``).
 - [x] New code is fully documented. Includes [numpydoc](https://numpydoc.readthedocs.io/en/latest/format.html) compliant docstrings, examples, and comments where necessary.
 - [x] Pull request is nearly complete and ready for detailed review.
 - [ ] Maintainer: Appropriate GitHub Labels (including `remote-data`) and Milestone are assigned to the Pull Request and linked Issue.

### CODE REVIEW

**Comment by steve-ransome** [comment]
I agree we should unify coding into sensible locations as soon as possible.

1) mpm fits not just the performance ratio but also other normalised coefficients such as i_sc, r_sc, i_mp. Will this code only fit performance ratio or are other parameters allowed?

2) The SAPM has 4 different equations to fit measured i_sc, i_mp, v_mp and v_oc, which can then be used to generate p_mp, pr_dc. Will this be added?

3) The equation you used for PVGIS needs a correction factor for any degradation or eta_meas/eta_nameplate at STC

**Comment by adriesse** [comment]
> I agree we should unify coding into sensible locations as soon as possible.
> 
>    1. mpm fits not just the performance ratio but also other normalised coefficients such as i_sc, r_sc, i_mp, i_ff ... v_oc, ff.
>        Will this code only fit performance ratio or are other parameters allowed?
>

Yes, if mpm has those capabilities, why not?  Is that in the current code already, or something you're thinking about adding later?

>    2. The SAPM has 4 different equations to fit measured i_sc, i_mp, v_mp and v_oc, which can then be used to generate p_mp, pr_dc. Will this be added?

That's not on my radar, but clearly both 1. and 2. could lead to different code organization ideas.
 
>    3. The equation you used for PVGIS needs a correction factor for any degradation or eta_meas/eta_nameplate at STC

Yes, I wrote about this problem, but for me the model is primarily of historical interest.

**Comment by steve-ransome** [comment]
> > I agree we should unify coding into sensible locations as soon as possible.
> > 
> > 1. mpm fits not just the performance ratio but also other normalised coefficients such as i_sc, r_sc, i_mp, i_ff ... v_oc, ff.
> >    Will this code only fit performance ratio or are other parameters allowed?
> 
> Yes, if mpm has those capabilities, why not? Is that in the current code already, or something you're thinking about adding later?

It's already in the code. You make var_to_fit as 'pr_dc', 'v_mp', 'r_sc' or whatever and it will fit it. The jupyter notebooks only have the 'pr_dc' in there but I've fitted all the other parameters in my publications such as this http://www.steveransome.com/pubs/2206_PVSC_49_Ransome_to_be_presented.pdf

**def mlfm_fit(data, var_to_fit):
    var_to_fit : string
        Column name in ``data`` containing variable being fitted.**
> 
> > 2. The SAPM has 4 different equations to fit measured i_sc, i_mp, v_mp and v_oc, which can then be used to generate p_mp, pr_dc. Will this be added?
> 
> That's not on my radar, but clearly both 1. and 2. could lead to different code organization ideas.

OK, as I knew SAPM and PVGIS are commonly used I analysed them in the paper I just linked. I also looked at the bilinear interpolation but as we've discussed before I really don't think it's a good idea at all. The traces are not linear with irradiance.
> 
> > 3. The equation you used for PVGIS needs a correction factor for any degradation or eta_meas/eta_nameplate at STC
> 
> Yes, I wrote about this problem, but for me the model is primarily of historical interest.

OK, I have seen others acknowledge the problem and correct for it. I changed the 1 to be k_0 to solve that.

**Comment by adriesse** [comment]
Well, maybe my opening suggestion was not the best in light of mpm/mlfm being used with a gradually expanding number of predictors and also applied to a multiple response variables.  Perhaps it is better to see how #1354 evolves before trying to solve this.

**Comment by adriesse** [comment]
Open for comments and/or reviews although not 100% done.

**Comment by adriesse** [comment]
FYI: I messed up my branch so I started over.

**Pull request closed without merging**
