### PR TITLE
Linke turbidity factor fixes

### LINKED ISSUE #262: Linke turbidity out of bounds error at (90, 180)
Some of the edge cases don't work:

```python
>>> from pvlib.clearsky import lookup_linke_turbidity
>>> import pandas as pd
>>> time = pd.DatetimeIndex(start='1/1/2016', end='1/2/2016', freq='H')
>>> import os
>>> lookup_linke_turbidity(time, 90, 180, os.path.join('Downloads', 'LinkeTurbidities.mat'))

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python27\lib\site-packages\pvlib\clearsky.py", line 210, in lookup_linke_turbidity
    g = linke_turbidity_table[latitude_index][longitude_index]
IndexError: index 4320 is out of bounds for axis 0 with size 4320
```

Should be an easy fix, I will try to submit something today, and obviously since these edge cases are north and south poles, I don't think that this issue occurs very often if ever - nevertheless, it should be handled gracefully.

### LINKED ISSUE #263: linke turbidity resolution should be 1/12 of an arcdegree
The Linke turbidity should be 1/12 = 0.0833 of an arc degree or 5' (minutes of arc degrees) - see [section 8 from "Aerosol optical depth and Linke turbidity climatology"][1] and [SoDa Pro: Linke Turbidity Factor](http://www.soda-pro.com/help/general-knowledge/linke-turbidity-factor), or the old [SoDa Linke Turbidity](http://www.soda-is.com/eng/services/linke_turbidity_maps_info.html) and [reference](http://www.soda-is.com/eng/services/linke_turbidity_info.html). Instead latitude is 180/2159 = 0.083372 and longitude is 360/4319 = 0.083353.

Section 8.1: Format of the data explains:

>Optionally the files are also available in 1/12° resolution. These files were organised in the following form:
1st row: 89.9583° S, 2nd row: 89.875 ° S, …
1st column: 179.9583°W, 2nd column: 179.875°W, …

This indicates that each measurement is at the center of the node, not the edges. _IE_: the 1st node is not at 90° but (90° - 1/24°) =  89.9583°.

The values of TL at points for any latitude along the longitude -180° and +180° don't match, and therefore indicate that they are not the same.

lt_180lon_janjun

[1]: http://www.meteonorm.com/images/uploads/downloads/ieashc36_report_TL_AOD_climatologies.pdf

### PR DESCRIPTION
**Pull request by mikofski**
fixes #263 and fixes #262 

* shift `outputmin` to zero, since (1) zero based indexing, and (2) documentation states that indices of LT data are 0.0833[arcdeg] apart
* shift from edge to center
* raise `IndexError` for out of bound lat/lon
* add `test_linke_turbidity_corners()` to test corners are not out of bounds, PASSES, but older tests fail since increment is different.

### CODE REVIEW

**Comment by wholmgren** [comment]
Thanks for digging into this!

I'm a bit skeptical that the new log messages are going to be useful to anyone after this is merged. I've been slowly removing all of the silly logging that I added before I was using pdb. 

You can get rid of that todo comment, as far as I'm concerned. I think users have a responsibility to follow our conventions.

The tests that throw IndexErrors should use pytest as shown here: http://doc.pytest.org/en/latest/assert.html#assertions-about-expected-exceptions

**Comment by mikofski** [comment]
@wholmgren do you want me to revise the 3 failing tests with new expected values?

```
pvlib/test/test_clearsky.py::test_lookup_linke_turbidity FAILED
pvlib/test/test_clearsky.py::test_lookup_linke_turbidity_months FAILED
pvlib/test/test_clearsky.py::test_lookup_linke_turbidity_nointerp_months FAILED
```

**Comment by mikofski** [comment]
Reverse engineering the current expected LT values to make sure the new calculation is consistent:

### [`test_lookup_linke_turbidity()`](../blob/master/pvlib/test/test_clearsky.py#L158-L166)
```
lat, lon = 32.2, -111
# using _linearly_scale
lat = (lat - 90.) * (-2159. / 180.) + 1.  # 694.2788888888888
lon = (lon - (-180.)) * (4319. / 360.) + 1.  # 828.8083333333333
# now use new lookup method, shifting the indices to their corrected inputs at (32.125, -110.875)
clearsky.lookup_linke_turbidity(
    times, 90. - np.around(lat) / 12. - (1. / 24.), np.around(lon) / 12. - 180. + (1. / 24.)
)
# 2014-06-24 00:00:00-07:00    3.101266
# 2014-06-24 12:00:00-07:00    3.101266
# 2014-06-25 00:00:00-07:00    3.114430
# Freq: 12H, dtype: float64
```
yields the same result as the expected answer

**Comment by wholmgren** [comment]
Can you look into doing the same thing for the rest of the tests? I'm guessing that it will work for some but not others. Maybe can adjust the precision of the tests too.

**Comment by mikofski** [comment]
Can you tell me which tests aren't passing? All `test_clearsky.py` pass for me.

**Comment by wholmgren** [comment]
There is a failing test in ``test_location`` and a bunch in ``test_modelchain``

https://travis-ci.org/pvlib/pvlib-python/jobs/176473332

Other than copy/pasting a bunch of new values, the easiest way to fix the modelchain tests might be to manually supply the irradiance data in the ``mc.run_model`` calls. Is that asking too much?

**Comment by mikofski** [comment]
There is an error in `test_forecast.test_process_data[NDFD]` that I don't think has anything to do with Linke turbidity factors, but I might be wrong?

```
==================================== ERRORS ====================================
__________________ ERROR at setup of test_process_data[NDFD] ___________________
request = <SubRequest 'model' for <Function 'test_process_data[NDFD]'>>
    @requires_siphon
    @pytest.fixture(scope='module', params=_modelclasses)
    def model(request):
        amodel = request.param()
        amodel.raw_data = \
>           amodel.get_data(_latitude, _longitude, _start, _end)
pvlib/test/test_forecast.py:51: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
pvlib/forecast.py:252: in get_data
    self.data = self._netcdf2pandas(self.netcdf_data, self.query_variables)
pvlib/forecast.py:333: in _netcdf2pandas
    self.set_time(netcdf_data.variables[time_var])
pvlib/forecast.py:357: in set_time
    times = num2date(time[:].squeeze(), time.units)
netCDF4/_netCDF4.pyx:3695: in netCDF4._netCDF4.Variable.__getitem__ (netCDF4/_netCDF4.c:37923)
    ???
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
>   ???
E   IndexError
netCDF4/_netCDF4.pyx:4374: IndexError
```

**Comment by wholmgren** [comment]
Awesome, thanks! Two minor things left to do: 

1. add ``@requires_scipy`` to your new corner cases test. That's the reason for the failure on the travis py27-min build. 
2. add some notes to the 0.4.2 whatsnew file. Be sure to mention that typical modeling results could change by ~1%, depending on location, if they depend on the turbidity table.

The test_forecast error is unrelated (sorry).

**Comment by wholmgren** [comment]
Thanks @mikofski!

**Pull request merged**
