### PR TITLE
Adding Mechanistic Performance and Loss Factors Models to pvlibMerge remote-tracking branch 'refs/remotes/pvlib/master'

### LINKED ISSUE #925: Adding the Loss Factors Model and Mechanistic Performance Models to PVLIB
I'll be adding the Loss Factors Models and Mechanistic Performance Models to PVLIB, . 

See http://www.steveransome.com/PUBS/1906_PVSC46_Chicago_Ransome.pdf for more details on what they do

I hope it should be ready by the conference in Salt Lake in May

I've uploaded a couple of graphs and some sample code and Initially I'm looking for feedback and comments as I will need to enhance the present naming convention

With the LFM I have been using prefix and suffix letters to describe the type of measurement and any corrections. For example this Python 3 code shows the naming I have been using and does normalised LFM and temperature correction.
I have just shown nIsc and nVoc for clarity but will upload code for all variables soon plus graphs and MPM fits.

Once I have this in a correct form I can add more of features

mSi0188_nVoc_U_5) mSi0188_nVoc_U_C4 ~  102 1%; -0 33%; 14 64%; -2 27%
mSi0188_PRdc_lfm_gi_3
[MLFM_SRCL_200302.py.txt](https://github.com/pvlib/pvlib-python/files/4278331/MLFM_SRCL_200302.py.txt)

Any feedback is welcome
Steve

### PR DESCRIPTION
**Pull request by steve-ransome**
- [x] Closes #925
 - [x] I am familiar with the [contributing guidelines](https://pvlib-python.readthedocs.io/en/latest/contributing.html)
 - [ ] Tests added
 - [ ] Updates entries to [`docs/sphinx/source/api.rst`](https://github.com/pvlib/pvlib-python/blob/master/docs/sphinx/source/api.rst) for API changes.
 - [ ] Adds description and name entries in the appropriate "what's new" file in [`docs/sphinx/source/whatsnew`](https://github.com/pvlib/pvlib-python/tree/master/docs/sphinx/source/whatsnew) for all changes. Includes link to the GitHub Issue with `` :issue:`num` `` or this Pull Request with `` :pull:`num` ``. Includes contributor name and/or GitHub username (link with `` :ghuser:`user` ``).
 - [x] New code is fully documented. Includes [numpydoc](https://numpydoc.readthedocs.io/en/latest/format.html) compliant docstrings, examples, and comments where necessary.
 - [ ] Pull request is nearly complete and ready for detailed review.
 - [ ] Maintainer: Appropriate GitHub Labels and Milestone are assigned to the Pull Request and linked Issue.

### CODE REVIEW

**Comment by mikofski** [comment]
Hi @steve-ransome ,

Great job opening the PR. I've linked it to the original issue in the description above by using the issue number (925). Make sure to go through the rest of the items in the checklist.

Here are a couple of other items that will help move this PR:

1. Can you please create a new branch and call it something like "loss-factor-model" ? You should do this at the HEAD of the branch that you're currently working on (which is currently master). I think you can use [TortoiseGit](https://tortoisegit.org/docs/tortoisegit/tgit-dug-branchtag.html) by right clicking in the folder where your development version of pvlib is cloned. Remember to check the box that says, "check out new branch" or you'll still be on master and so you'll have to [check out the new branch](https://tortoisegit.org/docs/tortoisegit/tgit-dug-checkout.html). You can also skip TortoiseGit and just enter the equivalent [git commands](https://git-scm.com/docs/git-checkout) in a terminal:

       (master) path/to/pvlib$ git checkout -b loss-factor-model

2. Once you've checked out the new branch, push it up to your GitHub fork of pvlib python. Then you may need to edit this PR to point to the new branch, or just close it and open a new one from the new branch.

3. You'll need to remove the desktop.ini file from your git repo and then ignore it. If it's important, you can just copy it somewhere else, then [delete the file from the repo with TortoiseGit](https://tortoisegit.org/docs/tortoisegit/tgit-dug-rename.html). The you can copy it back to your folder if it's important and [ignore it using TortoiseGit](https://tortoisegit.org/docs/tortoisegit/tgit-dug-ignore.html). Just right click on the file and select ignore. This creates a new file in your folder called `.gitignore`. Right click on `.gitignore` and select Add. Then commit the changes to make them permanent. You can also use these [git commands](https://git-scm.com/docs/git-rm) in a terminal:

       (loss-factor-model) path/to/pvlib$ git rm --cached desktop.ini
       (loss-factor-model) path/to/pvlib$ echo desktop.ini >> .gitignore
       (loss-factor-model) path/to/pvlib$ git add .gitignore
       (loss-factor-model) path/to/pvlib$ git commit -am "ignore desktop.ini"

4. You need to remove all of the figures and add them either to a jupyter notebook or a gallery example. See the existing gallery examples as a guide. A Jupyter notebook might be easier. The Jupyter notebook should have the commands to call your code and create the figures. It would serve as an example or tutorial to new users.

5. start working on the Stickler warnings that are in the checks above. The red X means that there are some style issues that don't follow the Python [pep8](https://pep8.org/) guidelines. If you run into issues, just post them here and we can help you through them.

I suggest you find someone in your timezone who you can have a chat / screen share with. Someone who has contributed to pvlib before like maybe @adriesse ?

Good luck!
Mark

**Comment by adriesse** [comment]
Hi @steve-ransome and @mikofski ,

I don't think I'm the best person to the git/github mechanics, but before trying to please the various bots I would maybe first try to figure out how to integrate a little more into the pvlib structure.  Ideally there would be some low-level model-related functions without graphics or user interaction, and then you could perhaps put the latter into a Jupyter Notebook?  Not speaking as an expert here either because I rarely use Jupyter myself.

Anyway, it's good to get the ball rolling.

Anton

**Comment by steve-ransome** [comment]
Thanks @mikofski   and @adriesse  for the help and advice.

The mlfm code explained in https://pvpmc.sandia.gov/download/7879/ was almost "self contained" in that it went from 
raw measured inputs though normalisation, sanity checks, mlfm model fitting, parameter and degradation extraction and then showed performance and any degradation. 

Most of the calculations, file handling and graphics are as python library functions in mlfm_lib.py rather than in the Jupyter notebook. These can be used independently such as the data normalisation routine e.g.

    def mlfm_meas_to_norm (dref, dmeas, mod_row):
        ''' 
        converts 
        measured dataframe = meas(isc,rsc ... voc) (V,A,W,Ohms) 
        normalising by reference stc dataframe = ref(isc,rsc ... voc)
        to normalised value dataframe = norm(isc,rsc ... voc) (~1) 
        '''

In the Jupyter notenook the only operator inputs are 
1) what measurement datafile to read 
2) which mlfm parameter to analyse further. 

Sensible defaults are given to some options (e.g. xaxis of graphs, irradiance or tmodule, yaxis scaling) and the user is shown how to alter those if they want.

The measurement data input, model curve fitting and power prediction side are most similar to the tmy_to_power tutorial so I can look at that approach to show how to use these lib functions, this table shows some of the similarity and maybe how best to get the mlfm code being compared and used


```
                                                    https://pvpmc.sandia.gov/download/7879/
                                                    slide 16
Stage                  tmy_to_power.ipynb           mlfm_pvpmc.ipynb
 
import met data        pvlib.iotools.read_tmy3      get_meas_filename() 
load stc data          pvlib.pvsystem.retrieve_sam  get_ref()
normalisation          n/a                          meas_to_norm()
model_fitting          e.g. pvusa                   mlfm_fit()
power_prediction       e.g. pvlib.pvsystem.sapm     mlfm()
                       power_pvusa
                       pvlib.pvsystem.singlediode
Loss and degradation   n/a
```

Any thoughts as to this approach?

**Comment by adriesse** [comment]
Sorry, I didn't see the notebook previously as it is not listed as part of the PR. I wonder if it can be made viewable from the browser, like some others are?

It seems to make sense to go with the tutorial approach.  Then the most important thing will be defining the low-level core functions.  Reading your own file format is probably better placed within the tutorial portion, for example.

**Pull request closed without merging**
