### PR TITLE
Update for PySAM 2.0

### PR DESCRIPTION
**Pull request by cwhanse**
- [x] I am familiar with the [contributing guidelines](https://pvlib-python.readthedocs.io/en/latest/contributing.html)
 - [ ] Adds description and name entries in the appropriate "what's new" file in [`docs/sphinx/source/whatsnew`](https://github.com/pvlib/pvlib-python/tree/master/docs/sphinx/source/whatsnew) for all changes. Includes link to the GitHub Issue with `` :issue:`num` `` or this Pull Request with `` :pull:`num` ``. Includes contributor name and/or GitHub username (link with `` :ghuser:`user` ``).
 - [x] New code is fully documented. Includes [numpydoc](https://numpydoc.readthedocs.io/en/latest/format.html) compliant docstrings, examples, and comments where necessary.
 - [x] Pull request is nearly complete and ready for detailed review.
 - [x] Maintainer: Appropriate GitHub Labels and Milestone are assigned to the Pull Request and linked Issue.

PySAM 2.0 is not backward compatible with PySAM 1.2.  Fixes `ivtools.fit_sdm_cec_sam` to work with PySAM 2.0, and sets the requirements to PySAM 2.0 or later.

### CODE REVIEW

**Comment by cwhanse** [comment]
@kanderso-nrel this fixes one test failure in #872

**Comment by CameronTStark** [comment]
@cwhanse just checking in on this PR. It looks ready to merge. Is there any additions you're wanting to include?

**Comment by cwhanse** [comment]
I think it's good to go. After the next PySAM release we should be able to remove the version restriction; I've provided a change to PySAM for this function to be backwards compatible.

**Comment by CameronTStark** [comment]
@cwhanse do you think this should  include a note in "What's New"? It could be useful for future reference.

**Comment by CameronTStark** [comment]
The only errors the CI catches are being addressed in #879. I'll merge now. 

Thanks @cwhanse!

**Pull request merged**
