### PR TITLE
Create CODE_OF_CONDUCT.md

### PR DESCRIPTION
**Pull request by mikofski**
Will, you are the only member of the pvlib org, so I put you as the email. Is that okay?

pvlib python pull request guidelines
====================================

Thank you for your contribution to pvlib python! You may delete all of these instructions except for the list below.

You may submit a pull request with your code at any stage of completion.

The following items must be addressed before the code can be merged. Please don't hesitate to ask for help if you're unsure of how to accomplish any of the items below:

 - [ ] Closes issue #xxxx
 - [ ] I am familiar with the [contributing guidelines](http://pvlib-python.readthedocs.io/en/latest/contributing.html).
 - [ ] Fully tested. Added and/or modified tests to ensure correct behavior for all reasonable inputs. Tests (usually) must pass on the TravisCI and Appveyor testing services.
 - [ ] Updates entries to `docs/sphinx/source/api.rst` for API changes.
 - [ ] Adds description and name entries in the appropriate `docs/sphinx/source/whatsnew` file for all changes.
 - [ ] Code quality and style is sufficient. Passes LGTM and SticklerCI checks.
 - [ ] New code is fully documented. Includes sphinx/numpydoc compliant docstrings and comments in the code where necessary.
 - [ ] Pull request is nearly complete and ready for detailed review.

Brief description of the problem and proposed solution (if not already fully described in the issue linked to above):

### CODE REVIEW

**Comment by wholmgren** [comment]
@mikofski, thanks for the PR. I've long thought that we should add a code of conduct based on the Contributor Covenant but never did it because the reporting/enforcement implications. I am ok with emails going to me, but I am not ok with being the only person that gets the emails. So we should list multiple people or create an organization list (preferred). The emails should go to my arizona.edu address. Note that if/when something is reported, I could be obligated to report it to the university.

**Comment by mikofski** [comment]
You can add me at mikofski@berkeley.edu I'm okay with that.

**Comment by cwhanse** [comment]
You can add me at cwhanse@sandia.gov.

**Comment by mikofski** [comment]
I created a [collaborative inbox](https://support.google.com/a/answer/167430?hl=en) called [pvlib-admin](https://groups.google.com/forum/#!forum/pvlib-admin), part of [Google Groups](https://gsuite.google.com/learning-center/products/groups/get-started/#!/). There's more [help](https://support.google.com/groups#topic=9216).

I think you can maybe add this to the existing "pvlib-python" group, but not sure. I don't even know if this will work, but it seemed to work in some tests I did. Basically any can email the group, which is preconfigured by google groups to be a "collaborative inbox" which they recommend for support type emails. It also comes with a bunch of moderation tools and other settings that I don't understand. So if someone emails the "pvlib-admin" group, then you can click more options next to reply and select "reply privately to author" and it will send an email to their inbox, but only if they are using Gmail. Otherwise, you can view their email address by hovering over their name, or you can respond from your personal inbox directly to them.

image

What I don't understand is how to do this using the pvlib-admin@googlegroups.com email address instead of your own email address. Maybe this isn't an issue? If you are responding to the group, then you can select the option to use the group email, but that wouldn't go to the poster since they are not members of the pvlib-admin group. And if the poster isn't using Gmail, then you have to respond from your personal email anyway?

So this may not be the correct solution. Sorry 😕

**Comment by mikofski** [comment]
@wholmgren or @cwhanse do you know of another way to create an "organization list" other than google groups collaborative inbox? [Googling](https://www.google.com/search?q=share+inbox+for+open+source+software) I found [helpmonk](https://helpmonks.com/opensource) free for open source.

**Comment by wholmgren** [comment]
Thanks for looking into that. That approach seems fine for this purpose given that it should be relatively little email - hopefully none! Some people might try to use it for support and we'll need to steer them back to the other resources. We've set up organization lists using AWS for a custom domain, but we don't need that complexity here.

I'm ok with listing multiple email addresses too. I preferred the list because I thought it was better if more than one person received this kind of email. But I guess that individual addresses could actually be preferable if someone thinks one of the people on the list is causing a problem. I don't know if there's a right answer and I'll leave it up to you.

**Comment by mikofski** [comment]
If y'all want to use the Google groups email, you'll have to join the group, look for an email from "pvlib-admin" to join. otherwise, I'll just list our 3 emails

**Comment by mikofski** [comment]
* updated email address with pvlib-admin googlegroups email
* also added individual emails in case complaint is against one of us
* I'm okay with this now if you all are - any feedback?

**Pull request merged**
