### PR TITLE
Replaced array_like with array-like

### LINKED ISSUE #1392: Change Underscore to Dash in "array_like" for fit_sandia
**Is your feature request related to a problem? Please describe.**

As noted on #765, there is one function called ``fit_sandia`` which seems to have a typo, declaring arguments as ``array_like`` (with an underscore) vs. ``array-like`` (with a dash). As noted by the author of that function, @cwhanse, there is a 99.99% probability that this was just a simple typo.

**Describe the solution you'd like**

Replace the 4 usages of ``array_like`` with ``array-like`` in the function ``fit_sandia``. By doing so, this would normalise all usages of ``array-like`` across the entire project, and would thus support any efforts to solve #765 e.g. without doing this, those four usages might be lost if someone tried a "find all" in order to fix #765.

**Describe alternatives you've considered**

The immediately obvious alternative would be: wait until #765 is figured out. But as per the above - this issue would actually support #765, and anyway, until #765 is figured out, the contributing guidelines still do specify that ``array-like`` (dash) should be used and certainly in this case it should be used because a scalar won't work (as per the discussion on #765).

**Additional context**

See the comment on #765. There are 4 occurrences of ``array_like`` (underscore) in the code vs. 22 occurrences of ``array-like`` (dash).

### PR DESCRIPTION
**Pull request by ColmBhandal**
- [x] Closes #1392
 - [x] I am familiar with the [contributing guidelines](https://pvlib-python.readthedocs.io/en/latest/contributing.html)
 - [x] Pull request is nearly complete and ready for detailed review.
 - [x] Maintainer: Appropriate GitHub Labels and Milestone are assigned to the Pull Request and linked Issue.

### CODE REVIEW

**Comment by ColmBhandal** [comment]
@cwhanse I went ahead and did this PR per our conversation on #765.

**Comment by cwhanse** [comment]
To underscore our commitment to accurate data types in docstrings, I think we need to test this function using `np.array` input type. It is tested currently only with `pd.Series`. @ColmBhandal I'm happy to contribute to this PR if that would help.

**Comment by ColmBhandal** [comment]
@cwhanse Makes sense- the PR is so small that it would at least beef it up a bit anyway. I will attempt to do that over the next few days. If I need help I will ping you. Thanks!

**Comment by ColmBhandal** [comment]
Based on the associated issue, gonna close this as it's been hanging stale for a while.

**Pull request closed without merging**
