### PR TITLE
Fix tiny typo in docs

### PR DESCRIPTION
**Pull request by JackKelly**
A _tiny_ PR! Just fixing a tiny typo in the docs :slightly_smiling_face: 

 - ~~[ ] Closes #xxxx~~
 - [x] I am familiar with the [contributing guidelines](https://pvlib-python.readthedocs.io/en/latest/contributing.html)
 - ~~[ ] Tests added~~
 - ~~[ ] Updates entries in [`docs/sphinx/source/reference`](https://github.com/pvlib/pvlib-python/blob/master/docs/sphinx/source/reference) for API changes.~~
 - [ ] Adds description and name entries in the appropriate "what's new" file in [`docs/sphinx/source/whatsnew`](https://github.com/pvlib/pvlib-python/tree/master/docs/sphinx/source/whatsnew) for all changes. Includes link to the GitHub Issue with `` :issue:`num` `` or this Pull Request with `` :pull:`num` ``. Includes contributor name and/or GitHub username (link with `` :ghuser:`user` ``).
 - ~~[ ] New code is fully documented. Includes [numpydoc](https://numpydoc.readthedocs.io/en/latest/format.html) compliant docstrings, examples, and comments where necessary.~~
 - [x] Pull request is nearly complete and ready for detailed review.
 - [x] Maintainer: Appropriate GitHub Labels and Milestone are assigned to the Pull Request and linked Issue.

### CODE REVIEW

**Review by cwhanse — APPROVED** [review]

**Comment by cwhanse** [comment]
Thanks @JackKelly can you add your name to the contributor list in whatsnew/v0.9.1 ?

**Comment by JackKelly** [comment]
Thanks for approving this pull request :slightly_smiling_face: 

I've just added myself to the list of contributors. Thank you!

**Comment by wholmgren** [comment]
thanks @JackKelly!

**Comment by JackKelly** [comment]
> thanks @JackKelly!

hehe, thank _you_ guys for creating such an awesome library! Sorry this first PR is so meagre. I hope to contribute in a more meaningful way soon :slightly_smiling_face:

**Pull request merged**
