### PR TITLE
PEP8 fixups to solarposition.py and spa.py

### PR DESCRIPTION
**Pull request by alorenzo175**
As requested by @uvchik in #48.

### CODE REVIEW

**Comment by wholmgren** [comment]
@uvchik if this looks good to you then I will merge.

For future reference, my vote is to not worry about trailing whitespace.

**Comment by uvchik** [comment]
Looks good, but between two references must be line break otherwise all references are shown in one line. If you do so you can also keep the 80 character rule. Check the references in : get_solarposition, spa_c, spa_python and get_sun_rise_set_transit.

If you change the following lines:
```python
    References
    ----------
    [1] I. Reda and A. Andreas, Solar position algorithm for solar radiation applications. Solar Energy, vol. 76, no. 5, pp. 577-589, 2004.
    [2] I. Reda and A. Andreas, Corrigendum to Solar position algorithm for solar radiation applications. Solar Energy, vol. 81, no. 6, p. 838, 2007.
    [3] USNO delta T: http://www.usno.navy.mil/USNO/earth-orientation/eo-products/long-term
```

to:
```python
    References
    ----------
    [1] I. Reda and A. Andreas, Solar position algorithm for solar radiation
    applications. Solar Energy, vol. 76, no. 5, pp. 577-589, 2004.

    [2] I. Reda and A. Andreas, Corrigendum to Solar position algorithm for
    solar radiation applications. Solar Energy, vol. 81, no. 6, p. 838, 2007.

    [3] USNO delta T:
    http://www.usno.navy.mil/USNO/earth-orientation/eo-products/long-term
```

the result will change from
```
[1] I. Reda and A. Andreas, Solar position algorithm for solar radiation applications. Solar Energy, vol. 76, no. 5, pp. 577-589, 2004. [2] I. Reda and A. Andreas, Corrigendum to Solar position algorithm for solar radiation applications. Solar Energy, vol. 81, no. 6, p. 838, 2007. [3] USNO delta T: http://www.usno.navy.mil/USNO/earth-orientation/eo-products/long-term
```
to:
```
[1] I. Reda and A. Andreas, Solar position algorithm for solar radiation applications. Solar Energy, vol. 76, no. 5, pp. 577-589, 2004.

[2] I. Reda and A. Andreas, Corrigendum to Solar position algorithm for solar radiation applications. Solar Energy, vol. 81, no. 6, p. 838, 2007.

[3] USNO delta T: http://www.usno.navy.mil/USNO/earth-orientation/eo-products/long-term```


I found some long lines (>79) at 156 and 285.

**Comment by alorenzo175** [comment]
Ok, should be fixed now. I think the remaining pep8 errors should be left alone for readability.

**Comment by uvchik** [comment]
I totally agree. Good work. It's great that the spa algorithm is now integrated in the python code. @wholmgren and @Calama-Consulting I would merge that and add it to 0.1.

**Comment by wholmgren** [comment]
Agreed on all of the above.

**Pull request merged**
