### PR TITLE
Fix port of old-precision-decimal to present-atol in tests

### PR DESCRIPTION
**Pull request by echedey-ls**
- [x] Closes comment https://github.com/pvlib/pvlib-python/pull/2080#issuecomment-2152762811
 - [x] I am familiar with the [contributing guidelines](https://pvlib-python.readthedocs.io/en/latest/contributing.html)
 - ~[ ] Tests added~
 - ~[ ] Updates entries in [`docs/sphinx/source/reference`](https://github.com/pvlib/pvlib-python/blob/main/docs/sphinx/source/reference) for API changes.~
 - ~[ ] Adds description and name entries in the appropriate "what's new" file in [`docs/sphinx/source/whatsnew`](https://github.com/pvlib/pvlib-python/tree/main/docs/sphinx/source/whatsnew) for all changes. Includes link to the GitHub Issue with `` :issue:`num` `` or this Pull Request with `` :pull:`num` ``. Includes contributor name and/or GitHub username (link with `` :ghuser:`user` ``).~
 - ~[ ] New code is fully documented. Includes [numpydoc](https://numpydoc.readthedocs.io/en/latest/format.html) compliant docstrings, examples, and comments where necessary.~
 - [x] Pull request is nearly complete and ready for detailed review.
 - [x] Maintainer: Appropriate GitHub Labels (including `remote-data`) and Milestone are assigned to the Pull Request and linked Issue.

Some tests were using a tolerance higher than expected.

Feel free to find other occurrences with `(assert_allclose)\((.*), ?(.*), ?([a-zA-Z0-9=]*)?(\d)\)`

These are the left integer tolerances:
image
But I have played a bit with some of em and didn't think they are a misunderstood decimal position.

### CODE REVIEW

**Comment by echedey-ls** [comment]
This regex to show that we are talking either about `assert_allclose` or `assert_frame_equal`. Constrains finds to functions that start with `assert_`

`(assert_.*)\((.*), ?(.*), ?([a-zA-Z0-9]=*)?(\d)\)$`

**Comment by IoannisSifnaios** [comment]
@echedey-ls If a test is for irradiance, I think an atol=10 is a reasonable value and should not be changed. #2080 was referring to temperature tests. So maybe we should be cautious not to change all integer tolerances.

**Review by cwhanse — APPROVED** [review]
I'm OK with the `assert_allclose` statements that aren't changing. These statements are in tests of PVSystem methods, where `assert_called_with` is the primary check. The `assert_allclose` statements are only intended to confirm that the results of the method are somewhat as expected.

**Comment by kandersolar** [comment]
Thanks as always for the comprehensive codebase greps @echedey-ls!

**Pull request merged**
