### PR TITLE
Spelling fix on "/pvlib/clearsky.py" documentation

### LINKED ISSUE #2159: Documentation typo
**Describe the bug**
Here is a hard issue to solve. Harder than solving some implementation details of unused models, changing patterns or so. The hardest issue so far. Please, refrain from solving this before we can talk about what shall be done at PVPMC - this issue is reserved for EU PVPMC attendees in case they want to learn about the contribution process.

There is a typo at https://github.com/pvlib/pvlib-python/blob/599c5d97abd6ed8ba2dec92999cc40ee05083fb7/pvlib/clearsky.py#L944C51-L944C63

**Expected behavior**
I'd like to read `implementation` with all the characters, instead of `implentation`.

**Versions:**
 - ``pvlib.__version__``: v0.11.0

**Additional context**
https://pvlib-python.readthedocs.io/en/stable/reference/generated/pvlib.clearsky.bird.html#pvlib.clearsky.bird

> [!WARNING]  
**THIS ISSUE IS RESERVED FOR THE 2024 EU PVPMC Workshop.
PLEASE DO NOT WORK ON THIS ISSUE WITHOUT PRIOR AGREEMENT.**

### PR DESCRIPTION
**Pull request by cardenca**
- [X] Closes #2159
 - [X] I am familiar with the [contributing guidelines](https://pvlib-python.readthedocs.io/en/latest/contributing.html)
 - [x] Adds description and name entries in the appropriate "what's new" file in [`docs/sphinx/source/whatsnew`](https://github.com/pvlib/pvlib-python/tree/main/docs/sphinx/source/whatsnew) for all changes. Includes link to the GitHub Issue with `` :issue:`num` `` or this Pull Request with `` :pull:`num` ``. Includes contributor name and/or GitHub username (link with `` :ghuser:`user` ``).
 - [X] New code is fully documented. Includes [numpydoc](https://numpydoc.readthedocs.io/en/latest/format.html) compliant docstrings, examples, and comments where necessary.
 - [X] Pull request is nearly complete and ready for detailed review.
 - [x] Maintainer: Appropriate GitHub Labels (including `remote-data`) and Milestone are assigned to the Pull Request and linked Issue.

### CODE REVIEW

**Comment by kandersolar** [comment]
@cardenca thanks for the PR!  Can you push a new commit to this PR to add yourself to the list of contributors in the v0.11.1 file in https://github.com/pvlib/pvlib-python/tree/main/docs/sphinx/source/whatsnew?

**Comment by cardenca** [comment]
@kandersolar I'm sorry for the delay. I already pushed the changes! thanks.

**Comment by kandersolar** [comment]
@cardenca it looks like you made the changes in a new PR (#2197) instead of updating this one.  It is better to make all related changes in a single PR.  Can you please redo the "what's new" edit in the branch for this PR (it is called `iss2159`), and close #2197?

Thank you!

**Comment by cardenca** [comment]
@kandersolar now I think I did it well, thank you for the correction!

**Review by kandersolar — APPROVED** [review]
Thanks @cardenca!  Hopefully we see more PRs from you in the future :)

**Pull request merged**
