### PR TITLE
add v0.6.1 whatsnew and update zenodo badge

### PR DESCRIPTION
**Pull request by wholmgren**
Adds a new whatsnew file for v0.6.1 and updates the zenodo badge to point to 0.6.0

 - [x] Pull request is nearly complete and ready for detailed review.

Builds ok locally so will go ahead and merge.

### CODE REVIEW

**Comment by mikofski** [comment]
Just curious, why did you create this PR? did you expect comments? Why not just make this commit straight in master?

**Comment by wholmgren** [comment]
The main reason I went through the PR is so that people can view the changes in the same github PR interface that most things go through. Sometimes I catch problems seeing the diff here (in addition to viewing the diff locally). I did not expect comments. I'm not sure what the right approach is for changes like this. I always feel bad pushing directly to pvlib/master. Your thoughts?

**Comment by mikofski** [comment]
>The main reason I went through the PR is so that people can view the changes in the same github PR interface that most things go through. Sometimes I catch problems seeing the diff here (in addition to viewing the diff locally).

That makes a lot of sense to me, thanks!

>I always feel bad pushing directly to pvlib/master. Your thoughts?

IMO it's okay for the maintainer/owner/bdfl to make changes directly in master, especially small routine ones like these, I think the only foul is forcefully rewriting master (or any branch) without discussion.

**Comment by cwhanse** [comment]
I prefer to see a PR, even for these housekeeping tasks, because it helps all of us stay aware of the repository status and the work required to maintain it.

**Comment by mikofski** [comment]
Also you could make an issue and then close it with your commit message, like `closes #999`, then the issue could also serve as a discussing point too.

**Pull request merged**
