### PR TITLE
'closed' parameter in Pandas Dataframe deprecated, changed to inclusive

### PR DESCRIPTION
**Pull request by joaoguilhermeS**
- [x] Closes #xxxx
 - [x] I am familiar with the [contributing guidelines](https://pvlib-python.readthedocs.io/en/latest/contributing.html)
 - [x] Tests added
 - [x] Updates entries in [`docs/sphinx/source/reference`](https://github.com/pvlib/pvlib-python/blob/master/docs/sphinx/source/reference) for API changes.
 - [x] Adds description and name entries in the appropriate "what's new" file in [`docs/sphinx/source/whatsnew`](https://github.com/pvlib/pvlib-python/tree/master/docs/sphinx/source/whatsnew) for all changes. Includes link to the GitHub Issue with `` :issue:`num` `` or this Pull Request with `` :pull:`num` ``. Includes contributor name and/or GitHub username (link with `` :ghuser:`user` ``).
 - [x] New code is fully documented. Includes [numpydoc](https://numpydoc.readthedocs.io/en/latest/format.html) compliant docstrings, examples, and comments where necessary.
 - [x] Pull request is nearly complete and ready for detailed review.
 - [x] Maintainer: Appropriate GitHub Labels (including `remote-data`) and Milestone are assigned to the Pull Request and linked Issue.

### CODE REVIEW

**Comment by joaoguilhermeS** [comment]
'closed' parameter in Pandas Dataframe deprecated, changed to 'inclusive'

**Comment by cwhanse** [comment]
It appears that the `'closed'` kwarg is deprecated for pandas >= 1.4.0. We still support python 3.7 with pandas=0.25. Rather than introduce complexity into the example to silence the deprecation warning, I think we can live with it for now.

**Comment by cwhanse** [comment]
Maybe instead of changing from `closed` to `inclusive`, we could future-proof and simply drop `closed`. I think the example would achieve its purpose. @kanderso-nrel your thoughts?

**Comment by kanderso-nrel** [comment]
No objection from me to dropping `closed` in any or all of those pages.  I probably included it in these pages out of habit, not because it is specifically desirable in any of these cases. 

Note that there are three examples that use `closed`, so might as well remove it in all of them (see `$ git grep closed docs/examples`):
- `solar-position/plot_sunpath_diagrams.py`
- `solar-tracking/plot_single_axis_tracking.py`
- `solar-tracking/plot_single_axis_tracking_on_sloped_terrain.py`

@joaoguilhermeS you can make a note of the change and add yourself to the contributors list in `docs/sphinx/source/whatsnew/v0.9.3.rst` if you like!

**Comment by joaoguilhermeS** [comment]
thank you for fixing it!

**Pull request closed without merging**
