### PR TITLE
Fancy "view on github" links in documentation

### PR DESCRIPTION
**Pull request by kanderso-nrel**
- [x] I am familiar with the [contributing guidelines](https://pvlib-python.readthedocs.io/en/latest/contributing.html)
 - [ ] Tests added
 - [ ] Adds description and name entries in the appropriate "what's new" file in [`docs/sphinx/source/whatsnew`](https://github.com/pvlib/pvlib-python/tree/master/docs/sphinx/source/whatsnew) for all changes. Includes link to the GitHub Issue with `` :issue:`num` `` or this Pull Request with `` :pull:`num` ``. Includes contributor name and/or GitHub username (link with `` :ghuser:`user` ``).
 - [ ] Pull request is nearly complete and ready for detailed review.
 - [ ] Maintainer: Appropriate GitHub Labels and Milestone are assigned to the Pull Request and linked Issue.

Cliff [pointed out](https://github.com/pvlib/pvlib-python/pull/905#pullrequestreview-363104166) that the "Edit on Github" links don't work on autogenerated pages (gallery examples, API pages).  This PR overrides how those links are generated to do custom URLs for the autogenerated pages so that they actually go somewhere useful.  

Test cases:
- Normal RST page: [package_overview](https://pvlib-python--913.org.readthedocs.build/en/913/package_overview.html)
- RST page, not in the source directory: [gallery's README.rst](https://pvlib-python--913.org.readthedocs.build/en/913/auto_examples/index.html)
- Gallery page: [SAT example](https://pvlib-python--913.org.readthedocs.build/en/913/auto_examples/plot_single_axis_tracking.html)
- API page (simple): [clearsky.bird](https://pvlib-python--913.org.readthedocs.build/en/913/generated/pvlib.clearsky.bird.html)
- API page (complex): [iotools.read_midc](https://pvlib-python--913.org.readthedocs.build/en/913/generated/pvlib.iotools.read_midc.html)

### CODE REVIEW

**Comment by kanderso-nrel** [comment]
> My only concern is that it seems like a lot of custom code to maintain

Yep, I don't really like all this custom stuff either.  I haven't been vocal on this PR because I was hoping a better method would pop up, but I haven't found one. 

> Any idea on if this is compatible with the newer versions of sphinx/rtd-theme that you've been testing with? Even better would be if it's not even needed or fixed upstream.

This approach does still work with `sphinx==2.4.3` and we're already using the most recent version of `sphinx_rtd_theme`.  Agreed it would be way better for this to work upstream, but I think getting GH links to work out of the box would require changes at the extension level as well as in sphinx itself -- for instance sphinx can't know where a gallery example came from unless sphinx-gallery records it somehow.  And the same for the API reference pages, etc.  

I've just pushed an update to move URL-building logic out of the template and into conf.py to hopefully make the code a little more maintainable.  At this point I think I'm done with it, but happy to make changes if there are any suggestions.

**Comment by wholmgren** [comment]
@CameronTStark @cwhanse any objection to moving forward with this?

**Comment by cwhanse** [comment]
OK by me

**Comment by CameronTStark** [comment]
No objection here.

**Comment by wholmgren** [comment]
@kanderso-nrel thanks!

**Pull request merged**
