### PR TITLE
Appease a few test warnings

### PR DESCRIPTION
**Pull request by kanderso-nrel**
- [x] Pull request is nearly complete and ready for detailed review.
 - [x] Maintainer: Appropriate GitHub Labels (including `remote-data`) and Milestone are assigned to the Pull Request and linked Issue.

This PR gets rid of a few warnings emitted by our CI test jobs:

- ```PytestReturnNotNoneWarning: Expected None, but pvlib/tests/test_atmosphere.py::test_kasten96_lt returned array([[[...]]]), which will be an error in a future version of pytest.  Did you mean to use `assert` instead of `return`?` ```
- ```test_solarposition.py:166: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.```
- ```Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: codecov/codecov-action@v2. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.```

### CODE REVIEW

**Review by AdamRJensen — APPROVED** [review]
LGTM :)

**Comment by mikofski** [comment]
Thanks @kanderso-nrel does it deserve a "what's new" note?

**Comment by kanderso-nrel** [comment]
I always ask myself "can I imagine a user reading an entry on this and being glad it was included in the "what's new" file?" and in this case I lean towards "no" and it would just be uninteresting clutter.  Of course if anyone else thinks a note is warranted I will happily add one.

**Comment by kanderso-nrel** [comment]
Yep, see https://github.com/pvlib/pvlib-python/issues/1591#issuecomment-1396344014

**Comment by mikofski** [comment]
It's only psm3 in the pytest-remote-data action action:
image

**Pull request merged**
