### PR TITLE
update whats new for #844 and other contributors

### PR DESCRIPTION
**Pull request by wholmgren**
Adds a whats new note for #844. Also adds reviewers of merged PRs.

@cwhanse I could make a 0.7.1 release today. If you agree that's worthwhile, I'll update the release date in this PR and delte the API changes section. Or you/@CameronTStark can make a release. It's not clear to me how long it will take to get the big PRs reviewed and merged, so I suggest pushing those to 0.7.2 or 0.8.0 (depending on our willingness to make breaking changes in the meantime).

### CODE REVIEW

**Comment by mikofski** [comment]
part of the [docstring for `read_epw`](https://external-builds.readthedocs.io/html/pvlib-python/851/generated/pvlib.iotools.read_epw.html) is not rendering correctly, sorry. 😕

**Comment by cwhanse** [comment]
> Adds a whats new note for #844. Also adds reviewers of merged PRs.
> @cwhanse I could make a 0.7.1 release today. If you agree that's worthwhile, I'll update the release date in this PR and delte the API changes section. Or you/@CameronTStark can make a release. It's not clear to me how long it will take to get the big PRs reviewed and merged, so I suggest pushing those to 0.7.2 or 0.8.0 (depending on our willingness to make breaking changes in the meantime).

I'd say go ahead with v0.7.1. #708 is nearly ready for review but the reviews could take a while. I haven't started a review of #823. I think all of the issues labeled 0.7.1 can be pushed ahead.

**Comment by kanderso-nrel** [comment]
> part of the docstring for read_epw is not rendering correctly

Looks like that was actually introduced in 0.7.0: https://pvlib-python.readthedocs.io/en/v0.7.0/generated/pvlib.iotools.read_epw.html

Maybe by the `#noqa` flag here?  https://github.com/pvlib/pvlib-python/blame/master/pvlib/iotools/epw.py#L71

**Comment by mikofski** [comment]
let me try something, a different type of table that will fit the line size restriction
https://docutils.sourceforge.io/docs/user/rst/quickref.html#tables

**Comment by wholmgren** [comment]
@mikofski you can put the noqa comment at the end of the whole docstring

**Comment by wholmgren** [comment]
I went ahead and moved the comment. Looks good now.

**Comment by wholmgren** [comment]
Ready to merge and release.

**Comment by mikofski** [comment]
looks good, the alternate approach #852 also seems to work - your choice - an advantage of the grid table is that although much longer, it does read easier - I just wish there was an easier way to format it.

**Comment by mikofski** [comment]
Oh and I found a few typos in the original table:
mintues -> minutes
Relatitudeive -> Relative
phenonema -> phenomena

**Comment by wholmgren** [comment]
ok to merge and release @cwhanse?

**Pull request merged**
