### PR TITLE
Finalize v0.9.0

### LINKED ISSUE #1214: pvlib v0.9 release planning
We've got a lot of new capability pending, and should move to formalize a release. @wholmgren @mikofski @kevinsa5 @wfvining  I am willing to manage v0.9 release. Here's the checklists. Please indicate what is needed to close a PR, or if you are willing to close any of the identified issues, or recommend deferring.

PRs to merge or defer: 

- [x] #1213 merged
- [x] #1211 
- [x] #1196 
- [x] #1191 
- [ ] #717 @mikofski I'm guessing the infinite sheds PR will be deferred?

Issues to close or defer:

- [x] #1188  will close with #1218 
- [x] #1185
- [x] #1184 PR #1231
- [x] #1148  PR #1224
- [x] #1126  PR #1233
- [x] #1118 PR #1222
- [x] #1115 PR #1223 
- [ ] #1113 
- [x] #1109 
- [ ] #1069 
- [ ] #964 suggest deferring
- [ ] #958 suggest deferring
- [x] #954 deferred 
- [x] #949 PR #1225 
- [ ] #825 recommend deferring
- [ ] #483 recommend deferring
- [ ] #436 maybe this can be closed, we've accomplished a substantial part of the scope
- [ ] #418 recommend deferring
- [ ] #329 perennial can to be kicked down the development road

### PR DESCRIPTION
**Pull request by kanderso-nrel**
- [x] Closes #1214
 - [x] I am familiar with the [contributing guidelines](https://pvlib-python.readthedocs.io/en/latest/contributing.html)
 - [x] Adds description and name entries in the appropriate "what's new" file in [`docs/sphinx/source/whatsnew`](https://github.com/pvlib/pvlib-python/tree/master/docs/sphinx/source/whatsnew) for all changes. Includes link to the GitHub Issue with `` :issue:`num` `` or this Pull Request with `` :pull:`num` ``. Includes contributor name and/or GitHub username (link with `` :ghuser:`user` ``).
 - [x] Pull request is nearly complete and ready for detailed review.
 - [x] Maintainer: Appropriate GitHub Labels and Milestone are assigned to the Pull Request and linked Issue.

### CODE REVIEW

**Review by wholmgren — APPROVED** [review]

**Review by cwhanse — APPROVED** [review]

**Comment by mikofski** [comment]
`read_epw_remote` test is failing
https://dev.azure.com/solararbiter/pvlib%20python/_build/results?buildId=5483&view=ms.vss-test-web.build-test-results-tab&runId=121394&resultId=100917&paneView=debug

**Comment by mikofski** [comment]
new links are:
`https://energyplus-weather.s3.amazonaws.com/europe_wmo_region_6/NLD/NLD_Amsterdam.062400_IWEC/NLD_Amsterdam.062400_IWEC.epw`

they moved from ghpages to AWS s3:
https://energyplus-weather.s3.amazonaws.com/europe_wmo_region_6/NLD/NLD_Amsterdam.062400_IWEC/NLD_Amsterdam.062400_IWEC.epw

**Comment by kanderso-nrel** [comment]
Ok @mikofski's url works, someone else merge this if they're good with that change

**Comment by wholmgren** [comment]
Kevin do you want to tag too?

**Comment by mikofski** [comment]
Shall I send out announcements? Unfortunately too late for NF August newsletter, but I'll let them know for September. Let me know if there's anything from the release notes that you want me to highlight.

**Comment by mikofski** [comment]
I'll do announcements a little later today. Thanks Kevin, Will, Cliff, Adam, Anton, and everyone who contributed new and previously :)

**Pull request merged**
