### PR TITLE
changed unix file modes, so that the files are not executable

### PR DESCRIPTION
**Pull request by bmu**
For some of the original files (I created a new clone to double check this), the unix file modes were set to 755, which means that they are executable (see #11).
I think, it should be save to merge this (however I am not 100% sure).
Maybe the best is to wait for travis and to test this on another linux machine. 
Any others, that work on linux?

### CODE REVIEW

**Comment by bmu** [comment]
Ok, it fails, but the reason is a failure in `test_tools`. I'll create another pull request to fix this.

**Comment by bmu** [comment]
Something is going wrong here: `test_tools.py` seems to be outdated and is not tested on the other pull requests, but is tested on the one, that I submitted! 

Any ideas?

**Comment by wholmgren** [comment]
Good catches. I apparently missed updating ``test_tools.py`` on UARENForecasting/PVLIB_Python and I never noticed because nose didn't run the tests automatically due to the permissions issue. 

Looks like everything in ``test_tools.py`` is for the old vars/expect pattern, so it will just be a stub when you remove all of that. This is fine with me for ``0.1``, but we should probably add some tests for ``0.2``.

**Comment by bmu** [comment]
Ok, so I think I should remove the file. Ok?

**Comment by wholmgren** [comment]
Yes, we can add it back later if tools expands.

**Comment by bmu** [comment]
this should be ready to merge from my side.

**Comment by wholmgren** [comment]
Great, merged.

**Pull request merged**
