### PR TITLE
Correct return docstrings 

### LINKED ISSUE #1234: Incorrect Returns docstrings for PVSystem.get_irradiance and Array.get_irradiance
`PVSystem.get_irradiance` and `Array.get_irradiance` both wrap `irradiance.get_total_irradiance`. `irradiance.get_total_irradiance` returns a OrderedDict/DataFrame with keys/columns ``'poa_global', 'poa_direct', 'poa_diffuse', 'poa_sky_diffuse', 'poa_ground_diffuse'``.  Descriptions at [this ](https://github.com/pvlib/pvlib-python/blob/310d191d141a0fb187f4177a4688b16b0ded001b/pvlib/pvsystem.py#L334)line and [this](https://github.com/pvlib/pvlib-python/blob/310d191d141a0fb187f4177a4688b16b0ded001b/pvlib/pvsystem.py#L1374) line are incorrect.

### PR DESCRIPTION
**Pull request by rockstaedt**
- [x] Closes #1234
 - [x] I am familiar with the [contributing guidelines](https://pvlib-python.readthedocs.io/en/latest/contributing.html)
 ~~- [ ] Tests added~~
 ~~- [ ] Updates entries to [`docs/sphinx/source/api.rst`](https://github.com/pvlib/pvlib-python/blob/master/docs/sphinx/source/api.rst) for API changes.~~
 ~~- [ ] Adds description and name entries in the appropriate "what's new" file in [`docs/sphinx/source/whatsnew`](https://github.com/pvlib/pvlib-python/tree/master/docs/sphinx/source/whatsnew) for all changes. Includes link to the GitHub Issue with `` :issue:`num` `` or this Pull Request with `` :pull:`num` ``. Includes contributor name and/or GitHub username (link with `` :ghuser:`user` ``).~~
 ~~- [ ] New code is fully documented. Includes [numpydoc](https://numpydoc.readthedocs.io/en/latest/format.html) compliant docstrings, examples, and comments where necessary.~~
 ~~- [ ] Pull request is nearly complete and ready for detailed review.~~
 - [x] Maintainer: Appropriate GitHub Labels and Milestone are assigned to the Pull Request and linked Issue.

Column names were added as described in the issue.

### CODE REVIEW

**Comment by cwhanse** [comment]
Thanks @rockstaedt .  I don't think the other checklist items require any action.

**Review by cwhanse — APPROVED** [review]

**Comment by rockstaedt** [comment]
Okay cool 👍🏼 I wasn't sure since it was my first pull request. Should I delete them then? @cwhanse

**Comment by cwhanse** [comment]
You can delete them, or mark them with strikethrough by putting ~~ at the beginning and end.

**Review by wholmgren — APPROVED** [review]
Thanks @rockstaedt!

**Pull request merged**
