### PR TITLE
finalize whatsnew v0.6.0

### PR DESCRIPTION
**Pull request by wholmgren**
See here for rendered whatsnew documentation: https://wholmgren-pvlib-python-new.readthedocs.io/en/latest/whatsnew.html

I will make the 0.6.0 tag as soon as this is merged.

### CODE REVIEW

**Comment by mikofski** [comment]
nits: there are several texts in the what's new that should probably be formatted as code or linked using Sphinx markup

**Comment by mikofski** [comment]
another nit: IMO we should be consistent in tag names, always using **v** prefix for versions, even in what's new, eg: "v0.7", not just "0.7"

**Comment by mikofski** [comment]
sorry, I would like to do more, but here's the start of a patch, there's still more ...

```patch
--- a/whatsnew_0600.rst
+++ b/whatsnew_0600.rst
@@ -17,31 +17,31 @@
   that can calculate a quantity using multiple algorithms now start
   with the prefix ``get_``. For example, ``relativeairmass`` can calculate
   airmass using one of many ``model`` arguments. Its name has been changed
-  to ``get_relative_airmass``. The old function names remain in this
+  to :func:`~pvlib.atmosphere.get_relative_airmass`. The old function names remain in this
   release, but will emit a ``PVLibDeprecationWarning`` when called. The
-  old functions will be removed in the 0.7 release. Functions composed
+  old functions will be removed in the v0.7 release. Functions composed
   of multiple words jammed together have been renamed with underscores
   separating the words (see above).
   Each change is detailed below. (:issue:`427`)
-* Deprecated relativeairmass. relativeairmass will be removed in 0.7.
-  Use the new get_relative_airmass instead. (:issue:`427`)
-* Deprecated absoluteairmass. absoluteairmass will be removed in 0.7.
-  Use the new get_absolute_airmass instead. (:issue:`427`)
-* Deprecated irradiance.globalinplane. globalinplane will be removed in 0.7.
-  Use the new irradiance.poa_components instead. (:issue:`427`)
-* Added irradiance.poa_components. Function is the same as the now-deprecated
-  irradiance.globalinplane, but adds 'poa_sky_diffuse' and
-  'poa_ground_diffuse' to the output. (:issue:`427`)
-* Deprecated irradiance.extraradiation. Use irradiance.get_extra_radiation
-  instead. irradiance.extraradiation will be removed in 0.7. (:issue:`427`)
-* Deprecated irradiance.grounddiffuse. Use irradiance.get_ground_diffuse
-  instead. irradiance.grounddiffuse will be removed in 0.7. (:issue:`427`)
-* Added irradiance.get_poa_sky_diffuse. (:issue:`427`)
-* Deprecated irradiance.total_irrad. Use irradiance.get_total_poa_irradiance
-  instead. irradiance.total_irrad will be removed in 0.7. (:issue:`427`)
-* Removed 'klutcher' from get_sky_diffuse/total_irrad. This misspelling was
+* Deprecated ``relativeairmass``; it will be removed in v0.7.
+  Use the new :func:`~pvlib.atmosphere.get_relative_airmass` instead. (:issue:`427`)
+* Deprecated ``absoluteairmass``; it will be removed in v0.7.
+  Use the new :func:`~pvlib.atmosphere.get_absolute_airmass` instead. (:issue:`427`)
+* Deprecated ``irradiance.globalinplane``; it will be removed in v0.7.
+  Use the new :func:`~pvlib.irradiance.poa_components` instead. (:issue:`427`)
+* Added :func:`~pvlib.irradiance.poa_components`. Function is the same as the now-deprecated
+  ``irradiance.globalinplane``, but adds ``'poa_sky_diffuse'`` and
+  ``'poa_ground_diffuse'`` to the output. (:issue:`427`)
+* Deprecated ``irradiance.extraradiation``; it will be removed in v0.7.
+  Use :func:`pvlib.irradiance.get_extra_radiation` instead. (:issue:`427`)
+* Deprecated ``irradiance.grounddiffuse``; it will be removed in v0.7. Use
+  :func:`~pvlib.irradiance.get_ground_diffuse` instead. (:issue:`427`)
+* Added :func:`~pvlib.irradiance.get_poa_sky_diffuse`. (:issue:`427`)
+* Deprecated ``irradiance.total_irrad``; it will be removed in v0.7. Use
+  :func:`~pvlib.irradiance.get_total_poa_irradiance` instead. (:issue:`427`)
+* Removed ``'klutcher'`` from ``get_sky_diffuse``/``total_irrad``. This misspelling was
   deprecated long ago but never removed. (:issue:`97`)
-* pvsystem.calcparams_desoto now requires arguments for each module model
+* :func:`~pvlib.pvsystem.calcparams_desoto` now requires arguments for each module model
   parameter. (:issue:`462`)
 * Add losses_parameters attribute to PVSystem objects and remove the kwargs
   support from PVSystem.pvwatts_losses. Enables custom losses specification

```

**Comment by mikofski** [comment]
@wholmgren you also added codecov ci too, maybe add that to the end of the [Testing section](https://wholmgren-pvlib-python-new.readthedocs.io/en/latest/whatsnew.html#testing) after SticklerCI ?

**Comment by wholmgren** [comment]
@mikofski thanks! can you make a pull request to my fork?

**Comment by wholmgren** [comment]
> there are several texts in the what's new that should probably be formatted as code or linked using Sphinx markup

this is more work than I've usually cared to put into it. For reference, pandas is good about formatting names as something other than regular text, but does not always link to the function.

**Comment by cwhanse** [comment]
@mikofski thanks for showing how the markup can be done.  I haven't gotten very far figuring this out, I try to imitate what others have submitted.

**Comment by wholmgren** [comment]
We should make the contributors list in the release notes be consistent with all of ways that we say that people can contribute it to pvlib in our documentation: 

https://pvlib-python.readthedocs.io/en/latest/contributing.html

So, I went through many of the closed issues/pull requests tagged with 0.6.0 to find who created the issue or commented on it. I've added the following people to the 0.6.0 contributors list:

@adriesse @cedricleroy @thunderfish24 @jforbess @jdnewmil @josricha @anomam @grisaitis @kdebrab @tadatoshi

Here's the new rendered list: https://wholmgren-pvlib-python-new.readthedocs.io/en/latest/whatsnew.html#contributors

I apologize if I missed anyone -- if so please comment now! We can also amend this version's notes after it's released.

Thanks @adriesse for catching this.

**Comment by thunderfish24** [comment]
You all have done a ton of work for this release. Nice! I hope I can catch up at some point.

**Pull request merged**
