### PR TITLE
Create forecast tools, add ARIMA model

### PR DESCRIPTION
**Pull request by cwhanse**
pvlib python pull request guidelines
====================================

Thank you for your contribution to pvlib python! You may delete all of these instructions except for the list below.

You may submit a pull request with your code at any stage of completion.

The following items must be addressed before the code can be merged. Please don't hesitate to ask for help if you're unsure of how to accomplish any of the items below:

 - [ ] Closes issue #xxxx
 - [x] I am familiar with the [contributing guidelines](http://pvlib-python.readthedocs.io/en/latest/contributing.html).
 - [ ] Fully tested. Added and/or modified tests to ensure correct behavior for all reasonable inputs. Tests (usually) must pass on the TravisCI and Appveyor testing services.
 - [ ] Updates entries to `docs/sphinx/source/api.rst` for API changes.
 - [ ] Adds description and name entries in the appropriate `docs/sphinx/source/whatsnew` file for all changes.
 - [ ] Code quality and style is sufficient. Passes ``git diff upstream/master -u -- "*.py" | flake8 --diff``
 - [ ] New code is fully documented. Includes sphinx/numpydoc compliant docstrings and comments in the code where necessary.
 - [ ] Pull request is nearly complete and ready for detailed review.

Brief description of the problem and proposed solution (if not already fully described in the issue linked to above):

Pushing code to perform short-time forecasts using an ARIMA model, for discussion of how this capability might be added to pvlib.

### CODE REVIEW

**Comment by mikofski** [comment]
Thanks! I noticed a few places it says "ARMA" instead of "ARIMA", is this intentional? Are you referring to auto-regressive integrated moving average? Super cool! I won't pretend I understand the algorithms, but I'm reading a paper that uses ARIMA to predict degradation.

**Comment by cwhanse** [comment]
ARMA vs. ARIMA - me being lazy.  I'll change it to `ARIMA` throughout.  SARIMAX is Seasonal Autoregressive Integrated Moving Average eXogenous, which can be done with the same function in statsmodels.  There's reason to think adding seasonal terms (e.g., a 24 hour lag) is appropriate for solar forecasting.  Exogenous inputs are predictors that are not the output being forecast by the ARIMA model, and I don't quite understand how to use them with this function. One challenge is that the SARIMAX function is coded in terms of lags, not timesteps, so to use seasonal terms we'd need to write some additional methods to calculate the lag in terms of the forecast timestep.

My application is short-term, e.g., 1 hour ahead, forecasting of power when the system metadata is not known with confidence.  For what I'm doing, ARIMA is OK.

**Comment by wholmgren** [comment]
@cwhanse I think stickler and code-cov will behave better if you merge the latest pvlib/master into your branch.

**Comment by wholmgren** [comment]
People interested in this PR should see `[solarforecastarbiter-core](https://github.com/SolarArbiter/solarforecastarbiter-core)` for careful implementations of persistence forecasts, and consider adding ARMA forecasts there.

**Pull request closed without merging**
