### PR TITLE
Allow read_surfrad to parse http files

### PR DESCRIPTION
**Pull request by AdamRJensen**
- [x] I am familiar with the [contributing guidelines](https://pvlib-python.readthedocs.io/en/latest/contributing.html)
 - [x] Tests added
 - ~~[ ] Updates entries in [`docs/sphinx/source/reference`](https://github.com/pvlib/pvlib-python/blob/master/docs/sphinx/source/reference) for API changes.~~
 - [x] Adds description and name entries in the appropriate "what's new" file in [`docs/sphinx/source/whatsnew`](https://github.com/pvlib/pvlib-python/tree/master/docs/sphinx/source/whatsnew) for all changes. Includes link to the GitHub Issue with `` :issue:`num` `` or this Pull Request with `` :pull:`num` ``. Includes contributor name and/or GitHub username (link with `` :ghuser:`user` ``).
 - [x] New code is fully documented. Includes [numpydoc](https://numpydoc.readthedocs.io/en/latest/format.html) compliant docstrings, examples, and comments where necessary.
 - [x] Pull request is nearly complete and ready for detailed review.
 - [x] Maintainer: Appropriate GitHub Labels and Milestone are assigned to the Pull Request and linked Issue.

A [StackOverflow user pointed out](https://stackoverflow.com/q/72283334/8558146) that the SUFRAD files are not only accessible from the FTP server but also via [HTTPS links](https://gml.noaa.gov/aftp/data/radiation/surfrad/Boulder_CO/2020/). This PR updates the ``read_surfrad`` function to allow for parsing remote HTTP files.

### CODE REVIEW

**Comment by AdamRJensen** [comment]
@kanderso-nrel Is a whatsnew entry needed?

**Comment by kanderso-nrel** [comment]
> @kanderso-nrel Is a whatsnew entry needed?

I can imagine a user being interested in this change, so I'd vote yes to a whatsnew entry :)

**Review by kanderso-nrel — APPROVED** [review]
Does NOAA document somewhere that the HTTP files are identical to the FTP files?  The READMEs in the HTTP index only mention the FTP locations: https://gml.noaa.gov/aftp/data/radiation/surfrad/Penn_State_PA/README

I'm also curious why the HTTP index seems to have two directories for each station (e.g. both `fpk` and `Fort_Peck_MT`).

**Comment by AdamRJensen** [comment]
Here's the response I got from Chris Cornwall from NOAA in regards to the reason for the SURFRAD files being available on both the FTP server and the new HTTP index:

> HTTP access to our FTP data was set up a couple years ago because more and more web browsers ended support for the FTP protocol, in the interest of security. As you noticed, the same data are available on our [aftp.cmdl.noaa.gov](http://aftp.cmdl.noaa.gov/) server as through the web link https://gml.noaa.gov/aftp/data/radiation/surfrad/
> The reason for duplicate directories for the SURFRAD permanent locations is for backward compatibility to the old FTP data directory structure. The 3-letter site abbreviations are actually symbolic links on the server, pointing to their longer-named counterparts: dra -> Desert_Rock_NV, for example.

**Review by wholmgren — APPROVED** [review]
any reason this is still sitting here?

**Comment by AdamRJensen** [comment]
> any reason this is still sitting here?

I think it was just needing a second review. Feel free to merge.

**Comment by kanderso-nrel** [comment]
Thanks @AdamRJensen!

**Pull request merged**
