### PR TITLE
Add minus sign in front of dEgdT, `sdm.py`

### LINKED ISSUE #2321: `pvlib.ivtools.sdm.fit_desoto_sandia` has incorrect sign for returned `dEgdT`
`fit_desoto_sandia` incorrectly returns `+0.0002677` instead of `-0.0002677` for `dEgdT`:

https://github.com/pvlib/pvlib-python/blob/891778cc9ceb11e159991d08a6d6cb2d09661bdf/pvlib/ivtools/sdm.py#L874-L886

That value is used both for the returned value and in the equations that compute other SDM parameters.  I've not inspected the math to see whether the sign should be fixed in both places, or only for the returned value.

Noticed in #2315.

### PR DESCRIPTION
**Pull request by echedey-ls**
- [x] Closes #2321
 - [x] I am familiar with the [contributing guidelines](https://pvlib-python.readthedocs.io/en/latest/contributing/index.html)
 - [x] Tests added
 - ~[ ] Updates entries in [`docs/sphinx/source/reference`](https://github.com/pvlib/pvlib-python/blob/main/docs/sphinx/source/reference) for API changes.~
 - [x] Adds description and name entries in the appropriate "what's new" file in [`docs/sphinx/source/whatsnew`](https://github.com/pvlib/pvlib-python/tree/main/docs/sphinx/source/whatsnew) for all changes. Includes link to the GitHub Issue with `` :issue:`num` `` or this Pull Request with `` :pull:`num` ``. Includes contributor name and/or GitHub username (link with `` :ghuser:`user` ``).
 - [x] New code is fully documented. Includes [numpydoc](https://numpydoc.readthedocs.io/en/latest/format.html) compliant docstrings, examples, and comments where necessary.
 - [x] Pull request is nearly complete and ready for detailed review.
 - [x] Maintainer: Appropriate GitHub Labels (including `remote-data`) and Milestone are assigned to the Pull Request and linked Issue.

Fixes the typo in line 874 of `sdm.py`, where `dEgdT = -0.0002677` instead of the same without the minus sign.

Inspired by today's AdventOfCode, I've regexed if this typo is everywhere else and I can confirm it isn't. Regex: `(?<!-)0.0002677`

Tests are passing locally. @cwhanse , should I create a test with a hella lot of precision to test this?

### CODE REVIEW

**Comment by RDaxini** [comment]
> it confirms the error is inconsequential, for practical purposes.

This surprises me. I haven't looked in detail yet how the tests are constructed but, a simple example:
```
import pandas as pd
from pvlib.pvsystem import calcparams_desoto, singlediode

ee = pd.Series([500, 800, 1000])
tc = pd.Series([40, 50, 60])
alphasc = 0.0004
aref = 1
ilref = 5
ioref = 1e-10
rshref = 2e3
rs = 1
egref = 1.1
degdt_pos = 0.0002677
degdt_neg = -0.0002677

sde_param1 = calcparams_desoto(ee, tc, alphasc, aref, ilref, ioref, rshref, rs,
                               egref, degdt_pos)
sde_param2 = calcparams_desoto(ee, tc, alphasc, aref, ilref, ioref, rshref, rs,
                               egref, degdt_neg)

output1 = singlediode(sde_param1[0], sde_param1[1], sde_param1[2],
                      sde_param1[3], sde_param1[4])
output2 = singlediode(sde_param2[0], sde_param2[1], sde_param2[2],
                      sde_param2[3], sde_param2[4])
```
returns different values between `output1` and `output2`. Have I done something incorrectly here?

**Comment by cwhanse** [comment]
The error affects `ivtools.sdm.fit_desoto_sandia`, not `pvsystem.calcparams_desoto` and `singlediode`. 

The tests for `fit_desot_sandia` have a coarse tolerance, which could have been set because of this error. https://github.com/pvlib/pvlib-python/blob/6af80da35a7c96059c534ee38be9123bcfc7f50f/pvlib/tests/ivtools/test_sdm.py#L141

**Comment by echedey-ls** [comment]
> The tests for `fit_desoto_sandia` have a coarse tolerance, which could have been set because of this error. 

At first I thought similar, but I decided to test it and it does not seem to change anything noticeable.

My test strategy has been:
1. Switch between +/- dEgdT
2. Run the tests without the tolerance, which made them fail
3. Re-run the tests and breakpoint on that assert, run command `modeled[params.keys()].values-expected[params.keys()].values`.

There is no difference, I've added my results to the details section down below.

Now I wonder whether that term has any impact on the model (I suppose it does, nobody would have put it there without a reason). Is there any check I've missed? Maybe is the max cell temp difference from STC too low (20 ºC)?

<details><summary>Same output</summary>
<p>

```bash
fit_desoto_sandia
-----------------
+ 0.0002677
Mismatched elements: 2 / 5 (40%)
Max absolute difference among violations: 10.26629715
Max relative difference among violations: 0.07620939

modeled[params.keys()].values-expected[params.keys()].values =
array([-7.84332362e-05,  7.69714883e-12,  1.02662972e+01, -4.47022678e-03,
        7.18454498e-03])

- 0.0002677
Mismatched elements: 2 / 5 (40%)
Max absolute difference among violations: 10.26629715
Max relative difference among violations: 0.07620939

modeled[params.keys()].values-expected[params.keys()].values =
array([-7.84332362e-05,  7.69714883e-12,  1.02662972e+01, -4.47022678e-03,
        7.18454498e-03])
```

</p>
</details>

**Comment by cwhanse** [comment]
The way that algorithm works, the value of `dEgdT` only affects `EgRef` and `I_o_ref`, and the effect on `I_o_ref` is very small. Here's a script to illustrate.  `sdm_desoto_degdt` is a copy of pvlib\ivtools\sdm.py with lines 857-858 changed:

```
    elif model == 'desoto':
        dEgdT = 0.0002677 * degdt_sign
```

Pass `degdt_sign` into `_extract_sdm_params` from `fit_desoto_sandia`. Give it values of either +1 or -1.

```
import numpy as np
import sdm_desoto_degdt as sdd
from pvlib import pvsystem


cansol = {'ivcurve': {'V_mp_ref': 46.6, 'I_mp_ref': 4.73, 'V_oc_ref': 58.3,
                        'I_sc_ref': 5.05},
            'specs': {'alpha_sc': 0.0025, 'beta_voc': -0.19659,
                      'gamma_pmp': -0.43, 'cells_in_series': 96},
            'params': {'I_L_ref': 5.056, 'I_o_ref': 1.01e-10,
                       'R_sh_ref': 837.51, 'R_s': 1.004, 'a_ref': 2.3674,
                       'Adjust': 2.3}}
params = cansol['params']
params.pop('Adjust')
specs = cansol['specs']
effective_irradiance = np.array([400., 500., 600., 700., 800., 900.,
                                 1000.])
temp_cell = np.array([15., 25., 35., 45.])
ee = np.tile(effective_irradiance, len(temp_cell))
tc = np.repeat(temp_cell, len(effective_irradiance))
IL, I0, Rs, Rsh, nNsVth = pvsystem.calcparams_desoto(
    ee, tc, alpha_sc=specs['alpha_sc'], **params)
ivcurve_params = dict(photocurrent=IL, saturation_current=I0,
                      resistance_series=Rs, resistance_shunt=Rsh,
                      nNsVth=nNsVth)
sim_ivcurves = pvsystem.singlediode(**ivcurve_params).to_dict('series')
v = np.linspace(0., sim_ivcurves['v_oc'], 300)
i = pvsystem.i_from_v(voltage=v, **ivcurve_params)
sim_ivcurves.update(v=v.T, i=i.T, ee=ee, tc=tc)


result = sdd.fit_desoto_sandia(sim_ivcurves, specs)
for k in ['I_L_ref', 'I_o_ref', 'R_s', 'R_sh_ref', 'a_ref', 'EgRef', 'dEgdT']:
    print(f'{k}: {result[k]}')

result2 = sdd.fit_desoto_sandia(sim_ivcurves, specs, degdt_sign=-1)
for k in ['I_L_ref', 'I_o_ref', 'R_s', 'R_sh_ref', 'a_ref', 'EgRef', 'dEgdT']:
    print(f'{k}: {result2[k]}')
```

**Comment by kandersolar** [comment]
So the problem is not that the change makes no difference, the problem is that our tests don't check the affected quantities.  The test currently only looks at `['I_L_ref', 'I_o_ref', 'R_sh_ref', 'R_s', 'a_ref']`.  Seems like we should add at least `dEgdT` and `EgRef` to the tested values in order to close out #2321.

There are other untested values as well (`'iph', 'io', 'rsh', 'rs', 'u', 'cells_in_series'`).  Seems like we should test those as well, but that's not required for this PR IMHO.

**Comment by echedey-ls** [comment]
These things have caught my attention:
1. The tested module is made of poly-crystalline (from datasheet), for which in [`pvlib.pvsystem.calcparams_pvsyst`](https://pvlib-python.readthedocs.io/en/stable/reference/generated/pvlib.pvsystem.calcparams_pvsyst.html) states in the docstring a `EgRef` = 1.121 eV for crystalline silicon. The result here is `1.3112547292120638`
2. Values of results, lets say `result["rs"]` differ from `Rs` by an amount I'm unable to distinguish acceptable or not. Trace from an `assert_allclose`:
   ```bash
   Mismatched elements: 28 / 28 (100%)
   Max absolute difference among violations: 0.00804031
   Max relative difference among violations: 0.00800828
   ```
   Before making too coarse tests I'd like to have your input.

**Comment by cwhanse** [comment]
> These things have caught my attention:
> 
> 1. The tested module is made of poly-crystalline (from datasheet), for which in [`pvlib.pvsystem.calcparams_pvsyst`](https://pvlib-python.readthedocs.io/en/stable/reference/generated/pvlib.pvsystem.calcparams_pvsyst.html) states in the docstring a `EgRef` = 1.121 eV for crystalline silicon. The result here is `1.3112547292120638`

The algorithm (as documented in the reference technical report) regards `EgRef` as a fitting parameter. I recall that fitting `EgRef` significantly improved the fitted model. Maybe worth a note in `fit_desoto_sandia` docstring.

> 2. Values of results, lets say `result["rs"]` differ from `Rs` by an amount I'm unable to distinguish acceptable or not. Trace from an `assert_allclose`:
>    ```shell
>    Mismatched elements: 28 / 28 (100%)
>    Max absolute difference among violations: 0.00804031
>    Max relative difference among violations: 0.00800828
>    ```

That doesn't surprise me. The five returned vectors are the diode equation parameters one for each input IV curve. The five values are determined by fitting. The thought was that fitting each curve would reveal the structure of the relationship between each parameters and irradiance and temperature. The DeSoto model (and other single diode models) assume that structure is described by the model's auxiliary equations, in the case of `rs`, that `Rs` is a constant for all curves. That's why `rs` differs from `Rs`.

If we test the diode equation parameters `rs` etc. we ought to compare with archived values rather than diode model parameters e.g. `Rs`. IMO, testing at that intermediate level would help with diagnosis if the current `test_fit_desoto_sandia` fails, but if the current test passes (diode model parameters are preserved), then I think it is safe to assume the intermediate variables are also OK.

**Comment by echedey-ls** [comment]
This PR should be ready to go. I don't have more time today so feel free to push changes as you need.

Thanks @cwhanse for the in-depth explanation, I wasn't aware of all that :)

**Review by cwhanse — APPROVED** [review]

**Comment by kandersolar** [comment]
Thanks @echedey-ls!

**Pull request merged**
