### PR TITLE
Lookup altitude2

### LINKED ISSUE #1516: Altitude lookup table
Currently, altitude for `pvlib.location` based algorithms defaults to zero, but if we include a low-resolution altitude lookup, we can provide better results when altitude is not specified.
We can make this altitude lookup the same format as [LinkeTurbidities.h5](https://github.com/pvlib/pvlib-python/blob/master/pvlib/data/LinkeTurbidities.h5), so it wouldn't require that much new code or any new dependencies.
I was able to build an altitude map using [open data aggregated by tilezen](https://github.com/tilezen/joerd/blob/master/docs/data-sources.md). My test H5 file is currently `13 mb` using `4320x2160` resolution, `uint16` altitude, and `gzip` compression. We are free to distribute this data, but we do need to do is add [this attribution](https://github.com/tilezen/joerd/blob/master/docs/attribution.md) somewhere in the documentation.
Would you guys be interested in this feature? Should I make a pull request?

Here is a plot of my sample
altitude
:

### PR DESCRIPTION
**Pull request by nicomt**
- [x] Closes #1516
 - [x] I am familiar with the [contributing guidelines](https://pvlib-python.readthedocs.io/en/latest/contributing.html)
 - [x] Tests added
 - [x] Updates entries in [`docs/sphinx/source/reference`](https://github.com/pvlib/pvlib-python/blob/master/docs/sphinx/source/reference) for API changes.
 - [ ] Adds description and name entries in the appropriate "what's new" file in [`docs/sphinx/source/whatsnew`](https://github.com/pvlib/pvlib-python/tree/master/docs/sphinx/source/whatsnew) for all changes. Includes link to the GitHub Issue with `` :issue:`num` `` or this Pull Request with `` :pull:`num` ``. Includes contributor name and/or GitHub username (link with `` :ghuser:`user` ``).
 - [x] New code is fully documented. Includes [numpydoc](https://numpydoc.readthedocs.io/en/latest/format.html) compliant docstrings, examples, and comments where necessary.
 - [x] Pull request is nearly complete and ready for detailed review.
 - [x] Maintainer: Appropriate GitHub Labels (including `remote-data`) and Milestone are assigned to the Pull Request and linked Issue.

In this pull request, I fix the outstanding issues from the last pull request and replace functions to use lookup_altitude by default

### CODE REVIEW

**Comment by nicomt** [comment]
The coverage for the spa_c solar position method keeps failing even though it is covered in tests.
Could that be caused by a dependency issue? Like the spa.c and spa.h files missing from the test?

**Comment by kanderso-nrel** [comment]
@nicomt we're on the cusp of releasing 0.9.3, which includes your last PR.  Do you agree that there is no problem making that release without including this PR?  Since some defaults are changing, I think it makes sense to wait for 0.10.0 here, just want to confirm that the previous PR can stand on its own without this one.

**Review by AdamRJensen — APPROVED** [review]
Took a brief look and everything seems to check out.

Still a little skeptical about relying on an external file, which may be updated in the future and cause inconsistencies between versions.

**Review by kandersolar — COMMENTED** [review]
Thanks again @nicomt for this PR.  I think I like the `Location` class looking up its own altitude, but I'm not sure it's a good idea to also do the lookup inside the `pvlib.solarposition` functions.  It's okay for the classes to have a little "magic" under the hood if it makes things more convenient, but I think we want more transparency in the functions.  I'm also nervous about the (probably small) runtime cost of the lookup, since most people will not be specifying altitude themselves.  I lean towards keeping the current static defaults in the `pvlib.solarposition.*` functions, but I'm curious what other maintainers think about it.

We'll also need a "what's new" entry, but let's decide where to go with this PR first.

**Comment by nicomt** [comment]
Those concerns are valid, and leaving sea level as the default seems reasonable.
I can close this PR, but then that leaves us with a few options:

1. We make the altitude lookup automatic for the Location class only.
```python
loc = Location(latitude, longitude)  # altitude == location.lookup_altitude
spa_c(times, latitude, longitude) # altitude == 0
```
2. We integrate the altitude lookup everywhere but make it more explicit 
```python
loc = Location(latitude, longitude)  # altitude == 0
spa_c(times, latitude, longitude) # altitude == 0
loc = Location(latitude, longitude, altitude="lookup")  # altitude == location.lookup_altitude
spa_c(times, latitude, longitude, altitude="lookup")  # altitude == location.lookup_altitude
```
3. We make the altitude lookup explicit and only available for the Location class.
```python
loc = Location(latitude, longitude)  # altitude == 0
loc = Location(latitude, longitude, altitude="lookup")  # altitude == location.lookup_altitude
spa_c(times, latitude, longitude)  # altitude == 0
```
5. We leave it as it is and let the user pass the altitude manually
```python
loc = Location(latitude, longitude, altitude=location.lookup_altitude(latitude, longitude))
spa_c(times, latitude, longitude, altitude=location.lookup_altitude(latitude, longitude))
```

What do you guys think?

**Comment by nicomt** [comment]
Closing for now.
While we decide what to do.

**Comment by cwhanse** [comment]
@nicomt my vote is #1, let `Location` lookup altitude, but require it explicitly for the solar position functions.

**Pull request closed without merging**
