### PR TITLE
clarify units for U1 and Uv temperature model coeff

### LINKED ISSUE #945: BUG:units for Uv & U1, convective thermal coefficient for Faiman and PVsyst, m/s should be in denominator
**Describe the bug**
the units are unclear, m/s should be in the denominator, but looks like numerator

https://github.com/pvlib/pvlib-python/blob/e526b55365ab0f4c473b40b24ae8a82c7e42f892/pvlib/temperature.py#L216

and 

https://github.com/pvlib/pvlib-python/blob/e526b55365ab0f4c473b40b24ae8a82c7e42f892/pvlib/temperature.py#L306

**Expected behavior**
There probably isn't a standard, and we could argue, but IMHO the units should always be as explict as possible. I like the way [wikipedia](https://en.wikipedia.org/wiki/Heat_transfer_coefficient#Composition) makes them very explicit using parentheses
image

**Screenshots**
pvsyst:
image
Faiman:
image

**Versions:**
 - ``pvlib.__version__``: e526b55365ab0f4c473b40b24ae8a82c7e42f892

**Additional context**
IMHO these units should uses parentheses like Wikipedia does for clarity:
* Uv & U1: [W/(m^2 K)/(m/s)] or [W/m^2/K/(m/s)] or [(W/m^2)/K/(m/s)]
* Uc & U0: [W/(m^2 K)] or [W/m^2/K] or [(W/m^2)/K]

### PR DESCRIPTION
**Pull request by mikofski**
* closes #945 
* group denominator together, same way it was done for U0 and Uc, ie: `W/(m^2 C)` instead of `(W/m^2 C)` which is ambiguous because it could mean `W/m^2 * C = W * C / m^2` which is not the same thing
* add missing division symbol before 2nd denominator `(m/s)` to get `W / (m^2 C) / (m/s)` instead of `(W/m^2 C) (m/s)` which looks like `WmC/ (m^2 s)` so it's ambiguous
* pvsyst help docs (https://www.pvsyst.com/help/thermal_loss.htm) say  `W/m²·k / m/s` which is also ambiguous but you can't win em all

 - [x] Closes #xxxx
 - [x] I am familiar with the [contributing guidelines](https://pvlib-python.readthedocs.io/en/latest/contributing.html)
 - [x] ~Tests added~
 - [x] ~Updates entries to [`docs/sphinx/source/api.rst`](https://github.com/pvlib/pvlib-python/blob/master/docs/sphinx/source/api.rst) for API changes.~
 - [x] Adds description and name entries in the appropriate "what's new" file in [`docs/sphinx/source/whatsnew`](https://github.com/pvlib/pvlib-python/tree/master/docs/sphinx/source/whatsnew) for all changes. Includes link to the GitHub Issue with `` :issue:`num` `` or this Pull Request with `` :pull:`num` ``. Includes contributor name and/or GitHub username (link with `` :ghuser:`user` ``).
 - [x] ~New code is fully documented. Includes [numpydoc](https://numpydoc.readthedocs.io/en/latest/format.html) compliant docstrings, examples, and comments where necessary.~
 - [x] Pull request is nearly complete and ready for detailed review.
 - [x] Maintainer: Appropriate GitHub Labels and Milestone are assigned to the Pull Request and linked Issue.

### CODE REVIEW

**Comment by kanderso-nrel** [comment]
In this and other cases with combined units, I wonder if it might be better to use a `:math:` tag to improve the rendering.  The plaintext display is a little difficult to parse:

image

**Comment by mikofski** [comment]
>In this and other cases with combined units, I wonder if it might be better to use a :math: tag to improve the rendering.

Everywhere? what about units that are simpler to parse? Probably best to be consistent, right?
https://github.com/pvlib/pvlib-python/blob/3ce8e1a5e5db42d09982e0153b65b4a8547180fa/pvlib/temperature.py#L46

I'm okay with making the shift to use `:math:` to render all units, but maybe that should be a separate issue? It would be a bit of an undertaking, good first timer maybe?

**Comment by cwhanse** [comment]
> Everywhere? what about units that are simpler to parse? Probably best to be consistent, right?

Perhaps in the few instances where the unit involves a compound fraction. I'm -1 for using :math: for units otherwise.

**Comment by mikofski** [comment]
Quick poll, so we've decided to use `: math:` to render these ugly confusing units here only, EG:
```python
in :eq:`pvsyst` :math:`\left[\frac{W/{\left(m^2 C\right)}{m/s}\right]`.
```

Looks like this
![latex] (https://latex.codecogs.com/png.latex?\left[&space;\frac{W/{\left(m^2&space;C\right)}}{m/s}&space;\right])

**Comment by adriesse** [comment]
Could we do:

```
 W/m2
------
C(m/s)
```
This would be more easily associated with the variables going in.

**Comment by mikofski** [comment]
>Could we do: `W/m^2 / (C(m/s))`

I'm fine with

    :math:`\left[\frac{W/{m^2 }}{C \left( m/s \right )}\right]`

which looks like this:
LaTeX equation}\right])
[Powered by CodeCogs](https://www.codecogs.com/eqnedit.php?latex=\left[\frac{W/{m^2}}{C\left(m/s\right)}\right])

But this makes me wonder if the `U0` and `U_c` should also be changed to look the same?
LaTeX equation
[Powered by CodeCogs](https://www.codecogs.com/eqnedit.php?latex=\left[\frac{W/{m^2}}{C}\right])

What do y'all think?

**Comment by mikofski** [comment]
Also should we be using Kelvin instead of Celsius?

**Comment by adriesse** [comment]
Sure, but I'd also be ok with the plain text:```[W/m^2/C]``` and ```[W/m^2/C/(m/s)]```.
My preference is for Celsius.

**Comment by cwhanse** [comment]
> My preference is for Celsius.

+1

**Comment by mikofski** [comment]
sorry stickler by inline math don't render if it's on two lines 😕

**Comment by mikofski** [comment]
What do you think @CameronTStark? Is this good?

**Comment by CameronTStark** [comment]
LGTM @mikofski, thanks!

**Pull request merged**
