### PR TITLE
Issue #2712 - implements closed-form solution for alpha in detect_clearsky

### PR DESCRIPTION
**Pull request by agodbehere**
Implements closed-form solution and removes call to scipy.optimize. Previously, the optimization algorithm would fail, but this solution does not have that issue. Thus, one test is also modified, checking that detect_clearsky runs successfully on a range of window_lengths including the one that previously failed.

 - [x] Closes #2712
 - [x] I am familiar with the [contributing guidelines](https://pvlib-python.readthedocs.io/en/latest/contributing.html)
 - [x] Tests added
 - [x] Adds description and name entries in the appropriate "what's new" file in [`docs/sphinx/source/whatsnew`](https://github.com/pvlib/pvlib-python/tree/main/docs/sphinx/source/whatsnew) for all changes. Includes link to the GitHub Issue with `` :issue:`num` `` or this Pull Request with `` :pull:`num` ``. Includes contributor name and/or GitHub username (link with `` :ghuser:`user` ``).
 - [x] New code is fully documented. Includes [numpydoc](https://numpydoc.readthedocs.io/en/latest/format.html) compliant docstrings, examples, and comments where necessary.
 - [x] Pull request is nearly complete and ready for detailed review.

### CODE REVIEW

**Comment by echedey-ls** [comment]
Can you revert changes in commit `https://github.com/pvlib/pvlib-python/pull/2173/commits/9beafb9c7fe17e460f0c6d9dfc3257a1528d2d14`? It's difficult to review a PR when there are too many lines that have changes, also cluttering the git blames with style changes is discouraged.

**Comment by agodbehere** [comment]
Will do, my apologies. Flake-8 had failed on lines I hadn’t changed, so I
went and over-did it.

**Comment by cwhanse** [comment]
@agodbehere please let me know if you would like help getting this PR over the finish line.

**Comment by agodbehere** [comment]
@cwhanse - the Flake8 test is failing on pre-existing lines that I didn't touch. How should I handle this case? Should I amend those 3 lines to pass Flake8 or should I create a new pull request to fix the style issues?

**Comment by cwhanse** [comment]
@agodbehere we'd like to revert the changes in https://github.com/pvlib/pvlib-python/pull/2173/commits/9beafb9c7fe17e460f0c6d9dfc3257a1528d2d14 

The CI is configured to only run flake8 on changed lines. I guess you are running flake8 locally and that's why it's flagging all those other style issues. If we fix those, a separate PR is better.

**Comment by echedey-ls** [comment]
@cwhanse @agodbehere the problem is that the flake8 CI script is made to warn about lint problems on the diff lines; a diff contains a few more lines than those that have been changed, just 3 at the beginning and at the end, sometimes even more. A diff is what you see in the [tab above that says "Files"](https://github.com/pvlib/pvlib-python/pull/2173/files).

Even thou the CI fails, I think it is safe to merge the PR with this failed test, since it doesn't impact the rest of the repo. Just keep the changes clear for the reviewers, which is the reason behind reverting that commit.

**Comment by agodbehere** [comment]
I have reverted the commit. As expected, Flake8 is still failing. @echedey-ls @cwhanse - would you like to merge as-is?

**Comment by cwhanse** [comment]
@agodbehere have you pushed the reverted commit? I don't see the changes here.

**Comment by cwhanse** [comment]
> Would you be open to that approach?

Yes, certainly. Sorry for the rework.

**Pull request closed without merging**
