### PR TITLE
Update v0.9.1.rst #1416

### PR DESCRIPTION
**Pull request by soma2000-lang**
@cwhanse  Added myself to the contributors section as you sugested
fixes #1416

### CODE REVIEW

**Comment by cwhanse** [comment]
@soma2000-lang could you add this change to #1416?

**Comment by wholmgren** [comment]
I think with new contributors we should be forgiving about this kind of workflow mistake... easy enough for us to hit merge twice or for us to make the change in the original PR. Of course @soma2000-lang is welcome to make the change in #1416 too.

**Comment by cwhanse** [comment]
We'll merge #1416 and this together. Thanks @soma2000-lang !

**Comment by cwhanse** [comment]
Thanks @soma2000-lang !

**Pull request merged**
