### PR TITLE
Remove ``read_srml_month_from_solardat``

### PR DESCRIPTION
**Pull request by echedey-ls**
- ~[ ] Closes #xxxx~
 - [x] I am familiar with the [contributing guidelines](https://pvlib-python.readthedocs.io/en/latest/contributing.html)
 - ~[ ] Tests added~
 - [x] Updates entries in [`docs/sphinx/source/reference`](https://github.com/pvlib/pvlib-python/blob/main/docs/sphinx/source/reference) for API changes.
 - [ ] Adds description and name entries in the appropriate "what's new" file in [`docs/sphinx/source/whatsnew`](https://github.com/pvlib/pvlib-python/tree/main/docs/sphinx/source/whatsnew) for all changes. Includes link to the GitHub Issue with `` :issue:`num` `` or this Pull Request with `` :pull:`num` ``. Includes contributor name and/or GitHub username (link with `` :ghuser:`user` ``).
 - ~[ ] New code is fully documented. Includes [numpydoc](https://numpydoc.readthedocs.io/en/latest/format.html) compliant docstrings, examples, and comments where necessary.~
 - [x] Pull request is nearly complete and ready for detailed review.
 - [x] Maintainer: Appropriate GitHub Labels (including `remote-data`) and Milestone are assigned to the Pull Request and linked Issue.

It was marked to be removed, no PR or issue found.

### CODE REVIEW

**Comment by echedey-ls** [comment]
Do removal of deprecated features require a whatsnew entry?

**Comment by AdamRJensen** [comment]
> Does the removal of deprecated features require a whatsnew entry?

Migh as well. Something along the lines of
> pvlib.iotools.read_srml_month_from_solardat was deprecated in version xx
> and has now fully removed in v0.11.0.

**Comment by AdamRJensen** [comment]
Note, this PR is a duplicate of #1989.

**Comment by AdamRJensen** [comment]
Closing this as it is a duplicate of #1989.

**Comment by echedey-ls** [comment]
Damn, I may have missed it from the milestone page

**Pull request closed without merging**
