### PR TITLE
Performance ratio v1

### PR DESCRIPTION
**Pull request by SaurabhPAneja**
- [ ] Closes #xxxx
 - [ ] I am familiar with the [contributing guidelines](https://pvlib-python.readthedocs.io/en/latest/contributing.html)
 - [ ] Tests added
 - [ ] Updates entries to [`docs/sphinx/source/api.rst`](https://github.com/pvlib/pvlib-python/blob/master/docs/sphinx/source/api.rst) for API changes.
 - [ ] Adds description and name entries in the appropriate "what's new" file in [`docs/sphinx/source/whatsnew`](https://github.com/pvlib/pvlib-python/tree/master/docs/sphinx/source/whatsnew) for all changes. Includes link to the GitHub Issue with `` :issue:`num` `` or this Pull Request with `` :pull:`num` ``. Includes contributor name and/or GitHub username (link with `` :ghuser:`user` ``).
 - [ ] New code is fully documented. Includes [numpydoc](https://numpydoc.readthedocs.io/en/latest/format.html) compliant docstrings, examples, and comments where necessary.
 - [ ] Pull request is nearly complete and ready for detailed review.
 - [ ] Maintainer: Appropriate GitHub Labels and Milestone are assigned to the Pull Request and linked Issue.

 Here is a version 1 of the performance ratio implementation. It utilizes various PVLib functions and uses the poa global-weighted method for determining Tref. Currently we need to filter for clipping and low light. I figured the community should decide on best way to filter clipping out, however, I can put a place holder. Documentation will need updates, along with other components of this request.

### CODE REVIEW

**Comment by kanderso-nrel** [comment]
Hey @PVPro-SPA, great to see you here!  I'm happy to help guide this PR, especially with the "extra" bits like code tests and documentation.

Is this pull request intended to be a faithful implementation of the Dierauf et al. Performance Ratio?  I ask because, while they might be in the spirit of that performance test and used in industry, I don't think low-light and clipping filters are mentioned in NREL/TP-5200-57991.  I'm okay with either way (following the technical report exactly or extending the method to be more useful), but I want it to be a conscious and documented decision.

Also curious if this is a part of a broader pvlib scope expansion into performance testing.  I wonder if [pvanalytics](https://github.com/pvlib/pvanalytics) is a better fit.

**Comment by cwhanse** [comment]
thanks @kanderso-nrel I am thinking the same that a PR function might fit better in pvanalytics, but I'm open other views.

**Comment by PVPro-SPA** [comment]
Thanks @kanderso-nrel. It is always a pleasure to cross paths and learn from you.

I agree with you on the clipping/low light filtering. If we do want something there, I wonder if we can put it as an optional parameter in the function call (low_light_filter=True) or something like that. This may be more than needed, and it may be best to stay within confines of paper.

I also agree that this seems a better fit for pvanalytics.

**Comment by cwhanse** [comment]
Merged in [pvlib/pvanalytics](https://github.com/pvlib/pvanalytics/pull/69)

**Pull request closed without merging**
