### PR TITLE
solar_position_method arg passed to basic_chain method wasn't used

### PR DESCRIPTION
**Pull request by KonstantinTr**
solar_position_method arg passed to basic_chain method wasn't used causing execution of solarposition.get_solarposition with default 'nrel_numpy' value in all cases.

### CODE REVIEW

**Comment by KonstantinTr** [comment]
There is something I don't understand: git shows all commitments from my fork. Even those that was closed in previous pull request. They doesn't change code in this pull request.

What should I do to show only relevant changes regarding this particular pull request?

**Comment by wholmgren** [comment]
Can you add a note to the 0.5.1 whatsnew file? 

I see the doc string for this parameter is also wrong. It references a location object's method instead of the solarposition module's function. Can you fix this too? Same for the parameters above and below.

The diff here is showing only 1 changed line. You could be seeing more changes locally, but it depends on how you've configured your git client. In general, the best git procedure for pvlib users is to:

1. fork the library
2. clone your fork to your computer
2. make a branch dedicated to the small change that you want to make
2. checkout the new branch
2. make the changes, commit the changes
2. push the new branch to your github fork
2. make a pull request from your fork's branch

The key ideas are to keep your local master up to date with ``pvlib/master`` (use git fetch and git rebase or git pull) and do not make any changes to your local master. Only make changes in branches, with one branch for each pull request. Note that some git clients will automatically refer to this as ``upstream/master``.

**Comment by KonstantinTr** [comment]
@wholmgren Thanks a lot for clarification! Next time I'll try with branches. 

Sure, I can fix doc string and update what's new file. Let me see if I can add these changes to the same pull request.

**Comment by wholmgren** [comment]
Thanks @KonstantinTr!

**Comment by KonstantinTr** [comment]
@wholmgren my pleasure :)

**Pull request merged**
