### PR TITLE
changed wid to omega_ideal

### PR DESCRIPTION
**Pull request by kurt-rhee**
- [x] Closes https://github.com/pvlib/pvlib-python/discussions/2137
 - [x] I am familiar with the [contributing guidelines](https://pvlib-python.readthedocs.io/en/latest/contributing.html)
 - [ ] Tests added
 - [ ] Updates entries in [`docs/sphinx/source/reference`](https://github.com/pvlib/pvlib-python/blob/main/docs/sphinx/source/reference) for API changes.
 - [ ] Adds description and name entries in the appropriate "what's new" file in [`docs/sphinx/source/whatsnew`](https://github.com/pvlib/pvlib-python/tree/main/docs/sphinx/source/whatsnew) for all changes. Includes link to the GitHub Issue with `` :issue:`num` `` or this Pull Request with `` :pull:`num` ``. Includes contributor name and/or GitHub username (link with `` :ghuser:`user` ``).
 - [ ] New code is fully documented. Includes [numpydoc](https://numpydoc.readthedocs.io/en/latest/format.html) compliant docstrings, examples, and comments where necessary.
 - [x] Pull request is nearly complete and ready for detailed review.
 - [ ] Maintainer: Appropriate GitHub Labels (including `remote-data`) and Milestone are assigned to the Pull Request and linked Issue.

### CODE REVIEW

**Comment by cwhanse** [comment]
@pvlib/pvlib-maintainer we haven't adopted `black` as the formatter. When PRs use `black` to fix lint errors, it appears that `black` also reformats lines that the submitter doesn't change. Are we OK with this? I think it's a minor concern, unless, clutter in the blame history is not a minor concern.

**Comment by AdamRJensen** [comment]
> @pvlib/pvlib-maintainer we haven't adopted `black` as the formatter. When PRs use `black` to fix lint errors, it appears that `black` also reformats lines that the submitter doesn't change. Are we OK with this? I think it's a minor concern, unless, clutter in the blame history is not a minor concern.

My concern is mainly that it makes reviewing more difficult. If we want to apply black then we should do the whole package in one go. I'm -1 on individual PRs doing it.

**Comment by echedey-ls** [comment]
Given that @kurt-rhee is a big fan of VSCode and Rust, I'm assuming he is using [`ruff`](https://github.com/astral-sh/ruff), right? For context, it is a Python linter and formatter written in Rust. And it has a [plugin for VSCode](https://marketplace.visualstudio.com/items?itemName=charliermarsh.ruff).

Kurt, in case you didn't know, you can format only some selected lines by selecting them and right-clicking, then click on `Format Selection`

image

This is the real behind-the-scenes of pretty much all my PRs

**Comment by kurt-rhee** [comment]
@echedey-ls I was using black just to be lazy and not format the flake8 line lengths manually.  I'll try out Ruff next, the format selection feature looks really nice!

New PR here without any autoformatting:  https://github.com/pvlib/pvlib-python/pull/2146

**Pull request closed without merging**
