### PR TITLE
Propagate d2mutau and NsVbi from PVSystem

### PR DESCRIPTION
**Pull request by cwhanse**
pvlib python pull request guidelines
====================================

Thank you for your contribution to pvlib python! You may delete all of these instructions except for the list below.

You may submit a pull request with your code at any stage of completion.

The following items must be addressed before the code can be merged. Please don't hesitate to ask for help if you're unsure of how to accomplish any of the items below:

 - [ ] Closes issue #xxxx
 - [ ] I am familiar with the [contributing guidelines](http://pvlib-python.readthedocs.io/en/latest/contributing.html).
 - [ ] Fully tested. Added and/or modified tests to ensure correct behavior for all reasonable inputs. Tests (usually) must pass on the TravisCI and Appveyor testing services.
 - [ ] Updates entries to `docs/sphinx/source/api.rst` for API changes.
 - [ ] Adds description and name entries in the appropriate `docs/sphinx/source/whatsnew` file for all changes.
 - [ ] Code quality and style is sufficient. Passes LGTM and SticklerCI checks.
 - [ ] New code is fully documented. Includes sphinx/numpydoc compliant docstrings and comments in the code where necessary.
 - [ ] Pull request is nearly complete and ready for detailed review.

Brief description of the problem and proposed solution (if not already fully described in the issue linked to above):

### CODE REVIEW

**Comment by cwhanse** [comment]
I'm rethinking the initial idea to build the recombination equation into `singlediode`.  The two extra parameters propagate to a lot of other functions in `pvsystem`, but only apply when using the PVsyst model for CdTe devices.

What do people feel about adding `pvsystem.singlediode_recomb`, as a separate function?  PVSystem would wrap this function just as `PVSystem.singlediode` does, but `ModelChain.pvsyst` would provide the switch between standard single diode and single diode with recombination.

I have had two recent requests for this capability.

**Comment by mikofski** [comment]
It doesn't really bother me is the two extra arguments aren't used, I'm more concerned about extra code, unless `singlediode_recomb` was the base function, and then `singlediode` was a more specific case with `vbi` and `d2mutau` set to `None`

```python
def singlediode_recomb(...):
    return result

def singlediode():
    return singlediode_recomb(..., vbi=None, d2mutau=None):
```

**Comment by mikofski** [comment]
Was this merged?

**Comment by cwhanse** [comment]
No - want to work it?

**Pull request closed without merging**
