### PR TITLE
[FIX] iam.physical returns nan for aoi > 90° when n = 1 (#1706)

### LINKED ISSUE #1706: regression: iam.physical returns nan for aoi > 90° when n = 1
**Describe the bug**
For pvlib==0.9.5, when n = 1 (no reflection) and aoi > 90°, we get nan as result.

**To Reproduce**
```python
import pvlib
pvlib.iam.physical(aoi=100, n=1)
```
returns `nan`.

**Expected behavior**
The result should be `0`, as it was for pvlib <= 0.9.4.

**Versions:**
 - ``pvlib.__version__``: '0.9.5'
 - ``pandas.__version__``:  '1.5.3'
 - python: 3.10.4

### PR DESCRIPTION
**Pull request by kdebrab**
- [x] Closes #1706
 - [x] I am familiar with the [contributing guidelines](https://pvlib-python.readthedocs.io/en/latest/contributing.html)
 - [x] Tests added
 - [x] Updates entries in [`docs/sphinx/source/reference`](https://github.com/pvlib/pvlib-python/blob/main/docs/sphinx/source/reference) for API changes.
 - [x] Adds description and name entries in the appropriate "what's new" file in [`docs/sphinx/source/whatsnew`](https://github.com/pvlib/pvlib-python/tree/main/docs/sphinx/source/whatsnew) for all changes. Includes link to the GitHub Issue with `` :issue:`num` `` or this Pull Request with `` :pull:`num` ``. Includes contributor name and/or GitHub username (link with `` :ghuser:`user` ``).
 - [x] New code is fully documented. Includes [numpydoc](https://numpydoc.readthedocs.io/en/latest/format.html) compliant docstrings, examples, and comments where necessary.
 - [x] Pull request is nearly complete and ready for detailed review.
 - [x] Maintainer: Appropriate GitHub Labels (including `remote-data`) and Milestone are assigned to the Pull Request and linked Issue.

### CODE REVIEW

**Comment by cwhanse** [comment]
The nan appears to enter [here](https://github.com/pvlib/pvlib-python/blob/7a2ec9b4765124463bf0ddd0a49dcfedc4cbcad7/pvlib/iam.py#L178) and on the following line, because `n1costheta1`  and `n2costheta1` are both zero when AOI>90, n=1 and n_ar is None.  I wonder if there is a condensed mathematical expression for the IAM in the limit case of `n1=1`, `n2=1`, and `n3=1`.

**Comment by kdebrab** [comment]
> The nan appears to enter [here](https://github.com/pvlib/pvlib-python/blob/7a2ec9b4765124463bf0ddd0a49dcfedc4cbcad7/pvlib/iam.py#L178) and on the following line, because `n1costheta1` and `n2costheta1` are both zero when AOI>90, n=1 and n_ar is None. I wonder if there is a condensed mathematical expression for the IAM in the limit case of `n1=1`, `n2=1`, and `n3=1`.

Such a shortcut is indeed possible, but it requires a special path not only at L178-179 but also at L211-212 (and maybe even L196-201).  But most importantly, it wouldn't be sufficient as we also need to support n2 as a vector (see https://github.com/pvlib/pvlib-python/pull/1616#issuecomment-1411767309), where potentially some elements are 1 and others not, and thus we would still need the lines included in the current pull request.
So, I think that in the end such a shortcut would probably not bring anything anymore in terms of performance and only complicate things.

**Review by mikofski — APPROVED** [review]
Thanks

**Review by kandersolar — COMMENTED** [review]
Thanks @kdebrab!  Can you add a bug fix entry in the 0.9.6 what's new file?

One thing is that the new test produces some runtime warning clutter: https://github.com/pvlib/pvlib-python/actions/runs/4510438842/jobs/7941391259?pr=1707#step:9:58


It would be nice to prevent `iam.physical` from emitting those, but `n=1` seems uncommon enough that I'd be okay with just suppressing them in the test function if there's not a clean way of preventing them at the source.

**Comment by adriesse** [comment]
There is an interesting thing happening with this sequence of inexact trig calculations:
```
costheta = np.maximum(0, cosd(aoi))  # --> 6.123233995736766e-17
sintheta = np.sqrt(1 - costheta**2)  # --> 1.0
costheta = np.sqrt(1 - sintheta**2) # --> 0.0
```

If the first line were producing a true zero this function would blow up sooner and more often; therefore, the previous use of ```zeroang = 1e-06```  might be the preferred solution.  

We shouldn't really rely on cosd(90) != 0 anywhere, although we probably unwittingly do.

**Comment by adriesse** [comment]
I would follow this up with a suggestion to rewrite tools.cosd as
```
np.sqrt(1 - np.square(np.sin(90 * (np.pi / 180))))
```

**Comment by cwhanse** [comment]
> I would follow this up with a suggestion to rewrite tools.cosd as
> 
> ```
> np.sqrt(1 - np.square(np.sin(90 * (np.pi / 180))))
> ```

I'm puzzled by this. I assume you meant `theta * (np.pi/180))`. How would it properly evaluate cosd(135)? It can't return a negative value, since np.sqrt only returns the principal root.

**Comment by adriesse** [comment]
> I'm puzzled by this

Sorry, didn't think that through all the way.

**Comment by kandersolar** [comment]
I'm going to merge this since it's ready to go and an improvement.  Additional improvements can always be future PRs :)

Thanks again @kdebrab for noticing and fixing this bug!

**Pull request merged**
