### PR TITLE
Fix error in the irradiance unit checker.

### PR DESCRIPTION
**Pull request by dzimmanck**
This is a fix to a very simple error, so I am bypassing the checklist.  It is a one line correction to what is clearly a simple error.

### CODE REVIEW

**Comment by wholmgren** [comment]
Thanks! It is a simple error, but it means the deprecation warning does not work as intended. We should make a 0.7.1 release very soon. I suggest we go ahead and merge this as is and add a note when #842 is merged.

**Comment by adriesse** [comment]
Thanks for fixing this.  I had wondered about the deprecation messages I was getting but hadn't had time to investigate.  I do think that all zeros should not trigger the message (ideally).

**Comment by wholmgren** [comment]
>  I do think that all zeros should not trigger the message (ideally).

That seems reasonable in principle. Do you actually run into this problem?

**Comment by cwhanse** [comment]
>> I do think that all zeros should not trigger the message (ideally).
> 
> That seems reasonable in principle.

Want me to refine the test condition to exclude 0.0 and NaN?

**Comment by wholmgren** [comment]
> Want me to refine the test condition to exclude 0.0 and NaN?

sure, let's hold 0.7.1 for that. I don't think it needs extensive testing - let's just make sure it looks right this time.

**Comment by adriesse** [comment]
> Do you actually run into this problem?

Not in typical time series, but when comparing models/graphing performance matrices, single or multiple zeroes do come up.

**Pull request merged**
