### PR TITLE
Update GH action versions

### PR DESCRIPTION
**Pull request by AdamRJensen**
Duplicate of #2218 

 - [x] I am familiar with the [contributing guidelines](https://pvlib-python.readthedocs.io/en/latest/contributing.html)
 - [x] Pull request is nearly complete and ready for detailed review.
 - [x] Maintainer: Appropriate GitHub Labels (including `remote-data`) and Milestone are assigned to the Pull Request and linked Issue.

The current versions of the tools used in the GH actions are outdated and are emitting warnings:

image

image

Used the replace-all function in Visual Studio Code that handles all files in a repository [link](https://stackoverflow.com/questions/37346481/how-do-i-find-and-replace-all-occurrences-in-all-files-in-visual-studio-code)

### CODE REVIEW

**Comment by echedey-ls** [comment]
You may want to compare against #2218

**Comment by AdamRJensen** [comment]
> You may want to compare against #2218
> 
> P.S.: when did you become part of the VSCode gang? 🤩

Here I was all proud of using VSCode and then it's a duplicate PR - sorry @echedey-ls. I think we should merge either one of the two (they're identical now).

**Comment by AdamRJensen** [comment]
@echedey-ls Want to leave a review?

**Review by echedey-ls — APPROVED** [review]
LGTM with the following change:

- this one (that I missed in my PR) can be updated to `v5`.
https://github.com/AdamRJensen/pvlib-python/blob/1192df32c56061b262cbae8640060d76fbdfc330/.github/workflows/publish.yml#L23

**Review by kandersolar — APPROVED** [review]
Thanks @AdamRJensen and @echedey-ls :)

**Pull request merged**
