### PR TITLE
Add LGTM code quality badges

### PR DESCRIPTION
**Pull request by xcorail**
Hi there!

I thought you might be interested in adding these [code quality badges](https://lgtm.com/projects/g/pvlib/pvlib-python/ci/#badges) to your project. They will indicate a very high code quality to potential users and contributors.
You can also check the alerts discovered by [LGTM](https://lgtm.com/projects/g/pvlib/pvlib-python).

N.B.: I am on the team behind LGTM.com, I'd appreciate your feedback on this initiative, whether you're interested or not, if you find time to drop me a line. Thanks.

### CODE REVIEW

**Comment by cwhanse** [comment]
@wholmgren some interesting bugs found by the [LGTM alerts](https://lgtm.com/projects/g/pvlib/pvlib-python/alerts/?mode=list)

**Comment by wholmgren** [comment]
Looks like it could be useful. 

So far as I can tell, a few of the reported errors are incorrect. These include:

* ``NotImplementedType`` errors in ``singlediode.py`` are probably hit due to the optional dependency allowance. [see here](https://lgtm.com/projects/g/pvlib/pvlib-python/snapshot/dist-1794124795-1535630266160/files/pvlib/singlediode.py#x6247ee49958c4865:1)
* If I correctly understand the``pvsystem.py`` method signature complaint (``SingleAxisTracker.get_aoi`` signature differs from ``PVSystem.get_aoi`` signature) then it's not a problem. [see here](https://lgtm.com/projects/g/pvlib/pvlib-python/snapshot/dist-1794124795-1535630266160/files/pvlib/pvsystem.py?sort=name&dir=ASC&mode=heatmap&showExcluded=false#x6f356ddf1ebc947b:1)

The imports should be cleaned up, though they are not hurting anything. Same for unused and identically assigned variables.

This ``forecast.py`` [report](https://lgtm.com/projects/g/pvlib/pvlib-python/snapshot/dist-1794124795-1535630266160/files/pvlib/forecast.py?sort=name&dir=ASC&mode=heatmap&showExcluded=false#xcbb7bc48300cd9bf:1) is a bug. 

We'd probably want to add a ``.lgtm.yml`` file similar to [metpy](https://github.com/Unidata/MetPy/blob/master/.lgtm.yml)

Most importantly we'd want to enable github integration to check pull requests. This is much more interesting to me than badges in the readme.

**Comment by mikofski** [comment]
>NotImplementedType errors in singlediode.py are probably hit due to the optional dependency allowance.

Actually, I think it *is* a bug. I should have used `brentq = lambda: NotImplemented` so that it's callable because [`NotImplemented` is a constant](https://docs.python.org/3/library/constants.html#NotImplemented), and will raise an exception if called:
```
TypeError: 'NotImplementedType' object is not callable
```
Sorry, I can send a pr to address it. Shall I open a ticket, or just wait until the SciPy dependency discussion is resolved?

**Comment by xcorail** [comment]
Hi @cwhanse @wholmgren 

Happy of this feedback, and thanks a lot for the detailed report. Allow me to pass it to my python colleagues so that they can check the false positives.

> Most importantly we'd want to enable github integration to check pull requests. This is much more interesting to me than badges in the readme.

I cannot agree more. PR integration is indeed the usage we recommend. I think the badges are more interesting for your potential users. Activating PR integration is [a one-click operation](https://lgtm.com/projects/g/pvlib/pvlib-python/ci/).

**Comment by wholmgren** [comment]
@mikofski thanks for checking! please do put in a quick pr.

**Comment by wholmgren** [comment]
Added PR integration. Easy to remove if we don't like it.

**Comment by wholmgren** [comment]
I'll go ahead and merge this and separately add a ``.lgtm.yml`` file. Thanks for the push, @xcorail.

**Pull request merged**
