### PR TITLE
Updated get_cams protocol to https #1457

### LINKED ISSUE #1457: Update get_cams protocol to https
According to an email sent out by Transvalor on May 12th 2022, the SoDa websites and services will switch from using "HTTP" to only "HTTPS". 

The existing HTTP endpoints will redirect to the correct HTTPS sites, hence without any changes the [`get_cams`](https://pvlib-python.readthedocs.io/en/stable/reference/generated/pvlib.iotools.get_cams.html) function will continue to work correctly (as the request package handles redirects automatically). However, for good practice and to avoid unnecessary redirects, updating the existing URLs and endpoints to HTTPS is surely a good idea:
https://github.com/pvlib/pvlib-python/blob/a0812b12584cfd5e662fa5aeb8972090763a671f/pvlib/iotools/sodapro.py#L188

<br>
For reference, here's a screen-shot of Transvalor email:

image

FYI: this is a good first issue to tackle to get familiar with contribution to pvlib :)

### PR DESCRIPTION
**Pull request by PrajwalBorkar**
- [x] Closes #1457 
 - [x] I am familiar with the [contributing guidelines](https://pvlib-python.readthedocs.io/en/latest/contributing.html)
 - ~~[ ] Tests added~~
 - ~~[ ] Updates entries in [`docs/sphinx/source/reference`](https://github.com/pvlib/pvlib-python/blob/master/docs/sphinx/source/reference) for API changes.~~
 - [x] Adds description and name entries in the appropriate "what's new" file in [`docs/sphinx/source/whatsnew`](https://github.com/pvlib/pvlib-python/tree/master/docs/sphinx/source/whatsnew) for all changes. Includes link to the GitHub Issue with `` :issue:`num` `` or this Pull Request with `` :pull:`num` ``. Includes contributor name and/or GitHub username (link with `` :ghuser:`user` ``).
 - ~~[x] New code is fully documented. Includes [numpydoc](https://numpydoc.readthedocs.io/en/latest/format.html) compliant docstrings, examples, and comments where necessary.~~
 - [x] Pull request is nearly complete and ready for detailed review.
 - [x] Maintainer: Appropriate GitHub Labels and Milestone are assigned to the Pull Request and linked Issue.

### CODE REVIEW

**Comment by AdamRJensen** [comment]
> If anyone can help with the errors it will be great.

There exists a number of mock tests that  compare the url created by the get_cams function to the expected URL which is hard coded. So you need to also change http to https in the file: pvlib/tests/iotools/test_sodapro.py

**Comment by PrajwalBorkar** [comment]
> > If anyone can help with the errors it will be great.
> 
> There exists a number of mock tests that compare the url created by the get_cams function to the expected URL which is hard coded. So you need to also change http to https in the file: pvlib/tests/iotools/test_sodapro.py
> 
> It would probably also be a good idea to change the documentation links to https.

Thanks for help . But in the test_sodapro.py file there are two URLs which one should I update? Actually I'm new to this repo and didn't know much about the code.

**Comment by AdamRJensen** [comment]
Each test covers a different scenario, meaning one function may have multiple tests. In this case you would need to change all the instances of http to https
________________________________

**Comment by AdamRJensen** [comment]
@PrajwalBorkar Nice to see the tests are passing. :) Could you also update the documentation links to https?

**Comment by AdamRJensen** [comment]
@PrajwalBorkar All functions are documented using [numpydoc docstrings](https://numpydoc.readthedocs.io/en/latest/format.html). So after each function declaration, there will be several lines of text that get converted into the documentation you see normally. 

The references for the `get_cams` function are declared here: https://github.com/pvlib/pvlib-python/blob/a0812b12584cfd5e662fa5aeb8972090763a671f/pvlib/iotools/sodapro.py#L153-L160

**Comment by PrajwalBorkar** [comment]
> @PrajwalBorkar All functions are documented using [numpydoc docstrings](https://numpydoc.readthedocs.io/en/latest/format.html). So after each function declaration, there will be several lines of text that get converted into the documentation you see normally.
> 
> The references for the `get_cams` function are declared here:
> 
> https://github.com/pvlib/pvlib-python/blob/a0812b12584cfd5e662fa5aeb8972090763a671f/pvlib/iotools/sodapro.py#L153-L160

I have updated the links as you explained any changes are required please tell :)

**Comment by AdamRJensen** [comment]
@PrajwalBorkar In this PR, you can make an additional commit to add your name and GH tag to the contributors section in the most recent whatsnew file [docs/sphinx/source/whatsnew](https://github.com/pvlib/pvlib-python/tree/master/docs/sphinx/source/whatsnew)

**Review by AdamRJensen — APPROVED** [review]

**Comment by PrajwalBorkar** [comment]
> @PrajwalBorkar In this PR, you can make an additional commit to add your name and GH tag to the contributors section in the most recent whatsnew file [docs/sphinx/source/whatsnew](https://github.com/pvlib/pvlib-python/tree/master/docs/sphinx/source/whatsnew)

Yeah. @AdamRJensen Thanks for the help

**Pull request merged**
