### PR TITLE
the parameter closed is deprecated, changed to inclusive

### PR DESCRIPTION
**Pull request by joaoguilhermeS**
- [x] Closes #xxxx
 - [x] I am familiar with the [contributing guidelines](https://pvlib-python.readthedocs.io/en/latest/contributing.html)
 - [x] Tests added
 - [x] Updates entries in [`docs/sphinx/source/reference`](https://github.com/pvlib/pvlib-python/blob/master/docs/sphinx/source/reference) for API changes.
 - [x] Adds description and name entries in the appropriate "what's new" file in [`docs/sphinx/source/whatsnew`](https://github.com/pvlib/pvlib-python/tree/master/docs/sphinx/source/whatsnew) for all changes. Includes link to the GitHub Issue with `` :issue:`num` `` or this Pull Request with `` :pull:`num` ``. Includes contributor name and/or GitHub username (link with `` :ghuser:`user` ``).
 - [x] New code is fully documented. Includes [numpydoc](https://numpydoc.readthedocs.io/en/latest/format.html) compliant docstrings, examples, and comments where necessary.
 - [x] Pull request is nearly complete and ready for detailed review.
 - [x] Maintainer: Appropriate GitHub Labels (including `remote-data`) and Milestone are assigned to the Pull Request and linked Issue.

### CODE REVIEW

**Comment by joaoguilhermeS** [comment]
the parameter 'closed' of the dataframe was deprecated, it should be 'inclusive'.

**Comment by cwhanse** [comment]
Thanks for this update. Did you intend to delete the first 20 lines of the example file? I don't think it will run without the imports.

**Comment by joaoguilhermeS** [comment]
you are correct, I did not intend that

**Comment by cwhanse** [comment]
It appears that the `'closed'` kwarg is deprecated for pandas >= 1.4.0. We still support python 3.7 with pandas=0.25. Rather than introduce complexity into the example to silence the deprecation warning, I think we can live with it for now.

**Pull request closed without merging**
