### PR TITLE
Issue244: Fix for isinstance str in python 3.

### PR DESCRIPTION
**Pull request by lukewitmer**
location timezone support for python3 newstr and unicode args

### CODE REVIEW

**Comment by wholmgren** [comment]
I think one problem is that basestring doesn't exist in Python 3. It looks like you can import six and use string_types as described here:

http://stackoverflow.com/questions/11301138/how-to-check-if-variable-is-string-with-python-2-and-3-compatibility

Might be some unrelated pandas 0.19 as well as forecast module problems, too.

**Comment by lukewitmer** [comment]
Interesting. Good point on basestring not being in python 3. I'll take a more detailed look at it tonight or tomorrow, as well as actually testing against python3 (instead of in python2 with future imports which is what I tested before submitting the PR).

**Comment by wholmgren** [comment]
I reran the travis tests for this PR now that #247 is merged. It looks like the only issue here is the basestring issue on Python 3 and hopefully the fix is as simple as advertised. I'll wait to release 0.4.1 if you can try that in the next 24 hours. Please also add a note and your name or username to the whatsnew file.

**Comment by wholmgren** [comment]
@lukewitmer are you still interested in pursuing this fix or can we close it and #244? I'm trying to clean up some issues and PRs. I can also take a quick attempt at it if you check the "allow edits from maintainers" box at the bottom of the right most column. Thanks!

**Comment by wholmgren** [comment]
@lukewitmer feel free to reopen if you want to finish this.

**Pull request closed without merging**
