### PR TITLE
BUG: constrain cftime to >=1.1.1

### LINKED ISSUE #944: BUG: netcdf4 conversion error in forecast.py
**Describe the bug**
The method `get_data()` from the parent class `ForecastModel` has a handling NETCDF data. It produces the following error on multiple tests within `test_forecast.py`:

`TypeError: <class 'cftime._cftime.DatetimeGregorian'> is not convertible to datetime`

**To Reproduce**
Run the command locally:

`pytest pvlib/tests/test_forecast.py --remote-data --pdb` 

This command will ensure the tests marked as `remote_data` are run and you'll be dropped into a pdb debugger.

**Expected behavior**
The formatted data would be received without error.

**Screenshots**

**Versions:**
 - ``pvlib.__version__``: 0.7.1 master
 - ``pandas.__version__``: 1.0.3
 - python: 3.7.4

**Additional context**
I'm unsure about the underlying origin but the disconnect seems to come through `get_data()` -> `_netcdf2pandas()` -> `set_time()` where `num2date` supplies a DatetimeGregorian that Pandas can't process. 

It's notable that there is a suggestion on line 279 of forecast.py about the potential to move to xarray's implementation of NetCDF rather than using the `_netcdf2pandas()` method. This avenue likely has the potential to be easier than continuing a pvlib implementation.

### PR DESCRIPTION
**Pull request by CameronTStark**
- [x] Closes #944 
 - [x] I am familiar with the [contributing guidelines](https://pvlib-python.readthedocs.io/en/latest/contributing.html)
 - [x] Adds description and name entries in the appropriate "what's new" file in [`docs/sphinx/source/whatsnew`](https://github.com/pvlib/pvlib-python/tree/master/docs/sphinx/source/whatsnew) for all changes. Includes link to the GitHub Issue with `` :issue:`num` `` or this Pull Request with `` :pull:`num` ``. Includes contributor name and/or GitHub username (link with `` :ghuser:`user` ``).
 - [x] Pull request is nearly complete and ready for detailed review.
 - [x] Maintainer: Appropriate GitHub Labels and Milestone are assigned to the Pull Request and linked Issue.

Limiting cftime<=1.1.0 . This is a few releases ahead of the suggested 1.0.4 but still passes all tests.

### CODE REVIEW

**Comment by CameronTStark** [comment]
It's good that everything checked out on this run. I reran the failing tests from #937 and they still fail confirming that this is indeed a fix. 

I'll add to what's new and this should be ready for approval thereafter.

**Comment by CameronTStark** [comment]
This is ready for review.

This is by no means the solution and an issue to address needs to be drafted unless #920 encompasses it. I'll make the issue unless If someone who knows the inner workings of forecast.py and/or how this interacts with it can describe what needs to be done.

**Comment by CameronTStark** [comment]
As proof of the error I pushed after reverting this branch to master to get the test results. [Link to test results](https://dev.azure.com/solararbiter/pvlib%20python/_build/results?buildId=3016&view=logs&j=ea977d73-b8d6-59cf-b2df-c65a31e93ffc&t=2690bf14-3208-5a31-bf74-aa7a625c04e8&l=56) 

The error is fixed in Python3.6 and above (thanks @kanderso-nrel!) but persists in Python3.5 even with the changes. [Link to 3.5 error](https://dev.azure.com/solararbiter/pvlib%20python/_build/results?buildId=3016&view=logs&j=ea977d73-b8d6-59cf-b2df-c65a31e93ffc&t=2690bf14-3208-5a31-bf74-aa7a625c04e8&l=56)

cftime only supports >=3.6 and therefore doesn't have the kwarg `only_use_python_datetimes` for the downloaded version in the 3.5 test. 

The Test_conda_linux environment for Python3.5 installs 1.0.0b1. [Link to installed packages for 3.5 test](https://dev.azure.com/solararbiter/pvlib%20python/_build/results?buildId=3018&view=logs&j=06aebe0f-636a-5f93-19d5-0c37b58d55c8&t=43a83552-1514-5067-ea2c-2784ec4ae593&l=26)

All other Python versions install the most current 1.1.1 [Link to installed packages for 3.6 test](https://dev.azure.com/solararbiter/pvlib%20python/_build/results?buildId=3018&view=logs&j=ea977d73-b8d6-59cf-b2df-c65a31e93ffc&t=cd94e248-e7b1-520e-8d46-503eae4a1c0b&l=25)

The most obvious options are:
* Go back to pinning 1.1.0
* Drop support for Python3.5

Are there any more options?

**Comment by wholmgren** [comment]
Pinning is ok with me, but Another option is to xfail or skip the test if run on 3.5. I’d rather wait until 0.8 to drop 3.5.

**Comment by CameronTStark** [comment]
I think this, after much learning, is ready for review. 

Thanks for your patience for the time it took and notification spam. 

Please let me know if the codecov/patch failure needs to be addressed for test. I don't think so but there may be some historical context in which I'm unaware.

**Comment by wholmgren** [comment]
ok to ignore this codecov/patch failure. Ok with me to just let it break on python 3.5 if we're no longer supporting it in pvlib 0.8.

**Comment by CameronTStark** [comment]
When you get a moment @wholmgren can you please merge this? Thanks!

**Pull request merged**
