### PR TITLE
Update tutorial notebooks for compat with current pvlib

### LINKED ISSUE #995: Update tutorials for pvlib >=0.7
Some tutorials e.g. `forecast_to_power.ipynb` use functions that are deprecated, e.g., `pvsystem.sapm_celltemp`. 

A broader question is how we test and maintain the iPython notebooks to keep up with pvlib changes.

### PR DESCRIPTION
**Pull request by kanderso-nrel**
- [x] Closes #995
 - [x] I am familiar with the [contributing guidelines](https://pvlib-python.readthedocs.io/en/latest/contributing.html)
 - [ ] Tests added
 - ~Updates entries to [`docs/sphinx/source/api.rst`](https://github.com/pvlib/pvlib-python/blob/master/docs/sphinx/source/api.rst) for API changes.~
 - [ ] Adds description and name entries in the appropriate "what's new" file in [`docs/sphinx/source/whatsnew`](https://github.com/pvlib/pvlib-python/tree/master/docs/sphinx/source/whatsnew) for all changes. Includes link to the GitHub Issue with `` :issue:`num` `` or this Pull Request with `` :pull:`num` ``. Includes contributor name and/or GitHub username (link with `` :ghuser:`user` ``).
 - ~New code is fully documented. Includes [numpydoc](https://numpydoc.readthedocs.io/en/latest/format.html) compliant docstrings, examples, and comments where necessary.~
 - [x] Pull request is nearly complete and ready for detailed review.
 - [x] Maintainer: Appropriate GitHub Labels and Milestone are assigned to the Pull Request and linked Issue.

Here is an updated set of notebooks.  I'll echo @mikofski's suggestion to use nbdime to review the changes.  If you clone this branch, you can spawn a handy visual diff between commits in the browser with `nbdiff-web 065e10c 97c6698 docs\tutorials\atmosphere.ipynb`

I also made some other changes unrelated to pvlib compat -- semicolons to suppress matplotlib output text and such.  I also removed the section in `tmy.ipynb` that called out to the RREDC website (see #996).  Lastly, I made the notebooks work with the nbval pytest plugin (added comments like `# NBVAL_SKIP` for cells that shouldn't be tested) -- run `pytest --nbval docs\tutorials\atmosphere.ipynb` if you want to check it out. 

I am aware of two remaining issues, neither of which I have investigated yet.  I would not be upset if someone else figures out what's going on with these before I do :)
- pvsystem.ipynb: de soto modeling at the end is different
- tracking.ipynb:  some traces get pretty wacky in the negative axis tilt plots (north-facing)

### CODE REVIEW

**Comment by cwhanse** [comment]
@kanderso-nrel about `pvsystem.ipynb`: when I vew the [notebook ](https://github.com/pvlib/pvlib-python/blob/b420f2b190be356413bf9434339fe50dfbb15814/docs/tutorials/pvsystem.ipynb) via the "Files changed" tab, all looks fine.  When I view the [notebook](https://nbviewer.jupyter.org/github/pvlib/pvlib-python/blob/master/docs/tutorials/pvsystem.ipynb#Single-diode-model) via the [link](https://nbviewer.jupyter.org/github/pvlib/pvlib-python/tree/master/docs/tutorials/) on the RTD index page, there are Type errors in the [desoto](https://nbviewer.jupyter.org/github/pvlib/pvlib-python/blob/master/docs/tutorials/pvsystem.ipynb#desoto) section, and a strange message in the [Single diode model](https://nbviewer.jupyter.org/github/pvlib/pvlib-python/blob/master/docs/tutorials/pvsystem.ipynb#Single-diode-model) section.

Maybe that provides some clues?

**Comment by kanderso-nrel** [comment]
I think the link on the RTD index page is pointing to the current version on master, which I agree has some errors.  I was trying to get the notebooks in this PR to recreate the versions on master, but I'm starting to think that the version of `pvsystem.ipynb` on master is not self-consistent, at least in the De Soto section and after.  Putting aside the error, some results seem strange (Rsh<20?).  So if this PR's version of `pvsystem.ipynb` looks acceptable on its own, I'm inclined to call it good.

For tracking.ipynb, maybe we should leave it with some funky plots until we pick up #823 again?  I suspect that implementing the method Mark and I worked out for non-parallel slope would solve those problems as a side effect.

**Comment by cwhanse** [comment]
> Putting aside the error, some results seem strange (Rsh<20?). 

The CEC module parameters changed between the two notebooks.  SAM used to supply a generic "Example Module", maybe it still does, but we're no longer using that module in the notebook or test fixtures, which I think is an improvement.

> So if this PR's version of `pvsystem.ipynb` looks acceptable on its own, I'm inclined to call it good.

Agree. There's a lot of little edits I'd suggest but I don't know how to comment on the ipynb file, so OK for now.
 
> For tracking.ipynb, maybe we should leave it with some funky plots until we pick up #823 again? I suspect that implementing the method Mark and I worked out for non-parallel slope would solve those problems as a side effect.

Also agree.

I've looked at the new notebooks. I agree that the PR meets its objective, that the notebooks work with pvlbi v0.7.2.  Further improvement of the notebooks can be in different PRs.

@kanderso-nrel what do you need next here?

**Comment by kanderso-nrel** [comment]
Thanks @cwhanse for going through the notebooks.  I don't intend to make any more changes to this PR unless requested from reviewers.  

I do still think it's worth trying to add the notebooks to the CI testing using nbval, but figuring out the best way might take some iteration and I'd prefer to do that in another PR later.  For now the notebooks can be tested with nbval locally if anyone cares to, which is a good step forward itself in addition to bringing the notebooks up to date with the current API.

**Pull request merged**
